// Code generated by perseid. DO NOT EDIT.

package meteroid

import (
	"encoding/json"
	"time"
)

// AddOnEvent is the AddOnEvent object of the Meteroid API.
type AddOnEvent struct {
	AddOnID AddOnID `json:"add_on_id"`

	// RFC 3339 timestamp.
	CreatedAt time.Time `json:"created_at"`

	Description *string `json:"description,omitempty"`

	FeeType *ProductFeeTypeEnum `json:"fee_type,omitempty"`

	MaxInstancesPerSubscription *int32 `json:"max_instances_per_subscription,omitempty"`

	Name string `json:"name"`

	PriceID PriceID `json:"price_id"`

	ProductID ProductID `json:"product_id"`

	SelfServiceable bool `json:"self_serviceable"`

	ID EventID `json:"id"`

	// RFC 3339 timestamp.
	Timestamp time.Time `json:"timestamp"`

	Type EventType `json:"type"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *AddOnEvent) UnmarshalJSON(data []byte) error {
	type plain AddOnEvent
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "add_on_id", "created_at", "description", "fee_type", "max_instances_per_subscription", "name", "price_id", "product_id", "self_serviceable", "id", "timestamp", "type")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v AddOnEvent) MarshalJSON() ([]byte, error) {
	type plain AddOnEvent
	return marshalWithExtra(plain(v), v.ExtraFields)
}
