// Code generated by perseid. DO NOT EDIT.

package meteroid

import (
	"context"
	"encoding/json"
	"net/http"
)

// AddOnsListOptions carries the optional query and header parameters of
// [AddOns.List]. Leave a field nil to omit it.
type AddOnsListOptions struct {
	Search *string

	Currency *string

	// Include archived add-ons in the results (default: false)
	IncludeArchived *bool

	// Sort order. Format: `column.direction`. Allowed columns: `name`, `created_at`. Direction: `asc` or `desc`. Default: `created_at.desc`.
	OrderBy *string

	// Page number (0-indexed)
	Page *int32

	// Number of items per page
	PerPage *int32
}

// AddOns groups the add ons operations of the Meteroid API.
type AddOns struct {
	client *Client
}

// Entitlements returns the entitlements API.
func (a *AddOns) Entitlements() *AddOnsEntitlements {
	return &AddOnsEntitlements{client: a.client}
}

// fetchList sends GET /api/v1/addons and decodes the response, for [AddOns.List].
func (a *AddOns) fetchList(ctx context.Context, options *AddOnsListOptions, opts ...RequestOption) (*AddOnListResponse, error) {
	req := newRequest(http.MethodGet, "/api/v1/addons", opts)
	req.errors = errorSchemas{
		"401": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
	}
	if options != nil && options.Search != nil {
		req.SetQueryParam("search", *options.Search)
	}
	if options != nil && options.Currency != nil {
		req.SetQueryParam("currency", *options.Currency)
	}
	if options != nil && options.IncludeArchived != nil {
		req.SetQueryParam("include_archived", formatBool(*options.IncludeArchived))
	}
	if options != nil && options.OrderBy != nil {
		req.SetQueryParam("order_by", *options.OrderBy)
	}
	if options != nil && options.Page != nil {
		req.SetQueryParam("page", formatInt(int64(*options.Page)))
	}
	if options != nil && options.PerPage != nil {
		req.SetQueryParam("per_page", formatInt(int64(*options.PerPage)))
	}
	var out AddOnListResponse
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// AddOnsListPage is a page of [AddOns.List]. It embeds the
// decoded [AddOnListResponse], promoting its fields, with the Items of the page; a field
// named like a page member stays reachable through the embedded AddOnListResponse.
type AddOnsListPage struct {
	AddOnListResponse

	// Items holds the items of this page.
	Items []AddOn

	next func(ctx context.Context) (*AddOnsListPage, error)
}

// HasNextPage reports whether another page follows this one.
func (p *AddOnsListPage) HasNextPage() bool {
	return p != nil && p.next != nil
}

// NextPage fetches the page after this one. It returns nil and no error after
// the last page.
func (p *AddOnsListPage) NextPage(ctx context.Context) (*AddOnsListPage, error) {
	if !p.HasNextPage() {
		return nil, nil
	}
	return p.next(ctx)
}

// MarshalJSON encodes the AddOnListResponse of the page, as received.
func (p AddOnsListPage) MarshalJSON() ([]byte, error) {
	return json.Marshal(&p.AddOnListResponse)
}

func (p *AddOnsListPage) pageItems() []AddOn { return p.Items }

// List add-ons
//
// [AddOns.ListAutoPaging] iterates over every item instead.
func (a *AddOns) List(ctx context.Context, options *AddOnsListOptions, opts ...RequestOption) (*AddOnsListPage, error) {
	var params AddOnsListOptions
	if options != nil {
		params = *options
	}
	resp, err := a.fetchList(ctx, &params, opts...)
	if err != nil {
		return nil, err
	}
	page := &AddOnsListPage{AddOnListResponse: *resp, Items: resp.Data}
	if len(page.Items) == 0 {
		return page, nil
	}
	current := int32(0)
	if params.Page != nil {
		current = *params.Page
	}
	if reached(current+1, resp.PaginationMeta.TotalPages) {
		return page, nil
	}
	next := current + 1
	params.Page = &next
	page.next = func(ctx context.Context) (*AddOnsListPage, error) {
		return a.List(ctx, &params, opts...)
	}
	return page, nil
}

// ListAutoPaging iterates over every item of [AddOns.List], fetching
// further pages on demand.
func (a *AddOns) ListAutoPaging(ctx context.Context, options *AddOnsListOptions, opts ...RequestOption) *AutoPager[AddOn] {
	return newAutoPager[AddOn](ctx, func(ctx context.Context) (*AddOnsListPage, error) {
		return a.List(ctx, options, opts...)
	})
}

// Create an add-on
func (a *AddOns) Create(ctx context.Context, createAddOnRequest CreateAddOnRequest, opts ...RequestOption) (*AddOn, error) {
	req := newRequest(http.MethodPost, "/api/v1/addons", opts)
	req.errors = errorSchemas{
		"400": errorSchema[RestErrorResponse],
		"401": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
	}
	req.SetJSONBody(createAddOnRequest)
	var out AddOn
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Retrieve sends GET /api/v1/addons/{addon_id}.
//
// Get add-on details
func (a *AddOns) Retrieve(ctx context.Context, addonID string, opts ...RequestOption) (*AddOn, error) {
	req := newRequest(http.MethodGet, "/api/v1/addons/{addon_id}", opts)
	req.SetPathParam("addon_id", addonID)
	req.errors = errorSchemas{
		"401": errorSchema[RestErrorResponse],
		"404": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
	}
	var out AddOn
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Update an add-on
func (a *AddOns) Update(ctx context.Context, addonID string, updateAddOnRequest UpdateAddOnRequest, opts ...RequestOption) (*AddOn, error) {
	req := newRequest(http.MethodPatch, "/api/v1/addons/{addon_id}", opts)
	req.SetPathParam("addon_id", addonID)
	req.errors = errorSchemas{
		"400": errorSchema[RestErrorResponse],
		"401": errorSchema[RestErrorResponse],
		"404": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
	}
	req.SetJSONBody(updateAddOnRequest)
	var out AddOn
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Archive an add-on
func (a *AddOns) Archive(ctx context.Context, addonID string, opts ...RequestOption) error {
	req := newRequest(http.MethodPost, "/api/v1/addons/{addon_id}/archive", opts)
	req.SetPathParam("addon_id", addonID)
	req.errors = errorSchemas{
		"401": errorSchema[RestErrorResponse],
		"404": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
	}
	return a.client.execute(ctx, req, nil)
}

// Unarchive an add-on
func (a *AddOns) Unarchive(ctx context.Context, addonID string, opts ...RequestOption) error {
	req := newRequest(http.MethodPost, "/api/v1/addons/{addon_id}/unarchive", opts)
	req.SetPathParam("addon_id", addonID)
	req.errors = errorSchemas{
		"401": errorSchema[RestErrorResponse],
		"404": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
	}
	return a.client.execute(ctx, req, nil)
}
