// Code generated by perseid. DO NOT EDIT.

package meteroid

import (
	"context"
	"net/http"
)

// AddOnsEntitlements groups the add ons entitlements operations of the Meteroid API.
type AddOnsEntitlements struct {
	client *Client
}

// List add-on entitlements
func (a *AddOnsEntitlements) List(ctx context.Context, addonID string, opts ...RequestOption) (*ResolvedEntitlementListResponse, error) {
	req := newRequest(http.MethodGet, "/api/v1/addons/{addon_id}/entitlements", opts)
	req.SetPathParam("addon_id", addonID)
	req.errors = errorSchemas{
		"401": errorSchema[RestErrorResponse],
		"404": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
	}
	var out ResolvedEntitlementListResponse
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Create add-on entitlements
//
// Entitlements already present on this add-on are skipped.
func (a *AddOnsEntitlements) Create(ctx context.Context, addonID string, createEntitlementsRequest CreateEntitlementsRequest, opts ...RequestOption) (*EntitlementListResponse, error) {
	req := newRequest(http.MethodPost, "/api/v1/addons/{addon_id}/entitlements", opts)
	req.SetPathParam("addon_id", addonID)
	req.errors = errorSchemas{
		"400": errorSchema[RestErrorResponse],
		"401": errorSchema[RestErrorResponse],
		"404": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
	}
	req.SetJSONBody(createEntitlementsRequest)
	var out EntitlementListResponse
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
