// Code generated by perseid. DO NOT EDIT.

package meteroid_test

import (
	"testing"

	"github.com/meteroid-oss/meteroid-go"
)

func TestAddOns_List(t *testing.T) {
	client, requests := mock(200, "application/json", `{"data":[{"created_at":"2023-12-31T23:59:59.999-05:30","id":"add_on_id_0","name":"sample","price_id":"price_id_47","product_id":"product_id_67","self_serviceable":false}],"pagination_meta":{"page":-123456789,"per_page":-123456789,"total_items":-9007199254740993,"total_pages":123456789}}`)
	call(t, client.AddOns().List, nil)
	expect(t, requests, "GET /api/v1/addons")
}

func TestAddOns_Create(t *testing.T) {
	client, requests := mock(200, "application/json", `{"created_at":"2024-03-15T10:30:45.123+02:00","id":"add_on_id_90","name":"sample","price_id":"price_id_99","product_id":"product_id_90","self_serviceable":false}`)
	call(t, client.AddOns().Create, decode[meteroid.CreateAddOnRequest](t, `{"name":"sample","price_id":"price_id_44","product_id":"product_id_47"}`))
	expect(t, requests, "POST /api/v1/addons")
}

func TestAddOns_Retrieve(t *testing.T) {
	client, requests := mock(200, "application/json", `{"created_at":"2024-03-15T10:30:45.123+02:00","id":"add_on_id_90","name":"sample","price_id":"price_id_99","product_id":"product_id_90","self_serviceable":false}`)
	call(t, client.AddOns().Retrieve, "addon_id")
	expect(t, requests, "GET /api/v1/addons/addon_id")
}

func TestAddOns_Update(t *testing.T) {
	client, requests := mock(200, "application/json", `{"created_at":"2024-03-15T10:30:45.123+02:00","id":"add_on_id_90","name":"sample","price_id":"price_id_99","product_id":"product_id_90","self_serviceable":false}`)
	call(t, client.AddOns().Update, "addon_id", decode[meteroid.UpdateAddOnRequest](t, `{}`))
	expect(t, requests, "PATCH /api/v1/addons/addon_id")
}

func TestAddOns_Archive(t *testing.T) {
	client, requests := mock(204, "", ``)
	call(t, client.AddOns().Archive, "addon_id")
	expect(t, requests, "POST /api/v1/addons/addon_id/archive")
}

func TestAddOns_Unarchive(t *testing.T) {
	client, requests := mock(204, "", ``)
	call(t, client.AddOns().Unarchive, "addon_id")
	expect(t, requests, "POST /api/v1/addons/addon_id/unarchive")
}
