// Code generated by perseid. DO NOT EDIT.

package meteroid

import (
	"encoding/json"
	"time"
)

// AddOn is the AddOn object of the Meteroid API.
type AddOn struct {
	// RFC 3339 timestamp.
	ArchivedAt *time.Time `json:"archived_at,omitempty"`

	// RFC 3339 timestamp.
	CreatedAt time.Time `json:"created_at"`

	Description *string `json:"description,omitempty"`

	Entitlements []Entitlement `json:"entitlements,omitempty"`

	FeeType *ProductFeeTypeEnum `json:"fee_type,omitempty"`

	ID AddOnID `json:"id"`

	MaxInstancesPerSubscription *int32 `json:"max_instances_per_subscription,omitempty"`

	Name string `json:"name"`

	PriceID PriceID `json:"price_id"`

	ProductID ProductID `json:"product_id"`

	SelfServiceable bool `json:"self_serviceable"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *AddOn) UnmarshalJSON(data []byte) error {
	type plain AddOn
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "AddOn", "created_at", "id", "name", "price_id", "product_id", "self_serviceable")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "archived_at", "created_at", "description", "entitlements", "fee_type", "id", "max_instances_per_subscription", "name", "price_id", "product_id", "self_serviceable")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v AddOn) MarshalJSON() ([]byte, error) {
	type plain AddOn
	return marshalWithExtra(plain(v), v.ExtraFields)
}
