// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// Address is the Address object of the Meteroid API.
type Address struct {
	City *string `json:"city,omitempty"`

	Country *CountryCode `json:"country,omitempty"`

	Line1 *string `json:"line1,omitempty"`

	Line2 *string `json:"line2,omitempty"`

	State *string `json:"state,omitempty"`

	ZipCode *string `json:"zip_code,omitempty"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *Address) UnmarshalJSON(data []byte) error {
	type plain Address
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "city", "country", "line1", "line2", "state", "zip_code")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v Address) MarshalJSON() ([]byte, error) {
	type plain Address
	return marshalWithExtra(plain(v), v.ExtraFields)
}
