// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// AvailableParameters is the AvailableParameters object of the Meteroid API.
type AvailableParameters struct {
	// Map of component_id -> available billing periods (e.g., "MONTHLY", "ANNUAL")
	BillingPeriods map[string][]BillingPeriodEnum `json:"billing_periods,omitempty"`

	// Map of component_id -> available capacity values
	CapacityThresholds map[string][]int64 `json:"capacity_thresholds,omitempty"`

	// List of component_ids that support slot parametrization (initial slot count)
	SlotComponents []string `json:"slot_components,omitempty"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *AvailableParameters) UnmarshalJSON(data []byte) error {
	type plain AvailableParameters
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "billing_periods", "capacity_thresholds", "slot_components")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v AvailableParameters) MarshalJSON() ([]byte, error) {
	type plain AvailableParameters
	return marshalWithExtra(plain(v), v.ExtraFields)
}
