// Code generated by perseid. DO NOT EDIT.

package meteroid

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

// BatchJobResponse is the BatchJobResponse object of the Meteroid API.
type BatchJobResponse struct {
	// RFC 3339 timestamp.
	CompletedAt *time.Time `json:"completed_at,omitempty"`

	// RFC 3339 timestamp.
	CreatedAt time.Time `json:"created_at"`

	CreatedBy uuid.UUID `json:"created_by"`

	FailedItems int32 `json:"failed_items"`

	ID BatchJobID `json:"id"`

	InputFileName *string `json:"input_file_name,omitempty"`

	JobType BatchJobType `json:"job_type"`

	ProcessedItems int32 `json:"processed_items"`

	Status BatchJobStatus `json:"status"`

	TotalItems *int32 `json:"total_items,omitempty"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *BatchJobResponse) UnmarshalJSON(data []byte) error {
	type plain BatchJobResponse
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "completed_at", "created_at", "created_by", "failed_items", "id", "input_file_name", "job_type", "processed_items", "status", "total_items")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v BatchJobResponse) MarshalJSON() ([]byte, error) {
	type plain BatchJobResponse
	return marshalWithExtra(plain(v), v.ExtraFields)
}
