// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// BillingCycleResetPeriod is the BillingCycleResetPeriod object of the Meteroid API.
//
// Resets each time your subscription renews — anchored to your billing cycle.
type BillingCycleResetPeriod struct {
	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *BillingCycleResetPeriod) UnmarshalJSON(data []byte) error {
	type plain BillingCycleResetPeriod
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "BillingCycleResetPeriod")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields)
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v BillingCycleResetPeriod) MarshalJSON() ([]byte, error) {
	type plain BillingCycleResetPeriod
	return marshalWithExtra(plain(v), v.ExtraFields)
}
