// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// BooleanConfigValue is the BooleanConfigValue object of the Meteroid API.
//
// A boolean config value.
type BooleanConfigValue struct {
	Value bool `json:"value"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *BooleanConfigValue) UnmarshalJSON(data []byte) error {
	type plain BooleanConfigValue
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "value")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v BooleanConfigValue) MarshalJSON() ([]byte, error) {
	type plain BooleanConfigValue
	return marshalWithExtra(plain(v), v.ExtraFields)
}
