// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// BooleanEntitlementValue is the BooleanEntitlementValue object of the Meteroid API.
type BooleanEntitlementValue struct {
	Enabled bool `json:"enabled"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *BooleanEntitlementValue) UnmarshalJSON(data []byte) error {
	type plain BooleanEntitlementValue
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "enabled")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v BooleanEntitlementValue) MarshalJSON() ([]byte, error) {
	type plain BooleanEntitlementValue
	return marshalWithExtra(plain(v), v.ExtraFields)
}
