// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// CalendarResetPeriod is the CalendarResetPeriod object of the Meteroid API.
//
// Resets on calendar boundaries (e.g. the 1st of every month) — not tied to subscription start date.
type CalendarResetPeriod struct {
	Interval int32 `json:"interval"`

	Unit CalendarUnit `json:"unit"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *CalendarResetPeriod) UnmarshalJSON(data []byte) error {
	type plain CalendarResetPeriod
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "interval", "unit")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v CalendarResetPeriod) MarshalJSON() ([]byte, error) {
	type plain CalendarResetPeriod
	return marshalWithExtra(plain(v), v.ExtraFields)
}
