// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// CancelSubscriptionRequest is the CancelSubscriptionRequest object of the Meteroid API.
type CancelSubscriptionRequest struct {
	// If not provided, the cancellation will be effective at the end of the current billing or committed period.
	EffectiveDate *Date `json:"effective_date,omitempty"`

	Reason *string `json:"reason,omitempty"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *CancelSubscriptionRequest) UnmarshalJSON(data []byte) error {
	type plain CancelSubscriptionRequest
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "CancelSubscriptionRequest")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "effective_date", "reason")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v CancelSubscriptionRequest) MarshalJSON() ([]byte, error) {
	type plain CancelSubscriptionRequest
	return marshalWithExtra(plain(v), v.ExtraFields)
}
