// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// CancelCheckoutSessionResponse is the CancelCheckoutSessionResponse object of the Meteroid API.
type CancelCheckoutSessionResponse struct {
	Session CheckoutSession `json:"session"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *CancelCheckoutSessionResponse) UnmarshalJSON(data []byte) error {
	type plain CancelCheckoutSessionResponse
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "CancelCheckoutSessionResponse", "session")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "session")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v CancelCheckoutSessionResponse) MarshalJSON() ([]byte, error) {
	type plain CancelCheckoutSessionResponse
	return marshalWithExtra(plain(v), v.ExtraFields)
}
