// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// CapacityThreshold is the CapacityThreshold object of the Meteroid API.
type CapacityThreshold struct {
	IncludedAmount int64 `json:"included_amount"`

	PerUnitOverage string `json:"per_unit_overage"`

	Price string `json:"price"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *CapacityThreshold) UnmarshalJSON(data []byte) error {
	type plain CapacityThreshold
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "included_amount", "per_unit_overage", "price")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v CapacityThreshold) MarshalJSON() ([]byte, error) {
	type plain CapacityThreshold
	return marshalWithExtra(plain(v), v.ExtraFields)
}
