// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// CapacityPlanFee is the CapacityPlanFee object of the Meteroid API.
//
// Capacity-based fee with included committed usage and overage
type CapacityPlanFee struct {
	Cadence BillingPeriodEnum `json:"cadence"`

	MetricID BillableMetricID `json:"metric_id"`

	Thresholds RequiredSlice[CapacityThreshold] `json:"thresholds"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *CapacityPlanFee) UnmarshalJSON(data []byte) error {
	type plain CapacityPlanFee
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "CapacityPlanFee", "cadence", "metric_id", "thresholds")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "cadence", "metric_id", "thresholds")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v CapacityPlanFee) MarshalJSON() ([]byte, error) {
	type plain CapacityPlanFee
	return marshalWithExtra(plain(v), v.ExtraFields)
}
