// Code generated by perseid. DO NOT EDIT.

package meteroid

import (
	"context"
	"net/http"
)

// CheckoutSessionsListOptions carries the optional query and header parameters of
// [CheckoutSessions.List]. Leave a field nil to omit it.
type CheckoutSessionsListOptions struct {
	CustomerID *CustomerID

	Status *CheckoutSessionStatus
}

// CheckoutSessions groups the checkout sessions operations of the Meteroid API.
type CheckoutSessions struct {
	client *Client
}

// List checkout sessions
func (a *CheckoutSessions) List(ctx context.Context, options *CheckoutSessionsListOptions, opts ...RequestOption) (*ListCheckoutSessionsResponse, error) {
	req := newRequest(http.MethodGet, "/api/v1/checkout-sessions", opts)
	req.errors = errorSchemas{
		"401": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
		"500": errorSchema[RestErrorResponse],
	}
	if options != nil && options.CustomerID != nil {
		req.SetQueryParam("customer_id", formatValue(*options.CustomerID))
	}
	if options != nil && options.Status != nil {
		req.SetQueryParam("status", formatValue(*options.Status))
	}
	var out ListCheckoutSessionsResponse
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Create a checkout session
func (a *CheckoutSessions) Create(ctx context.Context, createCheckoutSessionRequest CreateCheckoutSessionRequest, opts ...RequestOption) (*CreateCheckoutSessionResponse, error) {
	req := newRequest(http.MethodPost, "/api/v1/checkout-sessions", opts)
	req.errors = errorSchemas{
		"400": errorSchema[RestErrorResponse],
		"401": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
		"500": errorSchema[RestErrorResponse],
	}
	req.SetJSONBody(createCheckoutSessionRequest)
	var out CreateCheckoutSessionResponse
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Retrieve sends GET /api/v1/checkout-sessions/{id}.
//
// Get a checkout session by ID
func (a *CheckoutSessions) Retrieve(ctx context.Context, id string, opts ...RequestOption) (*GetCheckoutSessionResponse, error) {
	req := newRequest(http.MethodGet, "/api/v1/checkout-sessions/{id}", opts)
	req.SetPathParam("id", id)
	req.errors = errorSchemas{
		"401": errorSchema[RestErrorResponse],
		"404": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
		"500": errorSchema[RestErrorResponse],
	}
	var out GetCheckoutSessionResponse
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Cancel a checkout session
func (a *CheckoutSessions) Cancel(ctx context.Context, id string, opts ...RequestOption) (*CancelCheckoutSessionResponse, error) {
	req := newRequest(http.MethodPost, "/api/v1/checkout-sessions/{id}/cancel", opts)
	req.SetPathParam("id", id)
	req.errors = errorSchemas{
		"400": errorSchema[RestErrorResponse],
		"401": errorSchema[RestErrorResponse],
		"404": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
		"500": errorSchema[RestErrorResponse],
	}
	var out CancelCheckoutSessionResponse
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
