// Code generated by perseid. DO NOT EDIT.

package meteroid

import (
	"encoding/json"
	"time"
)

// CheckoutSession is the CheckoutSession object of the Meteroid API.
type CheckoutSession struct {
	BillingDayAnchor *int32 `json:"billing_day_anchor,omitempty"`

	BillingStartDate *Date `json:"billing_start_date,omitempty"`

	CancelURL *string `json:"cancel_url,omitempty"`

	CheckoutType CheckoutType `json:"checkout_type"`

	CheckoutURL *string `json:"checkout_url,omitempty"`

	// RFC 3339 timestamp.
	CompletedAt *time.Time `json:"completed_at,omitempty"`

	CouponCode *string `json:"coupon_code,omitempty"`

	// RFC 3339 timestamp.
	CreatedAt time.Time `json:"created_at"`

	CustomerID CustomerID `json:"customer_id"`

	// When the session expires. None means the session never expires.
	// RFC 3339 timestamp.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`

	ID CheckoutSessionID `json:"id"`

	NetTerms *int32 `json:"net_terms,omitempty"`

	PaymentMethodsConfig *PaymentMethodsConfig `json:"payment_methods_config,omitempty"`

	PlanVersionID PlanVersionID `json:"plan_version_id"`

	Status CheckoutSessionStatus `json:"status"`

	SubscriptionID *SubscriptionID `json:"subscription_id,omitempty"`

	SuccessURL *string `json:"success_url,omitempty"`

	TrialDurationDays *int32 `json:"trial_duration_days,omitempty"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *CheckoutSession) UnmarshalJSON(data []byte) error {
	type plain CheckoutSession
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "CheckoutSession", "checkout_type", "created_at", "customer_id", "id", "plan_version_id", "status")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "billing_day_anchor", "billing_start_date", "cancel_url", "checkout_type", "checkout_url", "completed_at", "coupon_code", "created_at", "customer_id", "expires_at", "id", "net_terms", "payment_methods_config", "plan_version_id", "status", "subscription_id", "success_url", "trial_duration_days")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v CheckoutSession) MarshalJSON() ([]byte, error) {
	type plain CheckoutSession
	return marshalWithExtra(plain(v), v.ExtraFields)
}
