// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// ComponentParameters is the ComponentParameters object of the Meteroid API.
type ComponentParameters struct {
	BillingPeriod *BillingPeriodEnum `json:"billing_period,omitempty"`

	CommittedCapacity *int64 `json:"committed_capacity,omitempty"`

	InitialSlotCount *int32 `json:"initial_slot_count,omitempty"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *ComponentParameters) UnmarshalJSON(data []byte) error {
	type plain ComponentParameters
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "ComponentParameters")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "billing_period", "committed_capacity", "initial_slot_count")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v ComponentParameters) MarshalJSON() ([]byte, error) {
	type plain ComponentParameters
	return marshalWithExtra(plain(v), v.ExtraFields)
}
