// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// ComponentOverride is the ComponentOverride object of the Meteroid API.
type ComponentOverride struct {
	ComponentID PriceComponentID `json:"component_id"`

	Name string `json:"name"`

	PriceEntry PriceEntry `json:"price_entry"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *ComponentOverride) UnmarshalJSON(data []byte) error {
	type plain ComponentOverride
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "ComponentOverride", "component_id", "name", "price_entry")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "component_id", "name", "price_entry")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v ComponentOverride) MarshalJSON() ([]byte, error) {
	type plain ComponentOverride
	return marshalWithExtra(plain(v), v.ExtraFields)
}
