// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// ConfigFeatureType is the ConfigFeatureType object of the Meteroid API.
//
// A static, typed configuration value. No metric — resolved synchronously.
type ConfigFeatureType struct {
	// Allowed values when `value_type = SELECT`. Empty otherwise.
	Options []string `json:"options,omitempty"`

	// The feature's value type, fixed at creation.
	ValueType ConfigValueType `json:"value_type"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *ConfigFeatureType) UnmarshalJSON(data []byte) error {
	type plain ConfigFeatureType
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "ConfigFeatureType", "value_type")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "options", "value_type")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v ConfigFeatureType) MarshalJSON() ([]byte, error) {
	type plain ConfigFeatureType
	return marshalWithExtra(plain(v), v.ExtraFields)
}
