// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// ConfigEntitlementValue is the ConfigEntitlementValue object of the Meteroid API.
type ConfigEntitlementValue struct {
	Value ConfigValue `json:"value"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *ConfigEntitlementValue) UnmarshalJSON(data []byte) error {
	type plain ConfigEntitlementValue
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "value")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v ConfigEntitlementValue) MarshalJSON() ([]byte, error) {
	type plain ConfigEntitlementValue
	return marshalWithExtra(plain(v), v.ExtraFields)
}
