// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// ConfigResolvedEntitlementValue is the ConfigResolvedEntitlementValue object of the Meteroid API.
type ConfigResolvedEntitlementValue struct {
	Value ConfigValue `json:"value"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *ConfigResolvedEntitlementValue) UnmarshalJSON(data []byte) error {
	type plain ConfigResolvedEntitlementValue
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "value")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v ConfigResolvedEntitlementValue) MarshalJSON() ([]byte, error) {
	type plain ConfigResolvedEntitlementValue
	return marshalWithExtra(plain(v), v.ExtraFields)
}
