// Code generated by perseid. DO NOT EDIT.

package meteroid

import (
	"context"
	"net/http"
)

// Connect groups the connect operations of the Meteroid API.
type Connect struct {
	client *Client
}

// ListConnectedAccounts sends GET /api/v1/connected-accounts.
//
// # List connected accounts
//
// List all connected accounts for this platform.
func (a *Connect) ListConnectedAccounts(ctx context.Context, opts ...RequestOption) (*ConnectedAccountsResponse, error) {
	req := newRequest(http.MethodGet, "/api/v1/connected-accounts", opts)
	req.errors = errorSchemas{
		"429": errorSchema[RestErrorResponse],
	}
	var out ConnectedAccountsResponse
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateConnectedAccount sends POST /api/v1/connected-accounts.
//
// # Create connected account
//
// Create a new connected account (Express flow). Returns the account
// and an onboarding link for the user to complete setup.
func (a *Connect) CreateConnectedAccount(ctx context.Context, createConnectedAccountRequest CreateConnectedAccountRequest, opts ...RequestOption) (*ConnectedAccount, error) {
	req := newRequest(http.MethodPost, "/api/v1/connected-accounts", opts)
	req.errors = errorSchemas{
		"429": errorSchema[RestErrorResponse],
	}
	req.SetJSONBody(createConnectedAccountRequest)
	var out ConnectedAccount
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// RetrieveConnectedAccount sends GET /api/v1/connected-accounts/{id}.
//
// # Get connected account
//
// Retrieve a connected account by ID.
func (a *Connect) RetrieveConnectedAccount(ctx context.Context, id string, opts ...RequestOption) (*ConnectedAccount, error) {
	req := newRequest(http.MethodGet, "/api/v1/connected-accounts/{id}", opts)
	req.SetPathParam("id", id)
	req.errors = errorSchemas{
		"429": errorSchema[RestErrorResponse],
	}
	var out ConnectedAccount
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// DisconnectAccount sends DELETE /api/v1/connected-accounts/{id}.
//
// # Disconnect account
//
// Revoke a connected account. All associated tokens are invalidated.
func (a *Connect) DisconnectAccount(ctx context.Context, id string, opts ...RequestOption) error {
	req := newRequest(http.MethodDelete, "/api/v1/connected-accounts/{id}", opts)
	req.SetPathParam("id", id)
	req.errors = errorSchemas{
		"429": errorSchema[RestErrorResponse],
	}
	return a.client.execute(ctx, req, nil)
}

// CreateOnboardingLink sends POST /api/v1/connected-accounts/{id}/onboarding.
//
// # Create onboarding link
//
// Generate a new onboarding link for a connected account. Any existing
// unused link is invalidated. The link expires after a configured duration.
func (a *Connect) CreateOnboardingLink(ctx context.Context, id string, createOnboardingLinkRequest CreateOnboardingLinkRequest, opts ...RequestOption) (*OnboardingLinkResponse, error) {
	req := newRequest(http.MethodPost, "/api/v1/connected-accounts/{id}/onboarding", opts)
	req.SetPathParam("id", id)
	req.errors = errorSchemas{
		"429": errorSchema[RestErrorResponse],
	}
	req.SetJSONBody(createOnboardingLinkRequest)
	var out OnboardingLinkResponse
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
