// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// ConnectedAccountsResponse is the ConnectedAccountsResponse object of the Meteroid API.
type ConnectedAccountsResponse struct {
	Data RequiredSlice[ConnectedAccount] `json:"data"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *ConnectedAccountsResponse) UnmarshalJSON(data []byte) error {
	type plain ConnectedAccountsResponse
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "ConnectedAccountsResponse", "data")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "data")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v ConnectedAccountsResponse) MarshalJSON() ([]byte, error) {
	type plain ConnectedAccountsResponse
	return marshalWithExtra(plain(v), v.ExtraFields)
}
