// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// CouponLineItem is the CouponLineItem object of the Meteroid API.
type CouponLineItem struct {
	CouponID string `json:"coupon_id"`

	Name string `json:"name"`

	Total int64 `json:"total"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *CouponLineItem) UnmarshalJSON(data []byte) error {
	type plain CouponLineItem
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "coupon_id", "name", "total")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v CouponLineItem) MarshalJSON() ([]byte, error) {
	type plain CouponLineItem
	return marshalWithExtra(plain(v), v.ExtraFields)
}
