// Code generated by perseid. DO NOT EDIT.

package meteroid

import (
	"context"
	"encoding/json"
	"net/http"
)

// CouponsListOptions carries the optional query and header parameters of
// [Coupons.List]. Leave a field nil to omit it.
type CouponsListOptions struct {
	Search *string

	Filter *CouponFilter

	// Sort order. Format: `column.direction`. Allowed columns: `code`, `created_at`, `expires_at`. Direction: `asc` or `desc`. Default: `created_at.desc`.
	OrderBy *string

	// Page number (0-indexed)
	Page *int32

	// Number of items per page
	PerPage *int32
}

// Coupons groups the coupons operations of the Meteroid API.
type Coupons struct {
	client *Client
}

// fetchList sends GET /api/v1/coupons and decodes the response, for [Coupons.List].
func (a *Coupons) fetchList(ctx context.Context, options *CouponsListOptions, opts ...RequestOption) (*CouponListResponse, error) {
	req := newRequest(http.MethodGet, "/api/v1/coupons", opts)
	req.errors = errorSchemas{
		"401": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
	}
	if options != nil && options.Search != nil {
		req.SetQueryParam("search", *options.Search)
	}
	if options != nil && options.Filter != nil {
		req.SetQueryParam("filter", formatValue(*options.Filter))
	}
	if options != nil && options.OrderBy != nil {
		req.SetQueryParam("order_by", *options.OrderBy)
	}
	if options != nil && options.Page != nil {
		req.SetQueryParam("page", formatInt(int64(*options.Page)))
	}
	if options != nil && options.PerPage != nil {
		req.SetQueryParam("per_page", formatInt(int64(*options.PerPage)))
	}
	var out CouponListResponse
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// CouponsListPage is a page of [Coupons.List]. It embeds the
// decoded [CouponListResponse], promoting its fields, with the Items of the page; a field
// named like a page member stays reachable through the embedded CouponListResponse.
type CouponsListPage struct {
	CouponListResponse

	// Items holds the items of this page.
	Items []Coupon

	next func(ctx context.Context) (*CouponsListPage, error)
}

// HasNextPage reports whether another page follows this one.
func (p *CouponsListPage) HasNextPage() bool {
	return p != nil && p.next != nil
}

// NextPage fetches the page after this one. It returns nil and no error after
// the last page.
func (p *CouponsListPage) NextPage(ctx context.Context) (*CouponsListPage, error) {
	if !p.HasNextPage() {
		return nil, nil
	}
	return p.next(ctx)
}

// MarshalJSON encodes the CouponListResponse of the page, as received.
func (p CouponsListPage) MarshalJSON() ([]byte, error) {
	return json.Marshal(&p.CouponListResponse)
}

func (p *CouponsListPage) pageItems() []Coupon { return p.Items }

// List coupons
//
// [Coupons.ListAutoPaging] iterates over every item instead.
func (a *Coupons) List(ctx context.Context, options *CouponsListOptions, opts ...RequestOption) (*CouponsListPage, error) {
	var params CouponsListOptions
	if options != nil {
		params = *options
	}
	resp, err := a.fetchList(ctx, &params, opts...)
	if err != nil {
		return nil, err
	}
	page := &CouponsListPage{CouponListResponse: *resp, Items: resp.Data}
	if len(page.Items) == 0 {
		return page, nil
	}
	current := int32(0)
	if params.Page != nil {
		current = *params.Page
	}
	if reached(current+1, resp.PaginationMeta.TotalPages) {
		return page, nil
	}
	next := current + 1
	params.Page = &next
	page.next = func(ctx context.Context) (*CouponsListPage, error) {
		return a.List(ctx, &params, opts...)
	}
	return page, nil
}

// ListAutoPaging iterates over every item of [Coupons.List], fetching
// further pages on demand.
func (a *Coupons) ListAutoPaging(ctx context.Context, options *CouponsListOptions, opts ...RequestOption) *AutoPager[Coupon] {
	return newAutoPager[Coupon](ctx, func(ctx context.Context) (*CouponsListPage, error) {
		return a.List(ctx, options, opts...)
	})
}

// Create a coupon
func (a *Coupons) Create(ctx context.Context, createCouponRequest CreateCouponRequest, opts ...RequestOption) (*Coupon, error) {
	req := newRequest(http.MethodPost, "/api/v1/coupons", opts)
	req.errors = errorSchemas{
		"400": errorSchema[RestErrorResponse],
		"401": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
	}
	req.SetJSONBody(createCouponRequest)
	var out Coupon
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Retrieve sends GET /api/v1/coupons/{coupon_id}.
//
// Get coupon details
func (a *Coupons) Retrieve(ctx context.Context, couponID string, opts ...RequestOption) (*Coupon, error) {
	req := newRequest(http.MethodGet, "/api/v1/coupons/{coupon_id}", opts)
	req.SetPathParam("coupon_id", couponID)
	req.errors = errorSchemas{
		"401": errorSchema[RestErrorResponse],
		"404": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
	}
	var out Coupon
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Update a coupon
func (a *Coupons) Update(ctx context.Context, couponID string, updateCouponRequest UpdateCouponRequest, opts ...RequestOption) (*Coupon, error) {
	req := newRequest(http.MethodPatch, "/api/v1/coupons/{coupon_id}", opts)
	req.SetPathParam("coupon_id", couponID)
	req.errors = errorSchemas{
		"400": errorSchema[RestErrorResponse],
		"401": errorSchema[RestErrorResponse],
		"404": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
	}
	req.SetJSONBody(updateCouponRequest)
	var out Coupon
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Archive a coupon
func (a *Coupons) Archive(ctx context.Context, couponID string, opts ...RequestOption) error {
	req := newRequest(http.MethodPost, "/api/v1/coupons/{coupon_id}/archive", opts)
	req.SetPathParam("coupon_id", couponID)
	req.errors = errorSchemas{
		"401": errorSchema[RestErrorResponse],
		"404": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
	}
	return a.client.execute(ctx, req, nil)
}

// Disable a coupon
func (a *Coupons) Disable(ctx context.Context, couponID string, opts ...RequestOption) error {
	req := newRequest(http.MethodPost, "/api/v1/coupons/{coupon_id}/disable", opts)
	req.SetPathParam("coupon_id", couponID)
	req.errors = errorSchemas{
		"401": errorSchema[RestErrorResponse],
		"404": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
	}
	return a.client.execute(ctx, req, nil)
}

// Enable a coupon
func (a *Coupons) Enable(ctx context.Context, couponID string, opts ...RequestOption) error {
	req := newRequest(http.MethodPost, "/api/v1/coupons/{coupon_id}/enable", opts)
	req.SetPathParam("coupon_id", couponID)
	req.errors = errorSchemas{
		"401": errorSchema[RestErrorResponse],
		"404": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
	}
	return a.client.execute(ctx, req, nil)
}

// Unarchive a coupon
func (a *Coupons) Unarchive(ctx context.Context, couponID string, opts ...RequestOption) error {
	req := newRequest(http.MethodPost, "/api/v1/coupons/{coupon_id}/unarchive", opts)
	req.SetPathParam("coupon_id", couponID)
	req.errors = errorSchemas{
		"401": errorSchema[RestErrorResponse],
		"404": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
	}
	return a.client.execute(ctx, req, nil)
}
