// Code generated by perseid. DO NOT EDIT.

package meteroid

import (
	"encoding/json"
	"time"
)

// CouponEvent is the CouponEvent object of the Meteroid API.
type CouponEvent struct {
	Code string `json:"code"`

	CouponID CouponID `json:"coupon_id"`

	// RFC 3339 timestamp.
	CreatedAt time.Time `json:"created_at"`

	Description string `json:"description"`

	Disabled bool `json:"disabled"`

	Discount CouponDiscount `json:"discount"`

	// RFC 3339 timestamp.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`

	RecurringValue *int32 `json:"recurring_value,omitempty"`

	RedemptionLimit *int32 `json:"redemption_limit,omitempty"`

	Reusable bool `json:"reusable"`

	ID EventID `json:"id"`

	// RFC 3339 timestamp.
	Timestamp time.Time `json:"timestamp"`

	Type EventType `json:"type"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *CouponEvent) UnmarshalJSON(data []byte) error {
	type plain CouponEvent
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "CouponEvent", "code", "coupon_id", "created_at", "description", "disabled", "discount", "reusable", "id", "timestamp", "type")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "code", "coupon_id", "created_at", "description", "disabled", "discount", "expires_at", "recurring_value", "redemption_limit", "reusable", "id", "timestamp", "type")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v CouponEvent) MarshalJSON() ([]byte, error) {
	type plain CouponEvent
	return marshalWithExtra(plain(v), v.ExtraFields)
}
