// Code generated by perseid. DO NOT EDIT.

package meteroid_test

import (
	"testing"

	"github.com/meteroid-oss/meteroid-go"
)

func TestCoupons_List(t *testing.T) {
	client, requests := mock(200, "application/json", `{"data":[{"code":"sample","created_at":"2024-03-15T10:30:45.123+02:00","disabled":false,"discount":{"type":"PERCENTAGE","percentage":"sample"},"id":"coupon_id_25","plan_ids":["plan_id_47"],"redemption_count":-2147483648,"reusable":false}],"pagination_meta":{"page":-123456789,"per_page":-123456789,"total_items":-9007199254740993,"total_pages":123456789}}`)
	call(t, client.Coupons().List, nil)
	expect(t, requests, "GET /api/v1/coupons")
}

func TestCoupons_Create(t *testing.T) {
	client, requests := mock(200, "application/json", `{"code":"sample","created_at":"2023-12-31T23:59:59.999-05:30","disabled":false,"discount":{"type":"PERCENTAGE","percentage":"sample"},"id":"coupon_id_40","plan_ids":["plan_id_99"],"redemption_count":-123456789,"reusable":false}`)
	call(t, client.Coupons().Create, decode[meteroid.CreateCouponRequest](t, `{"code":"sample","discount":{"type":"PERCENTAGE","percentage":"sample"}}`))
	expect(t, requests, "POST /api/v1/coupons")
}

func TestCoupons_Retrieve(t *testing.T) {
	client, requests := mock(200, "application/json", `{"code":"sample","created_at":"2023-12-31T23:59:59.999-05:30","disabled":false,"discount":{"type":"PERCENTAGE","percentage":"sample"},"id":"coupon_id_40","plan_ids":["plan_id_99"],"redemption_count":-123456789,"reusable":false}`)
	call(t, client.Coupons().Retrieve, "coupon_id")
	expect(t, requests, "GET /api/v1/coupons/coupon_id")
}

func TestCoupons_Update(t *testing.T) {
	client, requests := mock(200, "application/json", `{"code":"sample","created_at":"2023-12-31T23:59:59.999-05:30","disabled":false,"discount":{"type":"PERCENTAGE","percentage":"sample"},"id":"coupon_id_40","plan_ids":["plan_id_99"],"redemption_count":-123456789,"reusable":false}`)
	call(t, client.Coupons().Update, "coupon_id", decode[meteroid.UpdateCouponRequest](t, `{}`))
	expect(t, requests, "PATCH /api/v1/coupons/coupon_id")
}

func TestCoupons_Archive(t *testing.T) {
	client, requests := mock(204, "", ``)
	call(t, client.Coupons().Archive, "coupon_id")
	expect(t, requests, "POST /api/v1/coupons/coupon_id/archive")
}

func TestCoupons_Disable(t *testing.T) {
	client, requests := mock(204, "", ``)
	call(t, client.Coupons().Disable, "coupon_id")
	expect(t, requests, "POST /api/v1/coupons/coupon_id/disable")
}

func TestCoupons_Enable(t *testing.T) {
	client, requests := mock(204, "", ``)
	call(t, client.Coupons().Enable, "coupon_id")
	expect(t, requests, "POST /api/v1/coupons/coupon_id/enable")
}

func TestCoupons_Unarchive(t *testing.T) {
	client, requests := mock(204, "", ``)
	call(t, client.Coupons().Unarchive, "coupon_id")
	expect(t, requests, "POST /api/v1/coupons/coupon_id/unarchive")
}
