// Code generated by perseid. DO NOT EDIT.

package meteroid

import (
	"encoding/json"
	"time"
)

// Coupon is the Coupon object of the Meteroid API.
type Coupon struct {
	// RFC 3339 timestamp.
	ArchivedAt *time.Time `json:"archived_at,omitempty"`

	Code string `json:"code"`

	// RFC 3339 timestamp.
	CreatedAt time.Time `json:"created_at"`

	Description *string `json:"description,omitempty"`

	Disabled bool `json:"disabled"`

	Discount CouponDiscount `json:"discount"`

	// RFC 3339 timestamp.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`

	ID CouponID `json:"id"`

	PlanIDs RequiredSlice[PlanID] `json:"plan_ids"`

	RecurringValue *int32 `json:"recurring_value,omitempty"`

	RedemptionCount int32 `json:"redemption_count"`

	RedemptionLimit *int32 `json:"redemption_limit,omitempty"`

	Reusable bool `json:"reusable"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *Coupon) UnmarshalJSON(data []byte) error {
	type plain Coupon
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "Coupon", "code", "created_at", "disabled", "discount", "id", "plan_ids", "redemption_count", "reusable")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "archived_at", "code", "created_at", "description", "disabled", "discount", "expires_at", "id", "plan_ids", "recurring_value", "redemption_count", "redemption_limit", "reusable")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v Coupon) MarshalJSON() ([]byte, error) {
	type plain Coupon
	return marshalWithExtra(plain(v), v.ExtraFields)
}
