// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// CreateAddOnRequest is the CreateAddOnRequest object of the Meteroid API.
type CreateAddOnRequest struct {
	Description *string `json:"description,omitempty"`

	MaxInstancesPerSubscription *int32 `json:"max_instances_per_subscription,omitempty"`

	Name string `json:"name"`

	PriceID PriceID `json:"price_id"`

	ProductID ProductID `json:"product_id"`

	SelfServiceable *bool `json:"self_serviceable,omitempty"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *CreateAddOnRequest) UnmarshalJSON(data []byte) error {
	type plain CreateAddOnRequest
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "CreateAddOnRequest", "name", "price_id", "product_id")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "description", "max_instances_per_subscription", "name", "price_id", "product_id", "self_serviceable")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v CreateAddOnRequest) MarshalJSON() ([]byte, error) {
	type plain CreateAddOnRequest
	return marshalWithExtra(plain(v), v.ExtraFields)
}
