// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// CreateWebhookEndpointRequest is the CreateWebhookEndpointRequest object of the Meteroid API.
type CreateWebhookEndpointRequest struct {
	Description *string `json:"description,omitempty"`

	// Event types to subscribe to. Omit or leave empty to receive every event type.
	EventTypes []string `json:"event_types,omitempty"`

	// Custom headers sent with every delivery.
	Headers []WebhookHeaderInput `json:"headers,omitempty"`

	// Deliveries started per second, at most (1 to 1000).
	RateLimitPerSec *int32 `json:"rate_limit_per_sec,omitempty"`

	// HTTPS destination. Private and loopback addresses are rejected unless the
	// instance is configured to allow them.
	URL string `json:"url"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *CreateWebhookEndpointRequest) UnmarshalJSON(data []byte) error {
	type plain CreateWebhookEndpointRequest
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "CreateWebhookEndpointRequest", "url")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "description", "event_types", "headers", "rate_limit_per_sec", "url")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v CreateWebhookEndpointRequest) MarshalJSON() ([]byte, error) {
	type plain CreateWebhookEndpointRequest
	return marshalWithExtra(plain(v), v.ExtraFields)
}
