// Code generated by perseid. DO NOT EDIT.

package meteroid

import (
	"encoding/json"
	"time"
)

// CreateCouponRequest is the CreateCouponRequest object of the Meteroid API.
type CreateCouponRequest struct {
	Code string `json:"code"`

	Description *string `json:"description,omitempty"`

	Discount CouponDiscount `json:"discount"`

	// RFC 3339 timestamp.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`

	PlanIDs []PlanID `json:"plan_ids,omitempty"`

	RecurringValue *int32 `json:"recurring_value,omitempty"`

	RedemptionLimit *int32 `json:"redemption_limit,omitempty"`

	Reusable *bool `json:"reusable,omitempty"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *CreateCouponRequest) UnmarshalJSON(data []byte) error {
	type plain CreateCouponRequest
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "CreateCouponRequest", "code", "discount")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "code", "description", "discount", "expires_at", "plan_ids", "recurring_value", "redemption_limit", "reusable")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v CreateCouponRequest) MarshalJSON() ([]byte, error) {
	type plain CreateCouponRequest
	return marshalWithExtra(plain(v), v.ExtraFields)
}
