// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// CreateProductRequest is the CreateProductRequest object of the Meteroid API.
type CreateProductRequest struct {
	Catalog *bool `json:"catalog,omitempty"`

	Description *string `json:"description,omitempty"`

	FeeStructure ProductFeeStructure `json:"fee_structure"`

	Name string `json:"name"`

	ProductFamilyID ProductFamilyID `json:"product_family_id"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *CreateProductRequest) UnmarshalJSON(data []byte) error {
	type plain CreateProductRequest
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "catalog", "description", "fee_structure", "name", "product_family_id")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v CreateProductRequest) MarshalJSON() ([]byte, error) {
	type plain CreateProductRequest
	return marshalWithExtra(plain(v), v.ExtraFields)
}
