// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// CreateSubscriptionAddOn is the CreateSubscriptionAddOn object of the Meteroid API.
type CreateSubscriptionAddOn struct {
	AddOnID AddOnID `json:"add_on_id"`

	Customization *SubscriptionAddOnCustomization `json:"customization,omitempty"`

	Quantity *int32 `json:"quantity,omitempty"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *CreateSubscriptionAddOn) UnmarshalJSON(data []byte) error {
	type plain CreateSubscriptionAddOn
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "add_on_id", "customization", "quantity")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v CreateSubscriptionAddOn) MarshalJSON() ([]byte, error) {
	type plain CreateSubscriptionAddOn
	return marshalWithExtra(plain(v), v.ExtraFields)
}
