// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// CreateSubscriptionComponents is the CreateSubscriptionComponents object of the Meteroid API.
type CreateSubscriptionComponents struct {
	ExtraComponents []ExtraComponent `json:"extra_components,omitempty"`

	OverriddenComponents []ComponentOverride `json:"overridden_components,omitempty"`

	ParameterizedComponents []ComponentParameterization `json:"parameterized_components,omitempty"`

	RemoveComponents []PriceComponentID `json:"remove_components,omitempty"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *CreateSubscriptionComponents) UnmarshalJSON(data []byte) error {
	type plain CreateSubscriptionComponents
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "CreateSubscriptionComponents")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "extra_components", "overridden_components", "parameterized_components", "remove_components")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v CreateSubscriptionComponents) MarshalJSON() ([]byte, error) {
	type plain CreateSubscriptionComponents
	return marshalWithExtra(plain(v), v.ExtraFields)
}
