// Code generated by perseid. DO NOT EDIT.

package meteroid

import (
	"encoding/json"

	"github.com/google/uuid"
)

// CreateConnectedAccountRequest is the CreateConnectedAccountRequest object of the Meteroid API.
type CreateConnectedAccountRequest struct {
	ConnectedOrganizationID uuid.UUID `json:"connected_organization_id"`

	ConnectionType *ConnectionType `json:"connection_type,omitempty"`

	Metadata json.RawMessage `json:"metadata,omitempty"`

	PlatformCustomerID *CustomerID `json:"platform_customer_id,omitempty"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *CreateConnectedAccountRequest) UnmarshalJSON(data []byte) error {
	type plain CreateConnectedAccountRequest
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "connected_organization_id", "connection_type", "metadata", "platform_customer_id")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v CreateConnectedAccountRequest) MarshalJSON() ([]byte, error) {
	type plain CreateConnectedAccountRequest
	return marshalWithExtra(plain(v), v.ExtraFields)
}
