// Code generated by perseid. DO NOT EDIT.

package meteroid

import (
	"encoding/json"
	"time"
)

// CreditNoteEventData is the CreditNoteEventData object of the Meteroid API.
type CreditNoteEventData struct {
	// RFC 3339 timestamp.
	CreatedAt time.Time `json:"created_at"`

	CreditNoteID CreditNoteID `json:"credit_note_id"`

	// Absent while the credit note is a draft — the number is assigned at finalization.
	CreditNoteNumber *string `json:"credit_note_number,omitempty"`

	CreditedAmountCents int64 `json:"credited_amount_cents"`

	Currency string `json:"currency"`

	// User-defined custom property values, keyed by definition key.
	CustomProperties json.RawMessage `json:"custom_properties"`

	CustomerID CustomerID `json:"customer_id"`

	InvoiceID InvoiceID `json:"invoice_id"`

	// Number of the invoice being credited.
	InvoiceNumber *string `json:"invoice_number,omitempty"`

	// Credited line items (negated amounts).
	LineItems RequiredSlice[InvoiceLineItem] `json:"line_items"`

	Memo *string `json:"memo,omitempty"`

	Reason *string `json:"reason,omitempty"`

	RefundedAmountCents int64 `json:"refunded_amount_cents"`

	Status CreditNoteStatus `json:"status"`

	Subtotal int64 `json:"subtotal"`

	TaxAmount int64 `json:"tax_amount"`

	// Per-rate tax (VAT) breakdown for the credited amount.
	TaxBreakdown RequiredSlice[TaxBreakdownItem] `json:"tax_breakdown"`

	Total int64 `json:"total"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *CreditNoteEventData) UnmarshalJSON(data []byte) error {
	type plain CreditNoteEventData
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "created_at", "credit_note_id", "credit_note_number", "credited_amount_cents", "currency", "custom_properties", "customer_id", "invoice_id", "invoice_number", "line_items", "memo", "reason", "refunded_amount_cents", "status", "subtotal", "tax_amount", "tax_breakdown", "total")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v CreditNoteEventData) MarshalJSON() ([]byte, error) {
	type plain CreditNoteEventData
	return marshalWithExtra(plain(v), v.ExtraFields)
}
