// Code generated by perseid. DO NOT EDIT.

package meteroid_test

import (
	"testing"

	"github.com/meteroid-oss/meteroid-go"
)

func TestCreditNotes_List(t *testing.T) {
	client, requests := mock(200, "application/json", `{"data":[{"created_at":"2023-12-31T23:59:59.999-05:30","credit_note_number":"sample","credit_type":"DEBT_CANCELLATION","credited_amount_cents":9007199254740993,"currency":"TMT","custom_properties":{"key":"value","count":3,"ratio":0.5,"flags":[true,false],"nested":{"ok":true}},"customer_id":"customer_id_78","id":"credit_note_id_47","invoice_id":"invoice_id_67","invoice_number":"sample","line_items":[{"amount_total":-9007199254740993,"end_date":"2024-02-29","name":"sample","start_date":"2024-02-29","sub_line_items":[{"id":"sample","name":"sample","quantity":"12345.6789","total":9007199254740993,"unit_price":"12345.6789"}],"tax_rate":"12345.6789"}],"refunded_amount_cents":9007199254740993,"status":"DRAFT","subtotal":-9007199254740993,"tax_amount":9007199254740993,"tax_breakdown":[{"name":"sample","tax_amount":-9007199254740993,"tax_rate":"-0.000123","taxable_amount":-9007199254740993}],"total":-9007199254740993}],"pagination_meta":{"page":-123456789,"per_page":-123456789,"total_items":-9007199254740993,"total_pages":123456789}}`)
	call(t, client.CreditNotes().List, nil)
	expect(t, requests, "GET /api/v1/credit-notes")
}

func TestCreditNotes_Retrieve(t *testing.T) {
	client, requests := mock(200, "application/json", `{"created_at":"2023-12-31T23:59:59.999-05:30","credit_note_number":"sample","credit_type":"REFUND","credited_amount_cents":9007199254740993,"currency":"MMK","custom_properties":{"key":"value","count":3,"ratio":0.5,"flags":[true,false],"nested":{"ok":true}},"customer_id":"customer_id_13","id":"credit_note_id_99","invoice_id":"invoice_id_90","invoice_number":"sample","line_items":[{"amount_total":-9007199254740993,"end_date":"2024-02-29","name":"sample","start_date":"1999-12-31","sub_line_items":[{"id":"sample","name":"sample","quantity":"12345.6789","total":9007199254740993,"unit_price":"-0.000123"}],"tax_rate":"12345.6789"}],"refunded_amount_cents":-9007199254740993,"status":"DRAFT","subtotal":9007199254740993,"tax_amount":9007199254740993,"tax_breakdown":[{"name":"sample","tax_amount":9007199254740993,"tax_rate":"12345.6789","taxable_amount":9007199254740993}],"total":-9007199254740993}`)
	call(t, client.CreditNotes().Retrieve, "credit_note_id")
	expect(t, requests, "GET /api/v1/credit-notes/credit_note_id")
}

func TestCreditNotes_UpdateCustomProperties(t *testing.T) {
	client, requests := mock(200, "application/json", `{"created_at":"2023-12-31T23:59:59.999-05:30","credit_note_number":"sample","credit_type":"REFUND","credited_amount_cents":9007199254740993,"currency":"MMK","custom_properties":{"key":"value","count":3,"ratio":0.5,"flags":[true,false],"nested":{"ok":true}},"customer_id":"customer_id_13","id":"credit_note_id_99","invoice_id":"invoice_id_90","invoice_number":"sample","line_items":[{"amount_total":-9007199254740993,"end_date":"2024-02-29","name":"sample","start_date":"1999-12-31","sub_line_items":[{"id":"sample","name":"sample","quantity":"12345.6789","total":9007199254740993,"unit_price":"-0.000123"}],"tax_rate":"12345.6789"}],"refunded_amount_cents":-9007199254740993,"status":"DRAFT","subtotal":9007199254740993,"tax_amount":9007199254740993,"tax_breakdown":[{"name":"sample","tax_amount":9007199254740993,"tax_rate":"12345.6789","taxable_amount":9007199254740993}],"total":-9007199254740993}`)
	call(t, client.CreditNotes().UpdateCustomProperties, "credit_note_id", decode[meteroid.CreditNoteCustomPropertiesRequest](t, `{"custom_properties":{"key":"value","count":3,"ratio":0.5,"flags":[true,false],"nested":{"ok":true}}}`))
	expect(t, requests, "PATCH /api/v1/credit-notes/credit_note_id/custom-properties")
}

func TestCreditNotes_Download(t *testing.T) {
	client, requests := mock(200, "application/octet-stream", `sample`)
	call(t, client.CreditNotes().Download, "credit_note_id")
	expect(t, requests, "GET /api/v1/credit-notes/credit_note_id/download")
}

func TestCreditNotes_DownloadXML(t *testing.T) {
	client, requests := mock(200, "application/octet-stream", `sample`)
	call(t, client.CreditNotes().DownloadXML, "credit_note_id")
	expect(t, requests, "GET /api/v1/credit-notes/credit_note_id/xml")
}
