// Code generated by perseid. DO NOT EDIT.

package meteroid

import (
	"context"
	"net/http"
)

// CreditNotesListOptions carries the optional query and header parameters of
// [CreditNotes.List]. Leave a field nil to omit it.
type CreditNotesListOptions struct {
	// Filter by customer ID
	CustomerID *CustomerID

	// Filter by invoice ID
	InvoiceID *InvoiceID

	Status *CreditNoteStatus

	// Free-text search over credit note number.
	Search *string

	// Sort order. Format: `column.direction`. Allowed columns: `created_at`, `credit_note_number`, `total`, `status`. Direction: `asc` or `desc`. Default: `created_at.desc`.
	OrderBy *string

	// Page number (0-indexed)
	Page *int32

	// Number of items per page
	PerPage *int32
}

// CreditNotes groups the credit notes operations of the Meteroid API.
type CreditNotes struct {
	client *Client
}

// List credit notes
//
// List a tenant's credit notes, optionally filtered by customer, invoice or status.
func (a *CreditNotes) List(ctx context.Context, options *CreditNotesListOptions, opts ...RequestOption) (*CreditNoteListResponse, error) {
	req := newRequest(http.MethodGet, "/api/v1/credit-notes", opts)
	req.errors = errorSchemas{
		"401": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
		"500": errorSchema[RestErrorResponse],
	}
	if options != nil && options.CustomerID != nil {
		req.SetQueryParam("customer_id", formatValue(*options.CustomerID))
	}
	if options != nil && options.InvoiceID != nil {
		req.SetQueryParam("invoice_id", formatValue(*options.InvoiceID))
	}
	if options != nil && options.Status != nil {
		req.SetQueryParam("status", formatValue(*options.Status))
	}
	if options != nil && options.Search != nil {
		req.SetQueryParam("search", *options.Search)
	}
	if options != nil && options.OrderBy != nil {
		req.SetQueryParam("order_by", *options.OrderBy)
	}
	if options != nil && options.Page != nil {
		req.SetQueryParam("page", formatInt(int64(*options.Page)))
	}
	if options != nil && options.PerPage != nil {
		req.SetQueryParam("per_page", formatInt(int64(*options.PerPage)))
	}
	var out CreditNoteListResponse
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Retrieve sends GET /api/v1/credit-notes/{credit_note_id}.
//
// # Get credit note
//
// Retrieve a single credit note by ID.
func (a *CreditNotes) Retrieve(ctx context.Context, creditNoteID string, opts ...RequestOption) (*CreditNote, error) {
	req := newRequest(http.MethodGet, "/api/v1/credit-notes/{credit_note_id}", opts)
	req.SetPathParam("credit_note_id", creditNoteID)
	req.errors = errorSchemas{
		"401": errorSchema[RestErrorResponse],
		"404": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
		"500": errorSchema[RestErrorResponse],
	}
	var out CreditNote
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateCustomProperties sends PATCH /api/v1/credit-notes/{credit_note_id}/custom-properties.
//
// # Update credit note custom properties
//
// Merge custom property values onto a credit note (send a key with `null` to remove it).
// Values are validated against the tenant's `CREDIT_NOTE` property definitions. Allowed at any
// status — custom properties are external workflow metadata and stay editable after the credit
// note is finalized.
func (a *CreditNotes) UpdateCustomProperties(ctx context.Context, creditNoteID string, creditNoteCustomPropertiesRequest CreditNoteCustomPropertiesRequest, opts ...RequestOption) (*CreditNote, error) {
	req := newRequest(http.MethodPatch, "/api/v1/credit-notes/{credit_note_id}/custom-properties", opts)
	req.SetPathParam("credit_note_id", creditNoteID)
	req.errors = errorSchemas{
		"400": errorSchema[RestErrorResponse],
		"401": errorSchema[RestErrorResponse],
		"404": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
		"500": errorSchema[RestErrorResponse],
	}
	req.SetJSONBody(creditNoteCustomPropertiesRequest)
	var out CreditNote
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Download sends GET /api/v1/credit-notes/{credit_note_id}/download.
func (a *CreditNotes) Download(ctx context.Context, creditNoteID string, opts ...RequestOption) ([]byte, error) {
	req := newRequest(http.MethodGet, "/api/v1/credit-notes/{credit_note_id}/download", opts)
	req.SetPathParam("credit_note_id", creditNoteID)
	req.errors = errorSchemas{
		"401": errorSchema[RestErrorResponse],
		"404": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
		"500": errorSchema[RestErrorResponse],
	}
	return a.client.executeBinary(ctx, req)
}

// DownloadXML sends GET /api/v1/credit-notes/{credit_note_id}/xml.
//
// # Download credit note e-invoice XML
//
// Download the structured e-invoice (EN 16931 XML) issued with a credit note. For
// Factur-X the same XML is also embedded in the PDF.
func (a *CreditNotes) DownloadXML(ctx context.Context, creditNoteID string, opts ...RequestOption) ([]byte, error) {
	req := newRequest(http.MethodGet, "/api/v1/credit-notes/{credit_note_id}/xml", opts)
	req.SetPathParam("credit_note_id", creditNoteID)
	req.errors = errorSchemas{
		"401": errorSchema[RestErrorResponse],
		"404": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
		"500": errorSchema[RestErrorResponse],
	}
	return a.client.executeBinary(ctx, req)
}
