// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// CustomTaxRate is the CustomTaxRate object of the Meteroid API.
type CustomTaxRate struct {
	Name string `json:"name"`

	Rate string `json:"rate"`

	TaxCode string `json:"tax_code"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *CustomTaxRate) UnmarshalJSON(data []byte) error {
	type plain CustomTaxRate
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "name", "rate", "tax_code")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v CustomTaxRate) MarshalJSON() ([]byte, error) {
	type plain CustomTaxRate
	return marshalWithExtra(plain(v), v.ExtraFields)
}
