// Code generated by perseid. DO NOT EDIT.

package meteroid

import (
	"context"
	"encoding/json"
	"net/http"
)

// CustomersListOptions carries the optional query and header parameters of
// [Customers.List]. Leave a field nil to omit it.
type CustomersListOptions struct {
	// Sort order. Format: `column.direction`. Allowed columns: `name`, `email`, `alias`, `created_at`. Direction: `asc` or `desc`. Default: `created_at.desc`.
	OrderBy *string

	// Page number (0-indexed)
	Page *int32

	// Number of items per page
	PerPage *int32

	Search *string

	Archived *bool
}

// Customers groups the customers operations of the Meteroid API.
type Customers struct {
	client *Client
}

// fetchList sends GET /api/v1/customers and decodes the response, for [Customers.List].
func (a *Customers) fetchList(ctx context.Context, options *CustomersListOptions, opts ...RequestOption) (*CustomerListResponse, error) {
	req := newRequest(http.MethodGet, "/api/v1/customers", opts)
	req.errors = errorSchemas{
		"401": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
		"500": errorSchema[RestErrorResponse],
	}
	if options != nil && options.OrderBy != nil {
		req.SetQueryParam("order_by", *options.OrderBy)
	}
	if options != nil && options.Page != nil {
		req.SetQueryParam("page", formatInt(int64(*options.Page)))
	}
	if options != nil && options.PerPage != nil {
		req.SetQueryParam("per_page", formatInt(int64(*options.PerPage)))
	}
	if options != nil && options.Search != nil {
		req.SetQueryParam("search", *options.Search)
	}
	if options != nil && options.Archived != nil {
		req.SetQueryParam("archived", formatBool(*options.Archived))
	}
	var out CustomerListResponse
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// CustomersListPage is a page of [Customers.List]. It embeds the
// decoded [CustomerListResponse], promoting its fields, with the Items of the page; a field
// named like a page member stays reachable through the embedded CustomerListResponse.
type CustomersListPage struct {
	CustomerListResponse

	// Items holds the items of this page.
	Items []Customer

	next func(ctx context.Context) (*CustomersListPage, error)
}

// HasNextPage reports whether another page follows this one.
func (p *CustomersListPage) HasNextPage() bool {
	return p != nil && p.next != nil
}

// NextPage fetches the page after this one. It returns nil and no error after
// the last page.
func (p *CustomersListPage) NextPage(ctx context.Context) (*CustomersListPage, error) {
	if !p.HasNextPage() {
		return nil, nil
	}
	return p.next(ctx)
}

// MarshalJSON encodes the CustomerListResponse of the page, as received.
func (p CustomersListPage) MarshalJSON() ([]byte, error) {
	return json.Marshal(&p.CustomerListResponse)
}

func (p *CustomersListPage) pageItems() []Customer { return p.Items }

// List customers with optional pagination and search filtering.
//
// [Customers.ListAutoPaging] iterates over every item instead.
func (a *Customers) List(ctx context.Context, options *CustomersListOptions, opts ...RequestOption) (*CustomersListPage, error) {
	var params CustomersListOptions
	if options != nil {
		params = *options
	}
	resp, err := a.fetchList(ctx, &params, opts...)
	if err != nil {
		return nil, err
	}
	page := &CustomersListPage{CustomerListResponse: *resp, Items: resp.Data}
	if len(page.Items) == 0 {
		return page, nil
	}
	current := int32(0)
	if params.Page != nil {
		current = *params.Page
	}
	if reached(current+1, resp.PaginationMeta.TotalPages) {
		return page, nil
	}
	next := current + 1
	params.Page = &next
	page.next = func(ctx context.Context) (*CustomersListPage, error) {
		return a.List(ctx, &params, opts...)
	}
	return page, nil
}

// ListAutoPaging iterates over every item of [Customers.List], fetching
// further pages on demand.
func (a *Customers) ListAutoPaging(ctx context.Context, options *CustomersListOptions, opts ...RequestOption) *AutoPager[Customer] {
	return newAutoPager[Customer](ctx, func(ctx context.Context) (*CustomersListPage, error) {
		return a.List(ctx, options, opts...)
	})
}

// Create customer
func (a *Customers) Create(ctx context.Context, customerCreateRequest CustomerCreateRequest, opts ...RequestOption) (*Customer, error) {
	req := newRequest(http.MethodPost, "/api/v1/customers", opts)
	req.errors = errorSchemas{
		"400": errorSchema[RestErrorResponse],
		"401": errorSchema[RestErrorResponse],
		"409": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
		"500": errorSchema[RestErrorResponse],
	}
	req.SetJSONBody(customerCreateRequest)
	var out Customer
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Retrieve sends GET /api/v1/customers/{id_or_alias}.
//
// # Get customer
//
// Retrieve a single customer by ID or alias.
func (a *Customers) Retrieve(ctx context.Context, idOrAlias string, opts ...RequestOption) (*Customer, error) {
	req := newRequest(http.MethodGet, "/api/v1/customers/{id_or_alias}", opts)
	req.SetPathParam("id_or_alias", idOrAlias)
	req.errors = errorSchemas{
		"401": errorSchema[RestErrorResponse],
		"404": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
		"500": errorSchema[RestErrorResponse],
	}
	var out Customer
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Replace sends PUT /api/v1/customers/{id_or_alias}.
//
// Update customer
func (a *Customers) Replace(ctx context.Context, idOrAlias string, customerUpdateRequest CustomerUpdateRequest, opts ...RequestOption) (*Customer, error) {
	req := newRequest(http.MethodPut, "/api/v1/customers/{id_or_alias}", opts)
	req.SetPathParam("id_or_alias", idOrAlias)
	req.errors = errorSchemas{
		"400": errorSchema[RestErrorResponse],
		"401": errorSchema[RestErrorResponse],
		"404": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
		"500": errorSchema[RestErrorResponse],
	}
	req.SetJSONBody(customerUpdateRequest)
	var out Customer
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Archive a customer
//
// No linked entity will be deleted. You need to terminate all active subscriptions before archiving a customer, or the call will fail.
func (a *Customers) Archive(ctx context.Context, idOrAlias string, opts ...RequestOption) error {
	req := newRequest(http.MethodDelete, "/api/v1/customers/{id_or_alias}", opts)
	req.SetPathParam("id_or_alias", idOrAlias)
	req.errors = errorSchemas{
		"401": errorSchema[RestErrorResponse],
		"404": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
		"500": errorSchema[RestErrorResponse],
	}
	return a.client.execute(ctx, req, nil)
}

// Update sends PATCH /api/v1/customers/{id_or_alias}.
//
// # Patch customer
//
// Partially update a customer. Only provided fields will be updated.
func (a *Customers) Update(ctx context.Context, idOrAlias string, customerPatchRequest CustomerPatchRequest, opts ...RequestOption) (*Customer, error) {
	req := newRequest(http.MethodPatch, "/api/v1/customers/{id_or_alias}", opts)
	req.SetPathParam("id_or_alias", idOrAlias)
	req.errors = errorSchemas{
		"400": errorSchema[RestErrorResponse],
		"401": errorSchema[RestErrorResponse],
		"404": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
		"500": errorSchema[RestErrorResponse],
	}
	req.SetJSONBody(customerPatchRequest)
	var out Customer
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListEntitlements sends GET /api/v1/customers/{id_or_alias}/entitlements.
//
// List customer entitlements
func (a *Customers) ListEntitlements(ctx context.Context, idOrAlias string, opts ...RequestOption) (*EffectiveEntitlementListResponse, error) {
	req := newRequest(http.MethodGet, "/api/v1/customers/{id_or_alias}/entitlements", opts)
	req.SetPathParam("id_or_alias", idOrAlias)
	req.errors = errorSchemas{
		"401": errorSchema[RestErrorResponse],
		"404": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
	}
	var out EffectiveEntitlementListResponse
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// CreatePortalToken sends POST /api/v1/customers/{id_or_alias}/portal-token.
//
// # Generate a portal token for a customer
//
// Generates a JWT token that grants access to the customer portal.
// The token can be used to access invoices, payment methods, and other portal features.
func (a *Customers) CreatePortalToken(ctx context.Context, idOrAlias string, customerPortalTokenRequest CustomerPortalTokenRequest, opts ...RequestOption) (*CustomerPortalTokenResponse, error) {
	req := newRequest(http.MethodPost, "/api/v1/customers/{id_or_alias}/portal-token", opts)
	req.SetPathParam("id_or_alias", idOrAlias)
	req.errors = errorSchemas{
		"400": errorSchema[RestErrorResponse],
		"401": errorSchema[RestErrorResponse],
		"404": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
		"500": errorSchema[RestErrorResponse],
	}
	req.SetJSONBody(customerPortalTokenRequest)
	var out CustomerPortalTokenResponse
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Unarchive sends POST /api/v1/customers/{id_or_alias}/unarchive.
//
// Restore an archived customer
func (a *Customers) Unarchive(ctx context.Context, idOrAlias string, opts ...RequestOption) error {
	req := newRequest(http.MethodPost, "/api/v1/customers/{id_or_alias}/unarchive", opts)
	req.SetPathParam("id_or_alias", idOrAlias)
	req.errors = errorSchemas{
		"401": errorSchema[RestErrorResponse],
		"404": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
		"500": errorSchema[RestErrorResponse],
	}
	return a.client.execute(ctx, req, nil)
}
