// Code generated by perseid. DO NOT EDIT.

package meteroid

import (
	"context"
	"net/http"
)

// CustomPropertiesListCustomPropertyDefinitionsOptions carries the optional query and header parameters of
// [CustomProperties.ListCustomPropertyDefinitions]. Leave a field nil to omit it.
type CustomPropertiesListCustomPropertyDefinitionsOptions struct {
	// Filter to a single entity type.
	EntityType *CustomPropertyEntityType

	// Include archived (soft-deleted) definitions. Defaults to false.
	IncludeArchived *bool

	// Page number (0-indexed)
	Page *int32

	// Number of items per page
	PerPage *int32
}

// CustomProperties groups the custom properties operations of the Meteroid API.
type CustomProperties struct {
	client *Client
}

// ListCustomPropertyDefinitions sends GET /api/v1/custom-property-definitions.
//
// List custom property definitions
func (a *CustomProperties) ListCustomPropertyDefinitions(ctx context.Context, options *CustomPropertiesListCustomPropertyDefinitionsOptions, opts ...RequestOption) (*CustomPropertyDefinitionListResponse, error) {
	req := newRequest(http.MethodGet, "/api/v1/custom-property-definitions", opts)
	req.errors = errorSchemas{
		"401": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
		"500": errorSchema[RestErrorResponse],
	}
	if options != nil && options.EntityType != nil {
		req.SetQueryParam("entity_type", formatValue(*options.EntityType))
	}
	if options != nil && options.IncludeArchived != nil {
		req.SetQueryParam("include_archived", formatBool(*options.IncludeArchived))
	}
	if options != nil && options.Page != nil {
		req.SetQueryParam("page", formatInt(int64(*options.Page)))
	}
	if options != nil && options.PerPage != nil {
		req.SetQueryParam("per_page", formatInt(int64(*options.PerPage)))
	}
	var out CustomPropertyDefinitionListResponse
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateCustomPropertyDefinition sends POST /api/v1/custom-property-definitions.
//
// Create a custom property definition
func (a *CustomProperties) CreateCustomPropertyDefinition(ctx context.Context, customPropertyDefinitionCreateRequest CustomPropertyDefinitionCreateRequest, opts ...RequestOption) (*CustomPropertyDefinition, error) {
	req := newRequest(http.MethodPost, "/api/v1/custom-property-definitions", opts)
	req.errors = errorSchemas{
		"400": errorSchema[RestErrorResponse],
		"409": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
		"500": errorSchema[RestErrorResponse],
	}
	req.SetJSONBody(customPropertyDefinitionCreateRequest)
	var out CustomPropertyDefinition
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// RetrieveCustomPropertyDefinition sends GET /api/v1/custom-property-definitions/{id}.
//
// Get a custom property definition
func (a *CustomProperties) RetrieveCustomPropertyDefinition(ctx context.Context, id string, opts ...RequestOption) (*CustomPropertyDefinition, error) {
	req := newRequest(http.MethodGet, "/api/v1/custom-property-definitions/{id}", opts)
	req.SetPathParam("id", id)
	req.errors = errorSchemas{
		"404": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
		"500": errorSchema[RestErrorResponse],
	}
	var out CustomPropertyDefinition
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateCustomPropertyDefinition sends PUT /api/v1/custom-property-definitions/{id}.
//
// Update a custom property definition
func (a *CustomProperties) UpdateCustomPropertyDefinition(ctx context.Context, id string, customPropertyDefinitionUpdateRequest CustomPropertyDefinitionUpdateRequest, opts ...RequestOption) (*CustomPropertyDefinition, error) {
	req := newRequest(http.MethodPut, "/api/v1/custom-property-definitions/{id}", opts)
	req.SetPathParam("id", id)
	req.errors = errorSchemas{
		"404": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
		"500": errorSchema[RestErrorResponse],
	}
	req.SetJSONBody(customPropertyDefinitionUpdateRequest)
	var out CustomPropertyDefinition
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// ArchiveDefinition sends DELETE /api/v1/custom-property-definitions/{id}.
//
// # Archive a custom property definition
//
// Soft-deletes the definition. Existing property values on entities are preserved; the definition
// simply stops being enforced on new writes.
func (a *CustomProperties) ArchiveDefinition(ctx context.Context, id string, opts ...RequestOption) (*CustomPropertyDefinition, error) {
	req := newRequest(http.MethodDelete, "/api/v1/custom-property-definitions/{id}", opts)
	req.SetPathParam("id", id)
	req.errors = errorSchemas{
		"404": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
		"500": errorSchema[RestErrorResponse],
	}
	var out CustomPropertyDefinition
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
