// Code generated by perseid. DO NOT EDIT.

package meteroid_test

import (
	"testing"

	"github.com/meteroid-oss/meteroid-go"
)

func TestCustomProperties_ListCustomPropertyDefinitions(t *testing.T) {
	client, requests := mock(200, "application/json", `{"data":[{"archived":false,"config":{},"display_order":-2147483648,"entity_type":"CUSTOMER","id":"custom_property_definition_id_78","key":"sample","name":"sample","property_type":"JSON","required":false}],"pagination_meta":{"page":-123456789,"per_page":-123456789,"total_items":-9007199254740993,"total_pages":123456789}}`)
	call(t, client.CustomProperties().ListCustomPropertyDefinitions, nil)
	expect(t, requests, "GET /api/v1/custom-property-definitions")
}

func TestCustomProperties_CreateCustomPropertyDefinition(t *testing.T) {
	client, requests := mock(200, "application/json", `{"archived":false,"config":{},"display_order":-2147483648,"entity_type":"CUSTOMER","id":"custom_property_definition_id_13","key":"sample","name":"sample","property_type":"TEXT","required":false}`)
	call(t, client.CustomProperties().CreateCustomPropertyDefinition, decode[meteroid.CustomPropertyDefinitionCreateRequest](t, `{"entity_type":"INVOICE","key":"sample","name":"sample","property_type":"TEXT"}`))
	expect(t, requests, "POST /api/v1/custom-property-definitions")
}

func TestCustomProperties_RetrieveCustomPropertyDefinition(t *testing.T) {
	client, requests := mock(200, "application/json", `{"archived":false,"config":{},"display_order":-2147483648,"entity_type":"CUSTOMER","id":"custom_property_definition_id_13","key":"sample","name":"sample","property_type":"TEXT","required":false}`)
	call(t, client.CustomProperties().RetrieveCustomPropertyDefinition, "id")
	expect(t, requests, "GET /api/v1/custom-property-definitions/id")
}

func TestCustomProperties_UpdateCustomPropertyDefinition(t *testing.T) {
	client, requests := mock(200, "application/json", `{"archived":false,"config":{},"display_order":-2147483648,"entity_type":"CUSTOMER","id":"custom_property_definition_id_13","key":"sample","name":"sample","property_type":"TEXT","required":false}`)
	call(t, client.CustomProperties().UpdateCustomPropertyDefinition, "id", decode[meteroid.CustomPropertyDefinitionUpdateRequest](t, `{}`))
	expect(t, requests, "PUT /api/v1/custom-property-definitions/id")
}

func TestCustomProperties_ArchiveDefinition(t *testing.T) {
	client, requests := mock(200, "application/json", `{"archived":false,"config":{},"display_order":-2147483648,"entity_type":"CUSTOMER","id":"custom_property_definition_id_13","key":"sample","name":"sample","property_type":"TEXT","required":false}`)
	call(t, client.CustomProperties().ArchiveDefinition, "id")
	expect(t, requests, "DELETE /api/v1/custom-property-definitions/id")
}
