// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// CustomerPortalTokenRequest is the CustomerPortalTokenRequest object of the Meteroid API.
type CustomerPortalTokenRequest struct {
	// Token lifetime in seconds. Defaults to 86400 (24 hours).
	// Must be between 60 and 2592000 (30 days).
	ExpiresInSeconds *int32 `json:"expires_in_seconds,omitempty"`

	// Scopes granted to the token. Defaults to `["read", "manage"]`.
	// Use `["read"]` for tokens that only read billing state, e.g. to gate features in a browser.
	Scopes []CustomerPortalScope `json:"scopes,omitempty"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *CustomerPortalTokenRequest) UnmarshalJSON(data []byte) error {
	type plain CustomerPortalTokenRequest
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "expires_in_seconds", "scopes")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v CustomerPortalTokenRequest) MarshalJSON() ([]byte, error) {
	type plain CustomerPortalTokenRequest
	return marshalWithExtra(plain(v), v.ExtraFields)
}
