// Code generated by perseid. DO NOT EDIT.

package meteroid_test

import (
	"testing"

	"github.com/meteroid-oss/meteroid-go"
)

func TestCustomers_List(t *testing.T) {
	client, requests := mock(200, "application/json", `{"data":[{"currency":"BHD","custom_properties":{"key":"value","count":3,"ratio":0.5,"flags":[true,false],"nested":{"ok":true}},"custom_taxes":[{"name":"sample","rate":"sample","tax_code":"sample"}],"id":"customer_id_39","invoicing_emails":["sample"],"invoicing_entity_id":"invoicing_entity_id_23","name":"sample","preferred_locales":["sample"]}],"pagination_meta":{"page":-123456789,"per_page":-123456789,"total_items":-9007199254740993,"total_pages":123456789}}`)
	call(t, client.Customers().List, nil)
	expect(t, requests, "GET /api/v1/customers")
}

func TestCustomers_Create(t *testing.T) {
	client, requests := mock(200, "application/json", `{"currency":"ERN","custom_properties":{"key":"value","count":3,"ratio":0.5,"flags":[true,false],"nested":{"ok":true}},"custom_taxes":[{"name":"sample","rate":"sample","tax_code":"sample"}],"id":"customer_id_1","invoicing_emails":["sample"],"invoicing_entity_id":"invoicing_entity_id_83","name":"sample","preferred_locales":["sample"]}`)
	call(t, client.Customers().Create, decode[meteroid.CustomerCreateRequest](t, `{"currency":"ERN"}`))
	expect(t, requests, "POST /api/v1/customers")
}

func TestCustomers_Retrieve(t *testing.T) {
	client, requests := mock(200, "application/json", `{"currency":"ERN","custom_properties":{"key":"value","count":3,"ratio":0.5,"flags":[true,false],"nested":{"ok":true}},"custom_taxes":[{"name":"sample","rate":"sample","tax_code":"sample"}],"id":"customer_id_1","invoicing_emails":["sample"],"invoicing_entity_id":"invoicing_entity_id_83","name":"sample","preferred_locales":["sample"]}`)
	call(t, client.Customers().Retrieve, "id_or_alias")
	expect(t, requests, "GET /api/v1/customers/id_or_alias")
}

func TestCustomers_Replace(t *testing.T) {
	client, requests := mock(200, "application/json", `{"currency":"ERN","custom_properties":{"key":"value","count":3,"ratio":0.5,"flags":[true,false],"nested":{"ok":true}},"custom_taxes":[{"name":"sample","rate":"sample","tax_code":"sample"}],"id":"customer_id_1","invoicing_emails":["sample"],"invoicing_entity_id":"invoicing_entity_id_83","name":"sample","preferred_locales":["sample"]}`)
	call(t, client.Customers().Replace, "id_or_alias", decode[meteroid.CustomerUpdateRequest](t, `{"currency":"MMK","custom_taxes":[{"name":"sample","rate":"sample","tax_code":"sample"}],"invoicing_emails":["sample"],"invoicing_entity_id":"invoicing_entity_id_26"}`))
	expect(t, requests, "PUT /api/v1/customers/id_or_alias")
}

func TestCustomers_Archive(t *testing.T) {
	client, requests := mock(204, "", ``)
	call(t, client.Customers().Archive, "id_or_alias")
	expect(t, requests, "DELETE /api/v1/customers/id_or_alias")
}

func TestCustomers_Update(t *testing.T) {
	client, requests := mock(200, "application/json", `{"currency":"ERN","custom_properties":{"key":"value","count":3,"ratio":0.5,"flags":[true,false],"nested":{"ok":true}},"custom_taxes":[{"name":"sample","rate":"sample","tax_code":"sample"}],"id":"customer_id_1","invoicing_emails":["sample"],"invoicing_entity_id":"invoicing_entity_id_83","name":"sample","preferred_locales":["sample"]}`)
	call(t, client.Customers().Update, "id_or_alias", decode[meteroid.CustomerPatchRequest](t, `{}`))
	expect(t, requests, "PATCH /api/v1/customers/id_or_alias")
}

func TestCustomers_ListEntitlements(t *testing.T) {
	client, requests := mock(200, "application/json", `{"data":[{"feature":{"code":"sample","id":"feature_id_53","name":"sample"},"value":{"type":"BOOLEAN","enabled":false}}]}`)
	call(t, client.Customers().ListEntitlements, "id_or_alias")
	expect(t, requests, "GET /api/v1/customers/id_or_alias/entitlements")
}

func TestCustomers_CreatePortalToken(t *testing.T) {
	client, requests := mock(200, "application/json", `{"api_url":"sample","expires_at":"2024-03-15T10:30:45.123+02:00","portal_link":"sample","portal_url":"sample","token":"sample"}`)
	call(t, client.Customers().CreatePortalToken, "id_or_alias", decode[meteroid.CustomerPortalTokenRequest](t, `{}`))
	expect(t, requests, "POST /api/v1/customers/id_or_alias/portal-token")
}

func TestCustomers_Unarchive(t *testing.T) {
	client, requests := mock(204, "", ``)
	call(t, client.Customers().Unarchive, "id_or_alias")
	expect(t, requests, "POST /api/v1/customers/id_or_alias/unarchive")
}
