// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// CustomerEventData is the CustomerEventData object of the Meteroid API.
type CustomerEventData struct {
	Alias *string `json:"alias,omitempty"`

	BillingEmail *string `json:"billing_email,omitempty"`

	Currency string `json:"currency"`

	// User-defined custom property values, keyed by definition key.
	CustomProperties json.RawMessage `json:"custom_properties"`

	CustomerID CustomerID `json:"customer_id"`

	InvoicingEmails RequiredSlice[string] `json:"invoicing_emails"`

	Name string `json:"name"`

	Phone *string `json:"phone,omitempty"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *CustomerEventData) UnmarshalJSON(data []byte) error {
	type plain CustomerEventData
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "alias", "billing_email", "currency", "custom_properties", "customer_id", "invoicing_emails", "name", "phone")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v CustomerEventData) MarshalJSON() ([]byte, error) {
	type plain CustomerEventData
	return marshalWithExtra(plain(v), v.ExtraFields)
}
