// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// CustomPropertyDefinitionUpdateRequest is the CustomPropertyDefinitionUpdateRequest object of the Meteroid API.
//
// Update of a definition. `key`, `entity_type` and `property_type` are immutable and cannot be
// changed here. Any field left absent is unchanged.
type CustomPropertyDefinitionUpdateRequest struct {
	Config *PropertyConfig `json:"config,omitempty"`

	DefaultValue json.RawMessage `json:"default_value,omitempty"`

	Description *string `json:"description,omitempty"`

	DisplayOrder *int32 `json:"display_order,omitempty"`

	Name *string `json:"name,omitempty"`

	Required *bool `json:"required,omitempty"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *CustomPropertyDefinitionUpdateRequest) UnmarshalJSON(data []byte) error {
	type plain CustomPropertyDefinitionUpdateRequest
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "CustomPropertyDefinitionUpdateRequest")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "config", "default_value", "description", "display_order", "name", "required")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v CustomPropertyDefinitionUpdateRequest) MarshalJSON() ([]byte, error) {
	type plain CustomPropertyDefinitionUpdateRequest
	return marshalWithExtra(plain(v), v.ExtraFields)
}
