// Code generated by perseid. DO NOT EDIT.

package meteroid

import (
	"encoding/json"
	"time"
)

// CustomerDetails is the CustomerDetails object of the Meteroid API.
type CustomerDetails struct {
	Alias *string `json:"alias,omitempty"`

	BillingAddress *Address `json:"billing_address,omitempty"`

	Email *string `json:"email,omitempty"`

	ID CustomerID `json:"id"`

	Name string `json:"name"`

	// RFC 3339 timestamp.
	SnapshotAt time.Time `json:"snapshot_at"`

	VatNumber *string `json:"vat_number,omitempty"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *CustomerDetails) UnmarshalJSON(data []byte) error {
	type plain CustomerDetails
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "CustomerDetails", "id", "name", "snapshot_at")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "alias", "billing_address", "email", "id", "name", "snapshot_at", "vat_number")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v CustomerDetails) MarshalJSON() ([]byte, error) {
	type plain CustomerDetails
	return marshalWithExtra(plain(v), v.ExtraFields)
}
