// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// CustomerCreateRequest is the CustomerCreateRequest object of the Meteroid API.
type CustomerCreateRequest struct {
	Alias *string `json:"alias,omitempty"`

	BillingAddress *Address `json:"billing_address,omitempty"`

	BillingEmail *string `json:"billing_email,omitempty"`

	// BT-10 — the reference the buyer routes invoices by (a Leitweg-ID for German
	// public bodies). Required by XRechnung.
	BuyerReference *string `json:"buyer_reference,omitempty"`

	ConnectedAccountID *string `json:"connected_account_id,omitempty"`

	Currency Currency `json:"currency"`

	// User-defined custom property values, keyed by definition `key`. Validated against the
	// tenant's `CUSTOMER` property definitions. Omit to leave unset.
	CustomProperties json.RawMessage `json:"custom_properties,omitempty"`

	CustomTaxes []CustomTaxRate `json:"custom_taxes,omitempty"`

	// `INDIVIDUAL` requires `first_name`, `last_name`, and a billing-address country.
	CustomerType *CustomerType `json:"customer_type,omitempty"`

	// Free-text legal exemption mention surfaced on exempt invoices.
	ExemptionReason *string `json:"exemption_reason,omitempty"`

	FirstName *string `json:"first_name,omitempty"`

	InvoicingEmails []string `json:"invoicing_emails,omitempty"`

	InvoicingEntityID *InvoicingEntityID `json:"invoicing_entity_id,omitempty"`

	// Deprecated: use `preferred_locales`. Applied only when `preferred_locales` is absent.
	//
	// Deprecated: this field is deprecated in the Meteroid API.
	InvoicingLanguage *string `json:"invoicing_language,omitempty"`

	IsTaxExempt *bool `json:"is_tax_exempt,omitempty"`

	LastName *string `json:"last_name,omitempty"`

	// BT-47 — the buyer's national register identifier (SIREN/SIRET, HRB).
	LegalNumber *string `json:"legal_number,omitempty"`

	// Required for `COMPANY`. Ignored for `INDIVIDUAL`: derived from `first_name` + `last_name`.
	Name *string `json:"name,omitempty"`

	Phone *string `json:"phone,omitempty"`

	// Preferred document languages, most-preferred first (BCP-47 tags, e.g.
	// `["fr-FR", "en"]`); overrides the invoicing entity default. The first one the
	// renderer has a template for wins, so an unsupported entry alongside a supported
	// one just falls through; a list of only unsupported ones is rejected.
	PreferredLocales []string `json:"preferred_locales,omitempty"`

	ShippingAddress *ShippingAddress `json:"shipping_address,omitempty"`

	VatNumber *string `json:"vat_number,omitempty"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *CustomerCreateRequest) UnmarshalJSON(data []byte) error {
	type plain CustomerCreateRequest
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "CustomerCreateRequest", "currency")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "alias", "billing_address", "billing_email", "buyer_reference", "connected_account_id", "currency", "custom_properties", "custom_taxes", "customer_type", "exemption_reason", "first_name", "invoicing_emails", "invoicing_entity_id", "invoicing_language", "is_tax_exempt", "last_name", "legal_number", "name", "phone", "preferred_locales", "shipping_address", "vat_number")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v CustomerCreateRequest) MarshalJSON() ([]byte, error) {
	type plain CustomerCreateRequest
	return marshalWithExtra(plain(v), v.ExtraFields)
}
