// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// Customer is the Customer object of the Meteroid API.
type Customer struct {
	Alias *string `json:"alias,omitempty"`

	BillingAddress *Address `json:"billing_address,omitempty"`

	BillingEmail *string `json:"billing_email,omitempty"`

	// BT-10 — the reference the buyer routes invoices by (a Leitweg-ID for German
	// public bodies). Required by XRechnung.
	BuyerReference *string `json:"buyer_reference,omitempty"`

	ConnectedAccountID *string `json:"connected_account_id,omitempty"`

	Currency Currency `json:"currency"`

	// User-defined custom property values, keyed by definition `key`.
	CustomProperties json.RawMessage `json:"custom_properties"`

	CustomTaxes RequiredSlice[CustomTaxRate] `json:"custom_taxes"`

	CustomerType *CustomerType `json:"customer_type,omitempty"`

	FirstName *string `json:"first_name,omitempty"`

	ID CustomerID `json:"id"`

	InvoicingEmails RequiredSlice[string] `json:"invoicing_emails"`

	InvoicingEntityID InvoicingEntityID `json:"invoicing_entity_id"`

	// Deprecated: the first entry of `preferred_locales`.
	//
	// Deprecated: this field is deprecated in the Meteroid API.
	InvoicingLanguage *string `json:"invoicing_language,omitempty"`

	LastName *string `json:"last_name,omitempty"`

	// BT-47 — the buyer's national register identifier (SIREN/SIRET, HRB).
	LegalNumber *string `json:"legal_number,omitempty"`

	Name string `json:"name"`

	Phone *string `json:"phone,omitempty"`

	// Preferred document languages, most-preferred first (BCP-47 tags, e.g.
	// `["fr-FR", "en"]`); overrides the invoicing entity default.
	PreferredLocales RequiredSlice[string] `json:"preferred_locales"`

	ShippingAddress *ShippingAddress `json:"shipping_address,omitempty"`

	VatNumber *string `json:"vat_number,omitempty"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *Customer) UnmarshalJSON(data []byte) error {
	type plain Customer
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "alias", "billing_address", "billing_email", "buyer_reference", "connected_account_id", "currency", "custom_properties", "custom_taxes", "customer_type", "first_name", "id", "invoicing_emails", "invoicing_entity_id", "invoicing_language", "last_name", "legal_number", "name", "phone", "preferred_locales", "shipping_address", "vat_number")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v Customer) MarshalJSON() ([]byte, error) {
	type plain Customer
	return marshalWithExtra(plain(v), v.ExtraFields)
}
