// Code generated by perseid. DO NOT EDIT.

package meteroid

// DeclineKind is one of [AllDeclineKindValues], or a value this SDK version
// does not know.
//
// Why the payment provider declined a charge.
type DeclineKind string

// Known values of DeclineKind.
//
// The API may add new values over time; unknown values round-trip unchanged.
const (
	DeclineKindInsufficientFunds      DeclineKind = "INSUFFICIENT_FUNDS"
	DeclineKindDoNotHonor             DeclineKind = "DO_NOT_HONOR"
	DeclineKindCardExpired            DeclineKind = "CARD_EXPIRED"
	DeclineKindAuthenticationRequired DeclineKind = "AUTHENTICATION_REQUIRED"
	DeclineKindMandateInactive        DeclineKind = "MANDATE_INACTIVE"
	DeclineKindFraud                  DeclineKind = "FRAUD"
	DeclineKindProcessingError        DeclineKind = "PROCESSING_ERROR"
	DeclineKindOther                  DeclineKind = "OTHER"
)

// AllDeclineKindValues lists every DeclineKind value known to this SDK version.
var AllDeclineKindValues = []DeclineKind{
	DeclineKindInsufficientFunds,
	DeclineKindDoNotHonor,
	DeclineKindCardExpired,
	DeclineKindAuthenticationRequired,
	DeclineKindMandateInactive,
	DeclineKindFraud,
	DeclineKindProcessingError,
	DeclineKindOther,
}

// String returns the wire representation of the value.
func (e DeclineKind) String() string {
	return string(e)
}

// IsKnown reports whether the value is one this SDK version knows about.
func (e DeclineKind) IsKnown() bool {
	for _, known := range AllDeclineKindValues {
		if e == known {
			return true
		}
	}
	return false
}
