// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// DoubleSegmentationMatrix is the DoubleSegmentationMatrix object of the Meteroid API.
type DoubleSegmentationMatrix struct {
	Dimension1 MetricDimension `json:"dimension1"`

	Dimension2 MetricDimension `json:"dimension2"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *DoubleSegmentationMatrix) UnmarshalJSON(data []byte) error {
	type plain DoubleSegmentationMatrix
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "DoubleSegmentationMatrix", "dimension1", "dimension2")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "dimension1", "dimension2")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v DoubleSegmentationMatrix) MarshalJSON() ([]byte, error) {
	type plain DoubleSegmentationMatrix
	return marshalWithExtra(plain(v), v.ExtraFields)
}
