// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// EInvoicingFinding is the EInvoicingFinding object of the Meteroid API.
//
// One rule the document did not satisfy, in the standard's own vocabulary.
type EInvoicingFinding struct {
	Hint *string `json:"hint,omitempty"`

	Message string `json:"message"`

	// The rule identifier — "BR-11", "PEPPOL-EN16931-R003".
	Rule string `json:"rule"`

	// The business term path it is about — "BG-8/BT-55".
	Term string `json:"term"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *EInvoicingFinding) UnmarshalJSON(data []byte) error {
	type plain EInvoicingFinding
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "hint", "message", "rule", "term")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v EInvoicingFinding) MarshalJSON() ([]byte, error) {
	type plain EInvoicingFinding
	return marshalWithExtra(plain(v), v.ExtraFields)
}
