// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// EntitlementProductRef is the EntitlementProductRef object of the Meteroid API.
//
// Minimal reference to the product a feature belongs to.
type EntitlementProductRef struct {
	ID ProductID `json:"id"`

	Name string `json:"name"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *EntitlementProductRef) UnmarshalJSON(data []byte) error {
	type plain EntitlementProductRef
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "EntitlementProductRef", "id", "name")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "id", "name")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v EntitlementProductRef) MarshalJSON() ([]byte, error) {
	type plain EntitlementProductRef
	return marshalWithExtra(plain(v), v.ExtraFields)
}
