// Code generated by perseid. DO NOT EDIT.

package meteroid

import (
	"encoding/json"
	"time"
)

// Entitlement is the Entitlement object of the Meteroid API.
//
// A raw entitlement row attached to one entity (feature, plan version, add-on, or subscription).
type Entitlement struct {
	// RFC 3339 timestamp.
	CreatedAt time.Time `json:"created_at"`

	FeatureID FeatureID `json:"feature_id"`

	ID EntitlementID `json:"id"`

	// RFC 3339 timestamp.
	UpdatedAt time.Time `json:"updated_at"`

	Value EntitlementValue `json:"value"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *Entitlement) UnmarshalJSON(data []byte) error {
	type plain Entitlement
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "Entitlement", "created_at", "feature_id", "id", "updated_at", "value")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "created_at", "feature_id", "id", "updated_at", "value")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v Entitlement) MarshalJSON() ([]byte, error) {
	type plain Entitlement
	return marshalWithExtra(plain(v), v.ExtraFields)
}
