// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// ExistingProductRef is the ExistingProductRef object of the Meteroid API.
type ExistingProductRef struct {
	ID ProductID `json:"id"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *ExistingProductRef) UnmarshalJSON(data []byte) error {
	type plain ExistingProductRef
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "ExistingProductRef", "id")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "id")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v ExistingProductRef) MarshalJSON() ([]byte, error) {
	type plain ExistingProductRef
	return marshalWithExtra(plain(v), v.ExtraFields)
}
