// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// ExternalPaymentMethodConfig is the ExternalPaymentMethodConfig object of the Meteroid API.
type ExternalPaymentMethodConfig struct {
	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *ExternalPaymentMethodConfig) UnmarshalJSON(data []byte) error {
	type plain ExternalPaymentMethodConfig
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data)
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v ExternalPaymentMethodConfig) MarshalJSON() ([]byte, error) {
	type plain ExternalPaymentMethodConfig
	return marshalWithExtra(plain(v), v.ExtraFields)
}
