// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// ExtraRecurringFeeStructure is the ExtraRecurringFeeStructure object of the Meteroid API.
type ExtraRecurringFeeStructure struct {
	BillingType ExtraRecurringBillingTypeEnum `json:"billing_type"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *ExtraRecurringFeeStructure) UnmarshalJSON(data []byte) error {
	type plain ExtraRecurringFeeStructure
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "billing_type")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v ExtraRecurringFeeStructure) MarshalJSON() ([]byte, error) {
	type plain ExtraRecurringFeeStructure
	return marshalWithExtra(plain(v), v.ExtraFields)
}
