// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// FeatureListResponse is the FeatureListResponse object of the Meteroid API.
type FeatureListResponse struct {
	Data RequiredSlice[Feature] `json:"data"`

	PaginationMeta PaginationResponse `json:"pagination_meta"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *FeatureListResponse) UnmarshalJSON(data []byte) error {
	type plain FeatureListResponse
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "data", "pagination_meta")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v FeatureListResponse) MarshalJSON() ([]byte, error) {
	type plain FeatureListResponse
	return marshalWithExtra(plain(v), v.ExtraFields)
}
