// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// FixedWindowResetPeriod is the FixedWindowResetPeriod object of the Meteroid API.
//
// Resets at regular intervals — anchored to your subscription's exact activation time.
type FixedWindowResetPeriod struct {
	Interval int32 `json:"interval"`

	Unit CalendarUnit `json:"unit"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *FixedWindowResetPeriod) UnmarshalJSON(data []byte) error {
	type plain FixedWindowResetPeriod
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "interval", "unit")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v FixedWindowResetPeriod) MarshalJSON() ([]byte, error) {
	type plain FixedWindowResetPeriod
	return marshalWithExtra(plain(v), v.ExtraFields)
}
