// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// GroupedUsage is the GroupedUsage object of the Meteroid API.
type GroupedUsage struct {
	Dimensions RequiredMap[string] `json:"dimensions"`

	Value string `json:"value"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *GroupedUsage) UnmarshalJSON(data []byte) error {
	type plain GroupedUsage
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "dimensions", "value")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v GroupedUsage) MarshalJSON() ([]byte, error) {
	type plain GroupedUsage
	return marshalWithExtra(plain(v), v.ExtraFields)
}
