// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// IngestFailure is the IngestFailure object of the Meteroid API.
type IngestFailure struct {
	EventID string `json:"event_id"`

	Reason string `json:"reason"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *IngestFailure) UnmarshalJSON(data []byte) error {
	type plain IngestFailure
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "event_id", "reason")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v IngestFailure) MarshalJSON() ([]byte, error) {
	type plain IngestFailure
	return marshalWithExtra(plain(v), v.ExtraFields)
}
