// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// IntrospectionRequest is the IntrospectionRequest object of the Meteroid API.
//
// Token introspection request
type IntrospectionRequest struct {
	// The token to introspect
	Token string `json:"token"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *IntrospectionRequest) UnmarshalJSON(data []byte) error {
	type plain IntrospectionRequest
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "IntrospectionRequest", "token")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "token")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v IntrospectionRequest) MarshalJSON() ([]byte, error) {
	type plain IntrospectionRequest
	return marshalWithExtra(plain(v), v.ExtraFields)
}
