// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// InvoiceDocumentsEventData is the InvoiceDocumentsEventData object of the Meteroid API.
//
// Emitted once the accounting PDF is stored. This is also the moment the e-invoicing
// outcome is known: the structured document is produced with the PDF, not at finalization.
type InvoiceDocumentsEventData struct {
	CustomerID CustomerID `json:"customer_id"`

	// Set when generation failed for a reason that is not a business rule.
	EinvoicingError *string `json:"einvoicing_error,omitempty"`

	// Empty unless the status is `failed`.
	EinvoicingFindings RequiredSlice[EInvoicingFinding] `json:"einvoicing_findings"`

	// The profile the document was checked against, e.g. "EN 16931".
	EinvoicingProfile *string `json:"einvoicing_profile,omitempty"`

	EinvoicingStatus *EInvoicingStatus `json:"einvoicing_status,omitempty"`

	InvoiceID InvoiceID `json:"invoice_id"`

	PdfDocumentID string `json:"pdf_document_id"`

	// The structured e-invoice stored beside the PDF, when one was produced.
	XMLDocumentID *string `json:"xml_document_id,omitempty"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *InvoiceDocumentsEventData) UnmarshalJSON(data []byte) error {
	type plain InvoiceDocumentsEventData
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "InvoiceDocumentsEventData", "customer_id", "einvoicing_findings", "invoice_id", "pdf_document_id")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "customer_id", "einvoicing_error", "einvoicing_findings", "einvoicing_profile", "einvoicing_status", "invoice_id", "pdf_document_id", "xml_document_id")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v InvoiceDocumentsEventData) MarshalJSON() ([]byte, error) {
	type plain InvoiceDocumentsEventData
	return marshalWithExtra(plain(v), v.ExtraFields)
}
