// Code generated by perseid. DO NOT EDIT.

package meteroid

import (
	"encoding/json"
	"time"
)

// Invoice is the Invoice object of the Meteroid API.
type Invoice struct {
	AmountDue int64 `json:"amount_due"`

	AppliedCredits int64 `json:"applied_credits"`

	// The period/moment this invoice is about — the subscription period start, or the invoice's
	// own date for manual/one-off. Stable and always present, distinct from `invoice_date` (the
	// emission date). Shown as "Invoice date".
	BillingPeriodStart *Date `json:"billing_period_start,omitempty"`

	ChildInvoiceID *InvoiceID `json:"child_invoice_id,omitempty"`

	Coupons RequiredSlice[CouponLineItem] `json:"coupons"`

	// RFC 3339 timestamp.
	CreatedAt time.Time `json:"created_at"`

	Currency Currency `json:"currency"`

	// User-defined custom property values, keyed by definition `key`.
	CustomProperties json.RawMessage `json:"custom_properties"`

	CustomerDetails CustomerDetails `json:"customer_details"`

	CustomerID CustomerID `json:"customer_id"`

	DueDate *Date `json:"due_date,omitempty"`

	EinvoicingStatus *EInvoicingStatus `json:"einvoicing_status,omitempty"`

	// RFC 3339 timestamp.
	FinalizedAt *time.Time `json:"finalized_at,omitempty"`

	ID InvoiceID `json:"id"`

	InvoiceDate Date `json:"invoice_date"`

	InvoiceNumber string `json:"invoice_number"`

	InvoiceType InvoiceType `json:"invoice_type"`

	LineItems RequiredSlice[InvoiceLineItem] `json:"line_items"`

	// RFC 3339 timestamp.
	MarkedAsUncollectibleAt *time.Time `json:"marked_as_uncollectible_at,omitempty"`

	Memo *string `json:"memo,omitempty"`

	NetTerms int32 `json:"net_terms"`

	// RFC 3339 timestamp.
	PaidAt *time.Time `json:"paid_at,omitempty"`

	ParentInvoiceID *InvoiceID `json:"parent_invoice_id,omitempty"`

	PaymentStatus InvoicePaymentStatus `json:"payment_status"`

	PurchaseOrder *string `json:"purchase_order,omitempty"`

	Reference *string `json:"reference,omitempty"`

	Status InvoiceStatus `json:"status"`

	SubscriptionID *SubscriptionID `json:"subscription_id,omitempty"`

	Subtotal int64 `json:"subtotal"`

	SubtotalRecurring int64 `json:"subtotal_recurring"`

	TaxAmount int64 `json:"tax_amount"`

	TaxBreakdown RequiredSlice[TaxBreakdownItem] `json:"tax_breakdown"`

	// The prices billed were quoted tax-included. Amounts are net regardless: the tax was
	// carved out of the quoted price, so `total` is that price to the unit.
	TaxInclusive bool `json:"tax_inclusive"`

	Total int64 `json:"total"`

	Transactions RequiredSlice[Transaction] `json:"transactions"`

	// RFC 3339 timestamp.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`

	// RFC 3339 timestamp.
	VoidedAt *time.Time `json:"voided_at,omitempty"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *Invoice) UnmarshalJSON(data []byte) error {
	type plain Invoice
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "amount_due", "applied_credits", "billing_period_start", "child_invoice_id", "coupons", "created_at", "currency", "custom_properties", "customer_details", "customer_id", "due_date", "einvoicing_status", "finalized_at", "id", "invoice_date", "invoice_number", "invoice_type", "line_items", "marked_as_uncollectible_at", "memo", "net_terms", "paid_at", "parent_invoice_id", "payment_status", "purchase_order", "reference", "status", "subscription_id", "subtotal", "subtotal_recurring", "tax_amount", "tax_breakdown", "tax_inclusive", "total", "transactions", "updated_at", "voided_at")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v Invoice) MarshalJSON() ([]byte, error) {
	type plain Invoice
	return marshalWithExtra(plain(v), v.ExtraFields)
}
