// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// InvoiceListResponse is the InvoiceListResponse object of the Meteroid API.
type InvoiceListResponse struct {
	Data RequiredSlice[Invoice] `json:"data"`

	PaginationMeta PaginationResponse `json:"pagination_meta"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *InvoiceListResponse) UnmarshalJSON(data []byte) error {
	type plain InvoiceListResponse
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "InvoiceListResponse", "data", "pagination_meta")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "data", "pagination_meta")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v InvoiceListResponse) MarshalJSON() ([]byte, error) {
	type plain InvoiceListResponse
	return marshalWithExtra(plain(v), v.ExtraFields)
}
