// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// InvoiceCustomPropertiesRequest is the InvoiceCustomPropertiesRequest object of the Meteroid API.
//
// Merge update of an invoice's custom property values (send a key with `null` to remove it).
// Allowed at any status — custom properties stay editable after the invoice is finalized.
type InvoiceCustomPropertiesRequest struct {
	CustomProperties json.RawMessage `json:"custom_properties"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *InvoiceCustomPropertiesRequest) UnmarshalJSON(data []byte) error {
	type plain InvoiceCustomPropertiesRequest
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "InvoiceCustomPropertiesRequest")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "custom_properties")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v InvoiceCustomPropertiesRequest) MarshalJSON() ([]byte, error) {
	type plain InvoiceCustomPropertiesRequest
	return marshalWithExtra(plain(v), v.ExtraFields)
}
