// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// InvoiceLineItem is the InvoiceLineItem object of the Meteroid API.
type InvoiceLineItem struct {
	AmountTotal int64 `json:"amount_total"`

	Description *string `json:"description,omitempty"`

	EndDate Date `json:"end_date"`

	Name string `json:"name"`

	Quantity *string `json:"quantity,omitempty"`

	// The tax-included unit price the customer was quoted, on a line billed from
	// tax-inclusive prices. `unit_price` is its net counterpart.
	QuotedUnitPrice *string `json:"quoted_unit_price,omitempty"`

	StartDate Date `json:"start_date"`

	SubLineItems RequiredSlice[SubLineItem] `json:"sub_line_items"`

	TaxRate string `json:"tax_rate"`

	UnitPrice *string `json:"unit_price,omitempty"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *InvoiceLineItem) UnmarshalJSON(data []byte) error {
	type plain InvoiceLineItem
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "amount_total", "description", "end_date", "name", "quantity", "quoted_unit_price", "start_date", "sub_line_items", "tax_rate", "unit_price")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v InvoiceLineItem) MarshalJSON() ([]byte, error) {
	type plain InvoiceLineItem
	return marshalWithExtra(plain(v), v.ExtraFields)
}
