// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// JSONConfigValue is the JsonConfigValue object of the Meteroid API.
//
// A structured (JSON) config value — the "metadata" case, several fields in one entitlement.
type JSONConfigValue struct {
	Value json.RawMessage `json:"value"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *JSONConfigValue) UnmarshalJSON(data []byte) error {
	type plain JSONConfigValue
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "JSONConfigValue")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "value")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v JSONConfigValue) MarshalJSON() ([]byte, error) {
	type plain JSONConfigValue
	return marshalWithExtra(plain(v), v.ExtraFields)
}
