// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// ListCheckoutSessionsResponse is the ListCheckoutSessionsResponse object of the Meteroid API.
type ListCheckoutSessionsResponse struct {
	Sessions RequiredSlice[CheckoutSession] `json:"sessions"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *ListCheckoutSessionsResponse) UnmarshalJSON(data []byte) error {
	type plain ListCheckoutSessionsResponse
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "ListCheckoutSessionsResponse", "sessions")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "sessions")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v ListCheckoutSessionsResponse) MarshalJSON() ([]byte, error) {
	type plain ListCheckoutSessionsResponse
	return marshalWithExtra(plain(v), v.ExtraFields)
}
