// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// MatrixDimension is the MatrixDimension object of the Meteroid API.
type MatrixDimension struct {
	Key string `json:"key"`

	Value string `json:"value"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *MatrixDimension) UnmarshalJSON(data []byte) error {
	type plain MatrixDimension
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "MatrixDimension", "key", "value")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "key", "value")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v MatrixDimension) MarshalJSON() ([]byte, error) {
	type plain MatrixDimension
	return marshalWithExtra(plain(v), v.ExtraFields)
}
