// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// MatrixPlanPricing is the MatrixPlanPricing object of the Meteroid API.
type MatrixPlanPricing struct {
	Rates RequiredSlice[MatrixRow] `json:"rates"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *MatrixPlanPricing) UnmarshalJSON(data []byte) error {
	type plain MatrixPlanPricing
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "MatrixPlanPricing", "rates")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "rates")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v MatrixPlanPricing) MarshalJSON() ([]byte, error) {
	type plain MatrixPlanPricing
	return marshalWithExtra(plain(v), v.ExtraFields)
}
