// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// MeteredResolvedEntitlementValue is the MeteredResolvedEntitlementValue object of the Meteroid API.
type MeteredResolvedEntitlementValue struct {
	Enabled bool `json:"enabled"`

	Limit *string `json:"limit,omitempty"`

	MetricID BillableMetricID `json:"metric_id"`

	ResetPeriod ResetPeriod `json:"reset_period"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *MeteredResolvedEntitlementValue) UnmarshalJSON(data []byte) error {
	type plain MeteredResolvedEntitlementValue
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "MeteredResolvedEntitlementValue", "enabled", "metric_id", "reset_period")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "enabled", "limit", "metric_id", "reset_period")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v MeteredResolvedEntitlementValue) MarshalJSON() ([]byte, error) {
	type plain MeteredResolvedEntitlementValue
	return marshalWithExtra(plain(v), v.ExtraFields)
}
