// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// MetricDimension is the MetricDimension object of the Meteroid API.
type MetricDimension struct {
	Key string `json:"key"`

	Values RequiredSlice[string] `json:"values"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *MetricDimension) UnmarshalJSON(data []byte) error {
	type plain MetricDimension
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "MetricDimension", "key", "values")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "key", "values")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v MetricDimension) MarshalJSON() ([]byte, error) {
	type plain MetricDimension
	return marshalWithExtra(plain(v), v.ExtraFields)
}
