// Code generated by perseid. DO NOT EDIT.

package meteroid_test

import (
	"testing"

	"github.com/meteroid-oss/meteroid-go"
)

func TestMetrics_List(t *testing.T) {
	client, requests := mock(200, "application/json", `{"data":[{"aggregation_type":"COUNT","code":"sample","created_at":"2023-12-31T23:59:59.999-05:30","id":"billable_metric_id_78","name":"sample"}],"pagination_meta":{"page":-123456789,"per_page":-123456789,"total_items":-9007199254740993,"total_pages":123456789}}`)
	call(t, client.Metrics().List, nil)
	expect(t, requests, "GET /api/v1/metrics")
}

func TestMetrics_Create(t *testing.T) {
	client, requests := mock(200, "application/json", `{"aggregation_type":"LATEST","code":"sample","created_at":"2023-12-31T23:59:59.999-05:30","id":"billable_metric_id_40","name":"sample","product_family_id":"product_family_id_90"}`)
	call(t, client.Metrics().Create, decode[meteroid.CreateMetricRequest](t, `{"aggregation_type":"LATEST","code":"sample","name":"sample","product_family_id":"product_family_id_13"}`))
	expect(t, requests, "POST /api/v1/metrics")
}

func TestMetrics_Retrieve(t *testing.T) {
	client, requests := mock(200, "application/json", `{"aggregation_type":"LATEST","code":"sample","created_at":"2023-12-31T23:59:59.999-05:30","id":"billable_metric_id_40","name":"sample","product_family_id":"product_family_id_90"}`)
	call(t, client.Metrics().Retrieve, "metric_id")
	expect(t, requests, "GET /api/v1/metrics/metric_id")
}

func TestMetrics_Update(t *testing.T) {
	client, requests := mock(200, "application/json", `{"aggregation_type":"LATEST","code":"sample","created_at":"2023-12-31T23:59:59.999-05:30","id":"billable_metric_id_40","name":"sample","product_family_id":"product_family_id_90"}`)
	call(t, client.Metrics().Update, "metric_id", decode[meteroid.UpdateMetricRequest](t, `{}`))
	expect(t, requests, "PATCH /api/v1/metrics/metric_id")
}

func TestMetrics_Archive(t *testing.T) {
	client, requests := mock(204, "", ``)
	call(t, client.Metrics().Archive, "metric_id")
	expect(t, requests, "POST /api/v1/metrics/metric_id/archive")
}

func TestMetrics_Unarchive(t *testing.T) {
	client, requests := mock(204, "", ``)
	call(t, client.Metrics().Unarchive, "metric_id")
	expect(t, requests, "POST /api/v1/metrics/metric_id/unarchive")
}
