// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// MetricUsage is the MetricUsage object of the Meteroid API.
type MetricUsage struct {
	GroupedUsage RequiredSlice[GroupedUsage] `json:"grouped_usage"`

	MetricCode string `json:"metric_code"`

	MetricID BillableMetricID `json:"metric_id"`

	MetricName string `json:"metric_name"`

	TotalValue string `json:"total_value"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *MetricUsage) UnmarshalJSON(data []byte) error {
	type plain MetricUsage
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "grouped_usage", "metric_code", "metric_id", "metric_name", "total_value")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v MetricUsage) MarshalJSON() ([]byte, error) {
	type plain MetricUsage
	return marshalWithExtra(plain(v), v.ExtraFields)
}
