// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// MetricSegmentationMatrix is a tagged union discriminated by the type field.
//
// When [MetricSegmentationMatrix.IsKnown] reports true, exactly one variant pointer is
// set, matching Type. A variant added to the API after this SDK
// version was released still decodes without error, but with every variant
// pointer nil: always give a `switch` on Type a `default:` branch (or
// check IsKnown first) instead of dereferencing a pointer unconditionally. The
// unknown variant's JSON is available from [MetricSegmentationMatrix.Raw].
type MetricSegmentationMatrix struct {
	// Type selects the active variant. Compare it against the
	// MetricSegmentationMatrix* constants.
	Type MetricSegmentationMatrixType `json:"type"`

	// Single is set when Type is MetricSegmentationMatrixSingle.
	Single *MetricDimension `json:"-"`
	// Double is set when Type is MetricSegmentationMatrixDouble.
	Double *DoubleSegmentationMatrix `json:"-"`
	// Linked is set when Type is MetricSegmentationMatrixLinked.
	Linked *LinkedSegmentationMatrix `json:"-"`

	// raw keeps the payload of a variant this SDK version does not know about, so
	// that decoding and re-encoding an unknown variant preserves every field and
	// value. It is not byte-for-byte identical: `encoding/json` compacts the
	// whitespace and escapes `<`, `>` and `&` as `\u003c`, `\u003e` and `\u0026`.
	raw json.RawMessage
}

// MetricSegmentationMatrixType is the type of a [MetricSegmentationMatrix], one of the MetricSegmentationMatrix*
// constants for a variant this SDK version knows.
type MetricSegmentationMatrixType string

// Discriminator values for MetricSegmentationMatrix.
const (
	MetricSegmentationMatrixSingle MetricSegmentationMatrixType = "SINGLE"
	MetricSegmentationMatrixDouble MetricSegmentationMatrixType = "DOUBLE"
	MetricSegmentationMatrixLinked MetricSegmentationMatrixType = "LINKED"
)

// NewMetricSegmentationMatrixSingle builds a MetricSegmentationMatrix holding the SINGLE variant.
func NewMetricSegmentationMatrixSingle(value MetricDimension) MetricSegmentationMatrix {
	return MetricSegmentationMatrix{Type: MetricSegmentationMatrixSingle, Single: &value}
}

// NewMetricSegmentationMatrixDouble builds a MetricSegmentationMatrix holding the DOUBLE variant.
func NewMetricSegmentationMatrixDouble(value DoubleSegmentationMatrix) MetricSegmentationMatrix {
	return MetricSegmentationMatrix{Type: MetricSegmentationMatrixDouble, Double: &value}
}

// NewMetricSegmentationMatrixLinked builds a MetricSegmentationMatrix holding the LINKED variant.
func NewMetricSegmentationMatrixLinked(value LinkedSegmentationMatrix) MetricSegmentationMatrix {
	return MetricSegmentationMatrix{Type: MetricSegmentationMatrixLinked, Linked: &value}
}

// IsKnown reports whether Type is one of the variants this SDK version
// knows about, i.e. one of the MetricSegmentationMatrix* constants. It is false for a
// variant added to the API later, whose payload is then only available from
// [MetricSegmentationMatrix.Raw].
func (u MetricSegmentationMatrix) IsKnown() bool {
	switch u.Type {
	case MetricSegmentationMatrixSingle, MetricSegmentationMatrixDouble, MetricSegmentationMatrixLinked:
		return true
	}
	return false
}

// Raw returns the JSON of a variant this SDK version does not know about, as
// decoded (see [MetricSegmentationMatrix.IsKnown]). It is nil for a known variant, and
// for a value that was not decoded from JSON. The returned slice is a copy.
func (u MetricSegmentationMatrix) Raw() json.RawMessage {
	if u.IsKnown() || len(u.raw) == 0 {
		return nil
	}
	return append(json.RawMessage(nil), u.raw...)
}

// MarshalJSON implements json.Marshaler.
func (u MetricSegmentationMatrix) MarshalJSON() ([]byte, error) {
	switch u.Type {
	case MetricSegmentationMatrixSingle:
		if u.Single == nil {
			return nil, &UnionError{Union: "MetricSegmentationMatrix", Discriminator: string(u.Type), Reason: "variant payload is nil"}
		}
		return marshalUnionVariant("type", string(u.Type), u.Single)
	case MetricSegmentationMatrixDouble:
		if u.Double == nil {
			return nil, &UnionError{Union: "MetricSegmentationMatrix", Discriminator: string(u.Type), Reason: "variant payload is nil"}
		}
		return marshalUnionVariant("type", string(u.Type), u.Double)
	case MetricSegmentationMatrixLinked:
		if u.Linked == nil {
			return nil, &UnionError{Union: "MetricSegmentationMatrix", Discriminator: string(u.Type), Reason: "variant payload is nil"}
		}
		return marshalUnionVariant("type", string(u.Type), u.Linked)
	}

	if len(u.raw) > 0 {
		return u.raw, nil
	}
	if u.Type == "" {
		return nil, &UnionError{Union: "MetricSegmentationMatrix", Discriminator: "", Reason: "no variant set"}
	}
	return nil, &UnionError{Union: "MetricSegmentationMatrix", Discriminator: string(u.Type), Reason: "unknown discriminator"}
}

// UnmarshalJSON implements json.Unmarshaler.
//
// Payloads carrying an unrecognized discriminator are kept rather than rejected,
// so a newer API version does not break older SDK builds. Re-encoding such a
// value reproduces the same JSON document, though not necessarily the same
// bytes: `encoding/json` compacts whitespace and escapes `<`, `>` and `&`.
func (u *MetricSegmentationMatrix) UnmarshalJSON(data []byte) error {
	var tag struct {
		Type MetricSegmentationMatrixType `json:"type"`
	}
	if err := json.Unmarshal(data, &tag); err != nil {
		return err
	}

	*u = MetricSegmentationMatrix{Type: tag.Type}
	switch tag.Type {
	case MetricSegmentationMatrixSingle:
		u.Single = new(MetricDimension)
		return json.Unmarshal(data, u.Single)
	case MetricSegmentationMatrixDouble:
		u.Double = new(DoubleSegmentationMatrix)
		return json.Unmarshal(data, u.Double)
	case MetricSegmentationMatrixLinked:
		u.Linked = new(LinkedSegmentationMatrix)
		return json.Unmarshal(data, u.Linked)
	default:
		u.raw = append(json.RawMessage(nil), data...)
		return nil
	}
}
