// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// MinimumCommitment is the MinimumCommitment object of the Meteroid API.
type MinimumCommitment struct {
	// Decimal string in the plan currency, e.g. "100.00".
	Amount string `json:"amount"`

	Scope MinimumCommitmentScope `json:"scope"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *MinimumCommitment) UnmarshalJSON(data []byte) error {
	type plain MinimumCommitment
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "MinimumCommitment", "amount", "scope")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "amount", "scope")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v MinimumCommitment) MarshalJSON() ([]byte, error) {
	type plain MinimumCommitment
	return marshalWithExtra(plain(v), v.ExtraFields)
}
