// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// NumberConfigValue is the NumberConfigValue object of the Meteroid API.
//
// A number config value (decimal, encoded as a string).
type NumberConfigValue struct {
	Value string `json:"value"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *NumberConfigValue) UnmarshalJSON(data []byte) error {
	type plain NumberConfigValue
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "NumberConfigValue", "value")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "value")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v NumberConfigValue) MarshalJSON() ([]byte, error) {
	type plain NumberConfigValue
	return marshalWithExtra(plain(v), v.ExtraFields)
}
