// Code generated by perseid. DO NOT EDIT.

package meteroid

import (
	"encoding/json"
	"time"
)

// OAuthApp is the OAuthApp object of the Meteroid API.
//
// An OAuth application registered by a platform
type OAuthApp struct {
	ClientID string `json:"client_id"`

	ClientSecretHint string `json:"client_secret_hint"`

	// RFC 3339 timestamp.
	CreatedAt time.Time `json:"created_at"`

	ID OAuthAppID `json:"id"`

	IsActive bool `json:"is_active"`

	Name string `json:"name"`

	OrganizationID OrganizationID `json:"organization_id"`

	RedirectURIs RequiredSlice[string] `json:"redirect_uris"`

	Scopes RequiredSlice[string] `json:"scopes"`

	// RFC 3339 timestamp.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *OAuthApp) UnmarshalJSON(data []byte) error {
	type plain OAuthApp
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "client_id", "client_secret_hint", "created_at", "id", "is_active", "name", "organization_id", "redirect_uris", "scopes", "updated_at")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v OAuthApp) MarshalJSON() ([]byte, error) {
	type plain OAuthApp
	return marshalWithExtra(plain(v), v.ExtraFields)
}
