// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// OAuthAppsResponse is the OAuthAppsResponse object of the Meteroid API.
type OAuthAppsResponse struct {
	Data RequiredSlice[OAuthApp] `json:"data"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *OAuthAppsResponse) UnmarshalJSON(data []byte) error {
	type plain OAuthAppsResponse
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "OAuthAppsResponse", "data")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "data")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v OAuthAppsResponse) MarshalJSON() ([]byte, error) {
	type plain OAuthAppsResponse
	return marshalWithExtra(plain(v), v.ExtraFields)
}
