// Code generated by perseid. DO NOT EDIT.

package meteroid

import (
	"context"
	"net/http"
)

// OauthApps groups the oauth apps operations of the Meteroid API.
type OauthApps struct {
	client *Client
}

// List OAuth apps
//
// List all OAuth applications registered for this platform.
func (a *OauthApps) List(ctx context.Context, opts ...RequestOption) (*OAuthAppsResponse, error) {
	req := newRequest(http.MethodGet, "/api/v1/oauth-apps", opts)
	req.errors = errorSchemas{
		"429": errorSchema[RestErrorResponse],
	}
	var out OAuthAppsResponse
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Create OAuth app
//
// Register a new OAuth application. Returns the app with its client secret
// (only shown once).
func (a *OauthApps) Create(ctx context.Context, createOAuthAppRequest CreateOAuthAppRequest, opts ...RequestOption) (*OAuthAppWithSecret, error) {
	req := newRequest(http.MethodPost, "/api/v1/oauth-apps", opts)
	req.errors = errorSchemas{
		"429": errorSchema[RestErrorResponse],
	}
	req.SetJSONBody(createOAuthAppRequest)
	var out OAuthAppWithSecret
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Retrieve sends GET /api/v1/oauth-apps/{id}.
//
// # Get OAuth app
//
// Retrieve an OAuth application by ID.
func (a *OauthApps) Retrieve(ctx context.Context, id string, opts ...RequestOption) (*OAuthApp, error) {
	req := newRequest(http.MethodGet, "/api/v1/oauth-apps/{id}", opts)
	req.SetPathParam("id", id)
	req.errors = errorSchemas{
		"429": errorSchema[RestErrorResponse],
	}
	var out OAuthApp
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Delete OAuth app
//
// Delete an OAuth application and revoke all associated tokens.
func (a *OauthApps) Delete(ctx context.Context, id string, opts ...RequestOption) error {
	req := newRequest(http.MethodDelete, "/api/v1/oauth-apps/{id}", opts)
	req.SetPathParam("id", id)
	req.errors = errorSchemas{
		"429": errorSchema[RestErrorResponse],
	}
	return a.client.execute(ctx, req, nil)
}

// Rotate client secret
//
// Generate a new client secret for an OAuth app. The old secret is
// immediately invalidated.
func (a *OauthApps) Rotate(ctx context.Context, id string, opts ...RequestOption) (*RotatedSecret, error) {
	req := newRequest(http.MethodPost, "/api/v1/oauth-apps/{id}/rotate", opts)
	req.SetPathParam("id", id)
	req.errors = errorSchemas{
		"429": errorSchema[RestErrorResponse],
	}
	var out RotatedSecret
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
