// Code generated by perseid. DO NOT EDIT.

package meteroid

import (
	"context"
	"net/http"
)

// Oauth groups the oauth operations of the Meteroid API.
type Oauth struct {
	client *Client
}

// Introspect token
//
// Token introspection endpoint (RFC 7662). Requires client credentials
// via HTTP Basic auth.
//
// An error response is an [*APIError] whose Body is an [*OAuthErrorResponse] (401) or a [*RestErrorResponse] (429).
func (a *Oauth) Introspect(ctx context.Context, introspectionRequest IntrospectionRequest, opts ...RequestOption) (*TokenIntrospectionResponse, error) {
	req := newRequest(http.MethodPost, "/api/v1/oauth/introspect", opts)
	req.SetSecurity([][]string{})
	req.errors = errorSchemas{
		"401": errorSchema[OAuthErrorResponse],
		"429": errorSchema[RestErrorResponse],
	}
	req.SetFormBody(introspectionRequest, []string{}, []string{})
	var out TokenIntrospectionResponse
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Revoke token
//
// Token revocation endpoint (RFC 7009). Always returns 200 per spec.
// Requires client credentials via HTTP Basic auth.
//
// An error response is an [*APIError] whose Body is an [*OAuthErrorResponse] (401) or a [*RestErrorResponse] (429).
func (a *Oauth) Revoke(ctx context.Context, revocationRequest RevocationRequest, opts ...RequestOption) error {
	req := newRequest(http.MethodPost, "/api/v1/oauth/revoke", opts)
	req.SetSecurity([][]string{})
	req.errors = errorSchemas{
		"401": errorSchema[OAuthErrorResponse],
		"429": errorSchema[RestErrorResponse],
	}
	req.SetFormBody(revocationRequest, []string{}, []string{})
	return a.client.execute(ctx, req, nil)
}

// Token sends POST /api/v1/oauth/token.
//
// # Exchange tokens
//
// OAuth 2.0 token endpoint. Supports two grant types:
// - `authorization_code`: Exchange an authorization code for tokens
// - `refresh_token`: Refresh an access token
//
// Authenticate via HTTP Basic auth (`client_id:client_secret`) or body parameters.
//
// An error response is an [*APIError] whose Body is an [*OAuthErrorResponse] (400, 401) or a [*RestErrorResponse] (429).
func (a *Oauth) Token(ctx context.Context, tokenRequest TokenRequest, opts ...RequestOption) (*TokenResponse, error) {
	req := newRequest(http.MethodPost, "/api/v1/oauth/token", opts)
	req.SetSecurity([][]string{})
	req.errors = errorSchemas{
		"400": errorSchema[OAuthErrorResponse],
		"401": errorSchema[OAuthErrorResponse],
		"429": errorSchema[RestErrorResponse],
	}
	req.SetFormBody(tokenRequest, []string{}, []string{})
	var out TokenResponse
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
