// Code generated by perseid. DO NOT EDIT.

package meteroid_test

import (
	"testing"

	"github.com/meteroid-oss/meteroid-go"
)

func TestOauthApps_List(t *testing.T) {
	client, requests := mock(200, "application/json", `{"data":[{"client_id":"sample","client_secret_hint":"sample","created_at":"2024-03-15T10:30:45.123+02:00","id":"o_auth_app_id_90","is_active":false,"name":"sample","organization_id":"organization_id_78","redirect_uris":["sample"],"scopes":["sample"]}]}`)
	call(t, client.OauthApps().List)
	expect(t, requests, "GET /api/v1/oauth-apps")
}

func TestOauthApps_Create(t *testing.T) {
	client, requests := mock(200, "application/json", `{"app":{"client_id":"sample","client_secret_hint":"sample","created_at":"2024-03-15T10:30:45.123+02:00","id":"o_auth_app_id_90","is_active":false,"name":"sample","organization_id":"organization_id_78","redirect_uris":["sample"],"scopes":["sample"]},"client_secret":"sample"}`)
	call(t, client.OauthApps().Create, decode[meteroid.CreateOAuthAppRequest](t, `{"name":"sample","redirect_uris":["sample"]}`))
	expect(t, requests, "POST /api/v1/oauth-apps")
}

func TestOauthApps_Retrieve(t *testing.T) {
	client, requests := mock(200, "application/json", `{"client_id":"sample","client_secret_hint":"sample","created_at":"2023-12-31T23:59:59.999-05:30","id":"o_auth_app_id_44","is_active":false,"name":"sample","organization_id":"organization_id_13","redirect_uris":["sample"],"scopes":["sample"]}`)
	call(t, client.OauthApps().Retrieve, "id")
	expect(t, requests, "GET /api/v1/oauth-apps/id")
}

func TestOauthApps_Delete(t *testing.T) {
	client, requests := mock(204, "", ``)
	call(t, client.OauthApps().Delete, "id")
	expect(t, requests, "DELETE /api/v1/oauth-apps/id")
}

func TestOauthApps_Rotate(t *testing.T) {
	client, requests := mock(200, "application/json", `{"client_secret":"sample","client_secret_hint":"sample"}`)
	call(t, client.OauthApps().Rotate, "id")
	expect(t, requests, "POST /api/v1/oauth-apps/id/rotate")
}
