// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// OneTimeFee is the OneTimeFee object of the Meteroid API.
type OneTimeFee struct {
	Quantity int32 `json:"quantity"`

	Rate string `json:"rate"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *OneTimeFee) UnmarshalJSON(data []byte) error {
	type plain OneTimeFee
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "quantity", "rate")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v OneTimeFee) MarshalJSON() ([]byte, error) {
	type plain OneTimeFee
	return marshalWithExtra(plain(v), v.ExtraFields)
}
