// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// OneTimePricing is the OneTimePricing object of the Meteroid API.
type OneTimePricing struct {
	Quantity int32 `json:"quantity"`

	UnitPrice string `json:"unit_price"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *OneTimePricing) UnmarshalJSON(data []byte) error {
	type plain OneTimePricing
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "OneTimePricing", "quantity", "unit_price")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "quantity", "unit_price")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v OneTimePricing) MarshalJSON() ([]byte, error) {
	type plain OneTimePricing
	return marshalWithExtra(plain(v), v.ExtraFields)
}
