// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// OneTimePlanFee is the OneTimePlanFee object of the Meteroid API.
//
// One-time fee
type OneTimePlanFee struct {
	Quantity int32 `json:"quantity"`

	UnitPrice string `json:"unit_price"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *OneTimePlanFee) UnmarshalJSON(data []byte) error {
	type plain OneTimePlanFee
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "quantity", "unit_price")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v OneTimePlanFee) MarshalJSON() ([]byte, error) {
	type plain OneTimePlanFee
	return marshalWithExtra(plain(v), v.ExtraFields)
}
