// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// OnlinePaymentMethodConfig is the OnlinePaymentMethodConfig object of the Meteroid API.
type OnlinePaymentMethodConfig struct {
	Config *OnlineMethodsConfig `json:"config,omitempty"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *OnlinePaymentMethodConfig) UnmarshalJSON(data []byte) error {
	type plain OnlinePaymentMethodConfig
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "config")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v OnlinePaymentMethodConfig) MarshalJSON() ([]byte, error) {
	type plain OnlinePaymentMethodConfig
	return marshalWithExtra(plain(v), v.ExtraFields)
}
