// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// OnlineMethodsConfig is the OnlineMethodsConfig object of the Meteroid API.
type OnlineMethodsConfig struct {
	Card *OnlineMethodConfig `json:"card,omitempty"`

	DirectDebit *OnlineMethodConfig `json:"direct_debit,omitempty"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *OnlineMethodsConfig) UnmarshalJSON(data []byte) error {
	type plain OnlineMethodsConfig
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "card", "direct_debit")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v OnlineMethodsConfig) MarshalJSON() ([]byte, error) {
	type plain OnlineMethodsConfig
	return marshalWithExtra(plain(v), v.ExtraFields)
}
