// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// PackagePlanPricing is the PackagePlanPricing object of the Meteroid API.
type PackagePlanPricing struct {
	BlockSize int64 `json:"block_size"`

	Rate string `json:"rate"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *PackagePlanPricing) UnmarshalJSON(data []byte) error {
	type plain PackagePlanPricing
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "block_size", "rate")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v PackagePlanPricing) MarshalJSON() ([]byte, error) {
	type plain PackagePlanPricing
	return marshalWithExtra(plain(v), v.ExtraFields)
}
