// Code generated by perseid. DO NOT EDIT.

package meteroid

import (
	"encoding/json"
	"time"
)

// PaymentEvent is the PaymentEvent object of the Meteroid API.
type PaymentEvent struct {
	Amount int64 `json:"amount"`

	AmountRefunded int64 `json:"amount_refunded"`

	AmountReversed int64 `json:"amount_reversed"`

	CreditNoteID *CreditNoteID `json:"credit_note_id,omitempty"`

	Currency string `json:"currency"`

	DeclineKind *DeclineKind `json:"decline_kind,omitempty"`

	Error *string `json:"error,omitempty"`

	InvoiceID *InvoiceID `json:"invoice_id,omitempty"`

	ParentTransactionID *PaymentTransactionID `json:"parent_transaction_id,omitempty"`

	PaymentType PaymentTypeEnum `json:"payment_type"`

	// RFC 3339 timestamp.
	ProcessedAt *time.Time `json:"processed_at,omitempty"`

	ProviderTransactionID *string `json:"provider_transaction_id,omitempty"`

	RefundMode *RefundMode `json:"refund_mode,omitempty"`

	ReversalKind *ReversalKind `json:"reversal_kind,omitempty"`

	Status PaymentStatusEnum `json:"status"`

	TransactionID PaymentTransactionID `json:"transaction_id"`

	ID EventID `json:"id"`

	// RFC 3339 timestamp.
	Timestamp time.Time `json:"timestamp"`

	Type EventType `json:"type"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *PaymentEvent) UnmarshalJSON(data []byte) error {
	type plain PaymentEvent
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "PaymentEvent", "amount", "amount_refunded", "amount_reversed", "currency", "payment_type", "status", "transaction_id", "id", "timestamp", "type")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "amount", "amount_refunded", "amount_reversed", "credit_note_id", "currency", "decline_kind", "error", "invoice_id", "parent_transaction_id", "payment_type", "processed_at", "provider_transaction_id", "refund_mode", "reversal_kind", "status", "transaction_id", "id", "timestamp", "type")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v PaymentEvent) MarshalJSON() ([]byte, error) {
	type plain PaymentEvent
	return marshalWithExtra(plain(v), v.ExtraFields)
}
