// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// PaymentMethodInfo is the PaymentMethodInfo object of the Meteroid API.
type PaymentMethodInfo struct {
	AccountNumberHint *string `json:"account_number_hint,omitempty"`

	CardBrand *string `json:"card_brand,omitempty"`

	CardLast4 *string `json:"card_last4,omitempty"`

	PaymentMethodType PaymentMethodTypeEnum `json:"payment_method_type"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *PaymentMethodInfo) UnmarshalJSON(data []byte) error {
	type plain PaymentMethodInfo
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "PaymentMethodInfo", "payment_method_type")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "account_number_hint", "card_brand", "card_last4", "payment_method_type")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v PaymentMethodInfo) MarshalJSON() ([]byte, error) {
	type plain PaymentMethodInfo
	return marshalWithExtra(plain(v), v.ExtraFields)
}
