// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// PerUnitPricing is the PerUnitPricing object of the Meteroid API.
type PerUnitPricing struct {
	Rate string `json:"rate"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *PerUnitPricing) UnmarshalJSON(data []byte) error {
	type plain PerUnitPricing
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "PerUnitPricing", "rate")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "rate")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v PerUnitPricing) MarshalJSON() ([]byte, error) {
	type plain PerUnitPricing
	return marshalWithExtra(plain(v), v.ExtraFields)
}
