// Code generated by perseid. DO NOT EDIT.

package meteroid

import (
	"encoding/json"
	"time"
)

// Plan is the Plan object of the Meteroid API.
type Plan struct {
	AvailableParameters AvailableParameters `json:"available_parameters"`

	BillingCycles *int32 `json:"billing_cycles,omitempty"`

	// RFC 3339 timestamp.
	CreatedAt time.Time `json:"created_at"`

	Currency string `json:"currency"`

	Description *string `json:"description,omitempty"`

	Entitlements []Entitlement `json:"entitlements,omitempty"`

	ID PlanID `json:"id"`

	MinimumCommitment *MinimumCommitment `json:"minimum_commitment,omitempty"`

	Name string `json:"name"`

	NetTerms int32 `json:"net_terms"`

	PeriodStartDay *int32 `json:"period_start_day,omitempty"`

	PlanType PlanTypeEnum `json:"plan_type"`

	PriceComponents RequiredSlice[PriceComponent] `json:"price_components"`

	ProductFamily ProductFamily `json:"product_family"`

	SelfServiceRank *int32 `json:"self_service_rank,omitempty"`

	Status PlanStatusEnum `json:"status"`

	// The plan's amounts are quoted tax-included ("9.99 incl. VAT"): tax is carved out of
	// them at invoice time instead of being added on top, so the customer pays the quoted
	// price whatever rate applies. A customer who bears no tax (reverse charge, exempt,
	// export) still pays it in full. Defaults to `false`.
	TaxInclusive bool `json:"tax_inclusive"`

	Trial *TrialConfig `json:"trial,omitempty"`

	Version int32 `json:"version"`

	VersionID PlanVersionID `json:"version_id"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *Plan) UnmarshalJSON(data []byte) error {
	type plain Plan
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "available_parameters", "billing_cycles", "created_at", "currency", "description", "entitlements", "id", "minimum_commitment", "name", "net_terms", "period_start_day", "plan_type", "price_components", "product_family", "self_service_rank", "status", "tax_inclusive", "trial", "version", "version_id")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v Plan) MarshalJSON() ([]byte, error) {
	type plain Plan
	return marshalWithExtra(plain(v), v.ExtraFields)
}
