// Code generated by perseid. DO NOT EDIT.

package meteroid

import (
	"context"
	"encoding/json"
	"net/http"
)

// PlansVersionsListOptions carries the optional query and header parameters of
// [PlansVersions.List]. Leave a field nil to omit it.
type PlansVersionsListOptions struct {
	// Page number (0-indexed)
	Page *int32

	// Number of items per page
	PerPage *int32
}

// PlansVersions groups the plans versions operations of the Meteroid API.
type PlansVersions struct {
	client *Client
}

// UpdateMinimum sends PUT /api/v1/plans/versions/{plan_version_id}/minimum.
//
// Set or replace the plan-level minimum commitment for a draft plan version.
func (a *PlansVersions) UpdateMinimum(ctx context.Context, planVersionID string, minimumCommitment MinimumCommitment, opts ...RequestOption) (*MinimumCommitment, error) {
	req := newRequest(http.MethodPut, "/api/v1/plans/versions/{plan_version_id}/minimum", opts)
	req.SetPathParam("plan_version_id", planVersionID)
	req.errors = errorSchemas{
		"400": errorSchema[RestErrorResponse],
		"401": errorSchema[RestErrorResponse],
		"404": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
	}
	req.SetJSONBody(minimumCommitment)
	var out MinimumCommitment
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteMinimum sends DELETE /api/v1/plans/versions/{plan_version_id}/minimum.
//
// Remove the plan-level minimum commitment for a draft plan version.
func (a *PlansVersions) DeleteMinimum(ctx context.Context, planVersionID string, opts ...RequestOption) error {
	req := newRequest(http.MethodDelete, "/api/v1/plans/versions/{plan_version_id}/minimum", opts)
	req.SetPathParam("plan_version_id", planVersionID)
	req.errors = errorSchemas{
		"401": errorSchema[RestErrorResponse],
		"404": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
	}
	return a.client.execute(ctx, req, nil)
}

// fetchList sends GET /api/v1/plans/{plan_id}/versions and decodes the response, for [PlansVersions.List].
func (a *PlansVersions) fetchList(ctx context.Context, planID string, options *PlansVersionsListOptions, opts ...RequestOption) (*PlanVersionListResponse, error) {
	req := newRequest(http.MethodGet, "/api/v1/plans/{plan_id}/versions", opts)
	req.SetPathParam("plan_id", planID)
	req.errors = errorSchemas{
		"401": errorSchema[RestErrorResponse],
		"404": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
	}
	if options != nil && options.Page != nil {
		req.SetQueryParam("page", formatInt(int64(*options.Page)))
	}
	if options != nil && options.PerPage != nil {
		req.SetQueryParam("per_page", formatInt(int64(*options.PerPage)))
	}
	var out PlanVersionListResponse
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// PlansVersionsListPage is a page of [PlansVersions.List]. It embeds the
// decoded [PlanVersionListResponse], promoting its fields, with the Items of the page; a field
// named like a page member stays reachable through the embedded PlanVersionListResponse.
type PlansVersionsListPage struct {
	PlanVersionListResponse

	// Items holds the items of this page.
	Items []PlanVersionSummary

	next func(ctx context.Context) (*PlansVersionsListPage, error)
}

// HasNextPage reports whether another page follows this one.
func (p *PlansVersionsListPage) HasNextPage() bool {
	return p != nil && p.next != nil
}

// NextPage fetches the page after this one. It returns nil and no error after
// the last page.
func (p *PlansVersionsListPage) NextPage(ctx context.Context) (*PlansVersionsListPage, error) {
	if !p.HasNextPage() {
		return nil, nil
	}
	return p.next(ctx)
}

// MarshalJSON encodes the PlanVersionListResponse of the page, as received.
func (p PlansVersionsListPage) MarshalJSON() ([]byte, error) {
	return json.Marshal(&p.PlanVersionListResponse)
}

func (p *PlansVersionsListPage) pageItems() []PlanVersionSummary { return p.Items }

// List plan versions
//
// [PlansVersions.ListAutoPaging] iterates over every item instead.
func (a *PlansVersions) List(ctx context.Context, planID string, options *PlansVersionsListOptions, opts ...RequestOption) (*PlansVersionsListPage, error) {
	var params PlansVersionsListOptions
	if options != nil {
		params = *options
	}
	resp, err := a.fetchList(ctx, planID, &params, opts...)
	if err != nil {
		return nil, err
	}
	page := &PlansVersionsListPage{PlanVersionListResponse: *resp, Items: resp.Data}
	if len(page.Items) == 0 {
		return page, nil
	}
	current := int32(0)
	if params.Page != nil {
		current = *params.Page
	}
	if reached(current+1, resp.PaginationMeta.TotalPages) {
		return page, nil
	}
	next := current + 1
	params.Page = &next
	page.next = func(ctx context.Context) (*PlansVersionsListPage, error) {
		return a.List(ctx, planID, &params, opts...)
	}
	return page, nil
}

// ListAutoPaging iterates over every item of [PlansVersions.List], fetching
// further pages on demand.
func (a *PlansVersions) ListAutoPaging(ctx context.Context, planID string, options *PlansVersionsListOptions, opts ...RequestOption) *AutoPager[PlanVersionSummary] {
	return newAutoPager[PlanVersionSummary](ctx, func(ctx context.Context) (*PlansVersionsListPage, error) {
		return a.List(ctx, planID, options, opts...)
	})
}
