// Code generated by perseid. DO NOT EDIT.

package meteroid_test

import (
	"testing"

	"github.com/meteroid-oss/meteroid-go"
)

func TestPlansVersions_UpdateMinimum(t *testing.T) {
	client, requests := mock(200, "application/json", `{"amount":"sample","scope":{"type":"all_components"}}`)
	call(t, client.Plans().Versions().UpdateMinimum, "plan_version_id", decode[meteroid.MinimumCommitment](t, `{"amount":"sample","scope":{"type":"all_components"}}`))
	expect(t, requests, "PUT /api/v1/plans/versions/plan_version_id/minimum")
}

func TestPlansVersions_DeleteMinimum(t *testing.T) {
	client, requests := mock(204, "", ``)
	call(t, client.Plans().Versions().DeleteMinimum, "plan_version_id")
	expect(t, requests, "DELETE /api/v1/plans/versions/plan_version_id/minimum")
}

func TestPlansVersions_List(t *testing.T) {
	client, requests := mock(200, "application/json", `{"data":[{"created_at":"2023-12-31T23:59:59.999-05:30","currency":"CVE","id":"plan_version_id_2","is_draft":true,"version":-2147483648}],"pagination_meta":{"page":-123456789,"per_page":-123456789,"total_items":-9007199254740993,"total_pages":123456789}}`)
	call(t, client.Plans().Versions().List, "plan_id", nil)
	expect(t, requests, "GET /api/v1/plans/plan_id/versions")
}
