// Code generated by perseid. DO NOT EDIT.

package meteroid

import (
	"encoding/json"
	"time"
)

// PlanVersionSummary is the PlanVersionSummary object of the Meteroid API.
type PlanVersionSummary struct {
	// RFC 3339 timestamp.
	CreatedAt time.Time `json:"created_at"`

	Currency string `json:"currency"`

	ID PlanVersionID `json:"id"`

	IsDraft bool `json:"is_draft"`

	Version int32 `json:"version"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *PlanVersionSummary) UnmarshalJSON(data []byte) error {
	type plain PlanVersionSummary
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "created_at", "currency", "id", "is_draft", "version")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v PlanVersionSummary) MarshalJSON() ([]byte, error) {
	type plain PlanVersionSummary
	return marshalWithExtra(plain(v), v.ExtraFields)
}
