// Code generated by perseid. DO NOT EDIT.

package meteroid

import (
	"encoding/json"
	"time"
)

// PlanEventData is the PlanEventData object of the Meteroid API.
type PlanEventData struct {
	// RFC 3339 timestamp.
	CreatedAt time.Time `json:"created_at"`

	Currency string `json:"currency"`

	Description *string `json:"description,omitempty"`

	Name string `json:"name"`

	PlanID PlanID `json:"plan_id"`

	PlanType PlanTypeEnum `json:"plan_type"`

	Status PlanStatusEnum `json:"status"`

	Version int32 `json:"version"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *PlanEventData) UnmarshalJSON(data []byte) error {
	type plain PlanEventData
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "PlanEventData", "created_at", "currency", "name", "plan_id", "plan_type", "status", "version")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "created_at", "currency", "description", "name", "plan_id", "plan_type", "status", "version")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v PlanEventData) MarshalJSON() ([]byte, error) {
	type plain PlanEventData
	return marshalWithExtra(plain(v), v.ExtraFields)
}
