// Code generated by perseid. DO NOT EDIT.

package meteroid_test

import (
	"testing"

	"github.com/meteroid-oss/meteroid-go"
)

func TestPlans_ListPlanVersionEntitlements(t *testing.T) {
	client, requests := mock(200, "application/json", `{"data":[{"feature":{"code":"sample","id":"feature_id_53","name":"sample"},"value":{"type":"BOOLEAN","enabled":false}}]}`)
	call(t, client.Plans().ListPlanVersionEntitlements, "plan_version_id")
	expect(t, requests, "GET /api/v1/plan-versions/plan_version_id/entitlements")
}

func TestPlans_CreatePlanVersionEntitlement(t *testing.T) {
	client, requests := mock(200, "application/json", `{"data":[{"created_at":"2023-12-31T23:59:59.999-05:30","feature_id":"feature_id_39","id":"entitlement_id_2","updated_at":"2024-03-15T10:30:45.123+02:00","value":{"type":"BOOLEAN","enabled":false}}]}`)
	call(t, client.Plans().CreatePlanVersionEntitlement, "plan_version_id", decode[meteroid.CreateEntitlementsRequest](t, `{"entitlements":[{"feature_id":"feature_id_9","value":{"type":"BOOLEAN","enabled":false}}]}`))
	expect(t, requests, "POST /api/v1/plan-versions/plan_version_id/entitlements")
}

func TestPlans_List(t *testing.T) {
	client, requests := mock(200, "application/json", `{"data":[{"available_parameters":{},"created_at":"2024-03-15T10:30:45.123+02:00","currency":"sample","id":"plan_id_78","name":"sample","net_terms":-2147483648,"plan_type":"FREE","price_components":[{"id":"price_component_id_82","name":"sample"}],"product_family":{"id":"product_family_id_59","name":"sample"},"status":"INACTIVE","tax_inclusive":true,"version":-2147483648,"version_id":"plan_version_id_92"}],"pagination_meta":{"page":-123456789,"per_page":-123456789,"total_items":-9007199254740993,"total_pages":123456789}}`)
	call(t, client.Plans().List, nil)
	expect(t, requests, "GET /api/v1/plans")
}

func TestPlans_Create(t *testing.T) {
	client, requests := mock(200, "application/json", `{"available_parameters":{},"created_at":"2023-12-31T23:59:59.999-05:30","currency":"sample","id":"plan_id_13","name":"sample","net_terms":2147483647,"plan_type":"FREE","price_components":[{"id":"price_component_id_38","name":"sample"}],"product_family":{"id":"product_family_id_66","name":"sample"},"status":"ARCHIVED","tax_inclusive":false,"version":123456789,"version_id":"plan_version_id_84"}`)
	call(t, client.Plans().Create, decode[meteroid.CreatePlanRequest](t, `{"components":[{"fee":{"type":"RATE","rates":[{"price":"-0.000123","term":"ANNUAL"}]},"name":"sample"}],"currency":"sample","name":"sample","plan_type":"CUSTOM","product_family_id":"product_family_id_99","status":"ACTIVE"}`))
	expect(t, requests, "POST /api/v1/plans")
}

func TestPlans_UpdateVersionMinimum(t *testing.T) {
	client, requests := mock(200, "application/json", `{"amount":"sample","scope":{"type":"all_components"}}`)
	call(t, client.Plans().UpdateVersionMinimum, "plan_version_id", decode[meteroid.MinimumCommitment](t, `{"amount":"sample","scope":{"type":"all_components"}}`))
	expect(t, requests, "PUT /api/v1/plans/versions/plan_version_id/minimum")
}

func TestPlans_DeleteVersionMinimum(t *testing.T) {
	client, requests := mock(204, "", ``)
	call(t, client.Plans().DeleteVersionMinimum, "plan_version_id")
	expect(t, requests, "DELETE /api/v1/plans/versions/plan_version_id/minimum")
}

func TestPlans_Retrieve(t *testing.T) {
	client, requests := mock(200, "application/json", `{"available_parameters":{},"created_at":"2023-12-31T23:59:59.999-05:30","currency":"sample","id":"plan_id_13","name":"sample","net_terms":2147483647,"plan_type":"FREE","price_components":[{"id":"price_component_id_38","name":"sample"}],"product_family":{"id":"product_family_id_66","name":"sample"},"status":"ARCHIVED","tax_inclusive":false,"version":123456789,"version_id":"plan_version_id_84"}`)
	call(t, client.Plans().Retrieve, "plan_id", nil)
	expect(t, requests, "GET /api/v1/plans/plan_id")
}

func TestPlans_Replace(t *testing.T) {
	client, requests := mock(200, "application/json", `{"available_parameters":{},"created_at":"2023-12-31T23:59:59.999-05:30","currency":"sample","id":"plan_id_13","name":"sample","net_terms":2147483647,"plan_type":"FREE","price_components":[{"id":"price_component_id_38","name":"sample"}],"product_family":{"id":"product_family_id_66","name":"sample"},"status":"ARCHIVED","tax_inclusive":false,"version":123456789,"version_id":"plan_version_id_84"}`)
	call(t, client.Plans().Replace, "plan_id", decode[meteroid.ReplacePlanRequest](t, `{"components":[{"fee":{"type":"RATE","rates":[{"price":"-0.000123","term":"ANNUAL"}]},"name":"sample"}],"currency":"sample","name":"sample"}`))
	expect(t, requests, "PUT /api/v1/plans/plan_id")
}

func TestPlans_Update(t *testing.T) {
	client, requests := mock(200, "application/json", `{"available_parameters":{},"created_at":"2023-12-31T23:59:59.999-05:30","currency":"sample","id":"plan_id_13","name":"sample","net_terms":2147483647,"plan_type":"FREE","price_components":[{"id":"price_component_id_38","name":"sample"}],"product_family":{"id":"product_family_id_66","name":"sample"},"status":"ARCHIVED","tax_inclusive":false,"version":123456789,"version_id":"plan_version_id_84"}`)
	call(t, client.Plans().Update, "plan_id", decode[meteroid.PatchPlanRequest](t, `{}`))
	expect(t, requests, "PATCH /api/v1/plans/plan_id")
}

func TestPlans_Archive(t *testing.T) {
	client, requests := mock(204, "", ``)
	call(t, client.Plans().Archive, "plan_id")
	expect(t, requests, "POST /api/v1/plans/plan_id/archive")
}

func TestPlans_Publish(t *testing.T) {
	client, requests := mock(200, "application/json", `{"available_parameters":{},"created_at":"2023-12-31T23:59:59.999-05:30","currency":"sample","id":"plan_id_13","name":"sample","net_terms":2147483647,"plan_type":"FREE","price_components":[{"id":"price_component_id_38","name":"sample"}],"product_family":{"id":"product_family_id_66","name":"sample"},"status":"ARCHIVED","tax_inclusive":false,"version":123456789,"version_id":"plan_version_id_84"}`)
	call(t, client.Plans().Publish, "plan_id")
	expect(t, requests, "POST /api/v1/plans/plan_id/publish")
}

func TestPlans_Unarchive(t *testing.T) {
	client, requests := mock(204, "", ``)
	call(t, client.Plans().Unarchive, "plan_id")
	expect(t, requests, "POST /api/v1/plans/plan_id/unarchive")
}

func TestPlans_ListVersions(t *testing.T) {
	client, requests := mock(200, "application/json", `{"data":[{"created_at":"2023-12-31T23:59:59.999-05:30","currency":"sample","id":"plan_version_id_2","is_draft":true,"version":-2147483648}],"pagination_meta":{"page":-123456789,"per_page":-123456789,"total_items":-9007199254740993,"total_pages":123456789}}`)
	call(t, client.Plans().ListVersions, "plan_id", nil)
	expect(t, requests, "GET /api/v1/plans/plan_id/versions")
}
