// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// PriceComponentInput is the PriceComponentInput object of the Meteroid API.
type PriceComponentInput struct {
	Fee Fee `json:"fee"`

	Name string `json:"name"`

	ProductID *ProductID `json:"product_id,omitempty"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *PriceComponentInput) UnmarshalJSON(data []byte) error {
	type plain PriceComponentInput
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "PriceComponentInput", "fee", "name")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "fee", "name", "product_id")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v PriceComponentInput) MarshalJSON() ([]byte, error) {
	type plain PriceComponentInput
	return marshalWithExtra(plain(v), v.ExtraFields)
}
