// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// PriceComponent is the PriceComponent object of the Meteroid API.
type PriceComponent struct {
	Fee *Fee `json:"fee,omitempty"`

	ID PriceComponentID `json:"id"`

	Name string `json:"name"`

	ProductID *ProductID `json:"product_id,omitempty"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *PriceComponent) UnmarshalJSON(data []byte) error {
	type plain PriceComponent
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "fee", "id", "name", "product_id")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v PriceComponent) MarshalJSON() ([]byte, error) {
	type plain PriceComponent
	return marshalWithExtra(plain(v), v.ExtraFields)
}
