// Code generated by perseid. DO NOT EDIT.

package meteroid

import (
	"encoding/json"
	"time"
)

// Product is the Product object of the Meteroid API.
type Product struct {
	// RFC 3339 timestamp.
	ArchivedAt *time.Time `json:"archived_at,omitempty"`

	Catalog bool `json:"catalog"`

	// RFC 3339 timestamp.
	CreatedAt time.Time `json:"created_at"`

	Description *string `json:"description,omitempty"`

	FeeStructure ProductFeeStructure `json:"fee_structure"`

	FeeType ProductFeeTypeEnum `json:"fee_type"`

	ID ProductID `json:"id"`

	Name string `json:"name"`

	ProductFamilyID ProductFamilyID `json:"product_family_id"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *Product) UnmarshalJSON(data []byte) error {
	type plain Product
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "archived_at", "catalog", "created_at", "description", "fee_structure", "fee_type", "id", "name", "product_family_id")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v Product) MarshalJSON() ([]byte, error) {
	type plain Product
	return marshalWithExtra(plain(v), v.ExtraFields)
}
