// Code generated by perseid. DO NOT EDIT.

package meteroid

import (
	"context"
	"encoding/json"
	"net/http"
)

// ProductFamiliesListOptions carries the optional query and header parameters of
// [ProductFamilies.List]. Leave a field nil to omit it.
type ProductFamiliesListOptions struct {
	// Sort order. Format: `column.direction`. Allowed columns: `name`, `created_at`. Direction: `asc` or `desc`. Default: `created_at.desc`.
	OrderBy *string

	// Page number (0-indexed)
	Page *int32

	// Number of items per page
	PerPage *int32

	Search *string
}

// ProductFamilies groups the product families operations of the Meteroid API.
type ProductFamilies struct {
	client *Client
}

// fetchList sends GET /api/v1/product_families and decodes the response, for [ProductFamilies.List].
func (a *ProductFamilies) fetchList(ctx context.Context, options *ProductFamiliesListOptions, opts ...RequestOption) (*ProductFamilyListResponse, error) {
	req := newRequest(http.MethodGet, "/api/v1/product_families", opts)
	req.errors = errorSchemas{
		"429": errorSchema[RestErrorResponse],
	}
	if options != nil && options.OrderBy != nil {
		req.SetQueryParam("order_by", *options.OrderBy)
	}
	if options != nil && options.Page != nil {
		req.SetQueryParam("page", formatInt(int64(*options.Page)))
	}
	if options != nil && options.PerPage != nil {
		req.SetQueryParam("per_page", formatInt(int64(*options.PerPage)))
	}
	if options != nil && options.Search != nil {
		req.SetQueryParam("search", *options.Search)
	}
	var out ProductFamilyListResponse
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// ProductFamiliesListPage is a page of [ProductFamilies.List]. It embeds the
// decoded [ProductFamilyListResponse], promoting its fields, with the Items of the page; a field
// named like a page member stays reachable through the embedded ProductFamilyListResponse.
type ProductFamiliesListPage struct {
	ProductFamilyListResponse

	// Items holds the items of this page.
	Items []ProductFamily

	next func(ctx context.Context) (*ProductFamiliesListPage, error)
}

// HasNextPage reports whether another page follows this one.
func (p *ProductFamiliesListPage) HasNextPage() bool {
	return p != nil && p.next != nil
}

// NextPage fetches the page after this one. It returns nil and no error after
// the last page.
func (p *ProductFamiliesListPage) NextPage(ctx context.Context) (*ProductFamiliesListPage, error) {
	if !p.HasNextPage() {
		return nil, nil
	}
	return p.next(ctx)
}

// MarshalJSON encodes the ProductFamilyListResponse of the page, as received.
func (p ProductFamiliesListPage) MarshalJSON() ([]byte, error) {
	return json.Marshal(&p.ProductFamilyListResponse)
}

func (p *ProductFamiliesListPage) pageItems() []ProductFamily { return p.Items }

// List product families
//
// [ProductFamilies.ListAutoPaging] iterates over every item instead.
func (a *ProductFamilies) List(ctx context.Context, options *ProductFamiliesListOptions, opts ...RequestOption) (*ProductFamiliesListPage, error) {
	var params ProductFamiliesListOptions
	if options != nil {
		params = *options
	}
	resp, err := a.fetchList(ctx, &params, opts...)
	if err != nil {
		return nil, err
	}
	page := &ProductFamiliesListPage{ProductFamilyListResponse: *resp, Items: resp.Data}
	if len(page.Items) == 0 {
		return page, nil
	}
	current := int32(0)
	if params.Page != nil {
		current = *params.Page
	}
	if reached(current+1, resp.PaginationMeta.TotalPages) {
		return page, nil
	}
	next := current + 1
	params.Page = &next
	page.next = func(ctx context.Context) (*ProductFamiliesListPage, error) {
		return a.List(ctx, &params, opts...)
	}
	return page, nil
}

// ListAutoPaging iterates over every item of [ProductFamilies.List], fetching
// further pages on demand.
func (a *ProductFamilies) ListAutoPaging(ctx context.Context, options *ProductFamiliesListOptions, opts ...RequestOption) *AutoPager[ProductFamily] {
	return newAutoPager[ProductFamily](ctx, func(ctx context.Context) (*ProductFamiliesListPage, error) {
		return a.List(ctx, options, opts...)
	})
}

// Create product family
func (a *ProductFamilies) Create(ctx context.Context, productFamilyCreateRequest ProductFamilyCreateRequest, opts ...RequestOption) (*ProductFamily, error) {
	req := newRequest(http.MethodPost, "/api/v1/product_families", opts)
	req.errors = errorSchemas{
		"429": errorSchema[RestErrorResponse],
	}
	req.SetJSONBody(productFamilyCreateRequest)
	var out ProductFamily
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Retrieve sends GET /api/v1/product_families/{id_or_alias}.
//
// # Get product family
//
// Retrieve a single product family by ID or alias.
func (a *ProductFamilies) Retrieve(ctx context.Context, idOrAlias string, opts ...RequestOption) (*ProductFamily, error) {
	req := newRequest(http.MethodGet, "/api/v1/product_families/{id_or_alias}", opts)
	req.SetPathParam("id_or_alias", idOrAlias)
	req.errors = errorSchemas{
		"429": errorSchema[RestErrorResponse],
	}
	var out ProductFamily
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
