// Code generated by perseid. DO NOT EDIT.

package meteroid

import (
	"context"
	"encoding/json"
	"net/http"
)

// ProductsListOptions carries the optional query and header parameters of
// [Products.List]. Leave a field nil to omit it.
type ProductsListOptions struct {
	ProductFamilyID *ProductFamilyID

	Search *string

	// Sort order. Format: `column.direction`. Allowed columns: `name`, `created_at`. Direction: `asc` or `desc`. Default: `name.asc`.
	OrderBy *string

	// Page number (0-indexed)
	Page *int32

	// Number of items per page
	PerPage *int32
}

// Products groups the products operations of the Meteroid API.
type Products struct {
	client *Client
}

// fetchList sends GET /api/v1/products and decodes the response, for [Products.List].
func (a *Products) fetchList(ctx context.Context, options *ProductsListOptions, opts ...RequestOption) (*ProductListResponse, error) {
	req := newRequest(http.MethodGet, "/api/v1/products", opts)
	req.errors = errorSchemas{
		"401": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
	}
	if options != nil && options.ProductFamilyID != nil {
		req.SetQueryParam("product_family_id", formatValue(*options.ProductFamilyID))
	}
	if options != nil && options.Search != nil {
		req.SetQueryParam("search", *options.Search)
	}
	if options != nil && options.OrderBy != nil {
		req.SetQueryParam("order_by", *options.OrderBy)
	}
	if options != nil && options.Page != nil {
		req.SetQueryParam("page", formatInt(int64(*options.Page)))
	}
	if options != nil && options.PerPage != nil {
		req.SetQueryParam("per_page", formatInt(int64(*options.PerPage)))
	}
	var out ProductListResponse
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// ProductsListPage is a page of [Products.List]. It embeds the
// decoded [ProductListResponse], promoting its fields, with the Items of the page; a field
// named like a page member stays reachable through the embedded ProductListResponse.
type ProductsListPage struct {
	ProductListResponse

	// Items holds the items of this page.
	Items []Product

	next func(ctx context.Context) (*ProductsListPage, error)
}

// HasNextPage reports whether another page follows this one.
func (p *ProductsListPage) HasNextPage() bool {
	return p != nil && p.next != nil
}

// NextPage fetches the page after this one. It returns nil and no error after
// the last page.
func (p *ProductsListPage) NextPage(ctx context.Context) (*ProductsListPage, error) {
	if !p.HasNextPage() {
		return nil, nil
	}
	return p.next(ctx)
}

// MarshalJSON encodes the ProductListResponse of the page, as received.
func (p ProductsListPage) MarshalJSON() ([]byte, error) {
	return json.Marshal(&p.ProductListResponse)
}

func (p *ProductsListPage) pageItems() []Product { return p.Items }

// List products
//
// [Products.ListAutoPaging] iterates over every item instead.
func (a *Products) List(ctx context.Context, options *ProductsListOptions, opts ...RequestOption) (*ProductsListPage, error) {
	var params ProductsListOptions
	if options != nil {
		params = *options
	}
	resp, err := a.fetchList(ctx, &params, opts...)
	if err != nil {
		return nil, err
	}
	page := &ProductsListPage{ProductListResponse: *resp, Items: resp.Data}
	if len(page.Items) == 0 {
		return page, nil
	}
	current := int32(0)
	if params.Page != nil {
		current = *params.Page
	}
	if reached(current+1, resp.PaginationMeta.TotalPages) {
		return page, nil
	}
	next := current + 1
	params.Page = &next
	page.next = func(ctx context.Context) (*ProductsListPage, error) {
		return a.List(ctx, &params, opts...)
	}
	return page, nil
}

// ListAutoPaging iterates over every item of [Products.List], fetching
// further pages on demand.
func (a *Products) ListAutoPaging(ctx context.Context, options *ProductsListOptions, opts ...RequestOption) *AutoPager[Product] {
	return newAutoPager[Product](ctx, func(ctx context.Context) (*ProductsListPage, error) {
		return a.List(ctx, options, opts...)
	})
}

// Create a product
func (a *Products) Create(ctx context.Context, createProductRequest CreateProductRequest, opts ...RequestOption) (*Product, error) {
	req := newRequest(http.MethodPost, "/api/v1/products", opts)
	req.errors = errorSchemas{
		"400": errorSchema[RestErrorResponse],
		"401": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
	}
	req.SetJSONBody(createProductRequest)
	var out Product
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Retrieve sends GET /api/v1/products/{product_id}.
//
// Get product details
func (a *Products) Retrieve(ctx context.Context, productID string, opts ...RequestOption) (*Product, error) {
	req := newRequest(http.MethodGet, "/api/v1/products/{product_id}", opts)
	req.SetPathParam("product_id", productID)
	req.errors = errorSchemas{
		"401": errorSchema[RestErrorResponse],
		"404": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
	}
	var out Product
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Update a product
//
// Partially update product fields. The fee_type is immutable and cannot be changed.
func (a *Products) Update(ctx context.Context, productID string, updateProductRequest UpdateProductRequest, opts ...RequestOption) (*Product, error) {
	req := newRequest(http.MethodPatch, "/api/v1/products/{product_id}", opts)
	req.SetPathParam("product_id", productID)
	req.errors = errorSchemas{
		"400": errorSchema[RestErrorResponse],
		"401": errorSchema[RestErrorResponse],
		"404": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
	}
	req.SetJSONBody(updateProductRequest)
	var out Product
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Archive a product
func (a *Products) Archive(ctx context.Context, productID string, opts ...RequestOption) error {
	req := newRequest(http.MethodPost, "/api/v1/products/{product_id}/archive", opts)
	req.SetPathParam("product_id", productID)
	req.errors = errorSchemas{
		"401": errorSchema[RestErrorResponse],
		"404": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
	}
	return a.client.execute(ctx, req, nil)
}

// ListEntitlements sends GET /api/v1/products/{product_id}/entitlements.
//
// List product entitlements
func (a *Products) ListEntitlements(ctx context.Context, productID string, opts ...RequestOption) (*ResolvedEntitlementListResponse, error) {
	req := newRequest(http.MethodGet, "/api/v1/products/{product_id}/entitlements", opts)
	req.SetPathParam("product_id", productID)
	req.errors = errorSchemas{
		"401": errorSchema[RestErrorResponse],
		"404": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
	}
	var out ResolvedEntitlementListResponse
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateEntitlement sends POST /api/v1/products/{product_id}/entitlements.
//
// # Create product entitlements
//
// A product has no entitlement rows of its own: its entitlements are the feature-level
// defaults of the features scoped to it, which is what `GET` on this path resolves. Every
// spec must therefore target a feature belonging to `product_id`. Features that already
// carry a default entitlement are skipped.
//
// Specs are validated up front, but the writes are not atomic: each feature is written on
// its own, so a failure part-way can leave earlier specs committed. Retrying is safe.
func (a *Products) CreateEntitlement(ctx context.Context, productID string, createEntitlementsRequest CreateEntitlementsRequest, opts ...RequestOption) (*EntitlementListResponse, error) {
	req := newRequest(http.MethodPost, "/api/v1/products/{product_id}/entitlements", opts)
	req.SetPathParam("product_id", productID)
	req.errors = errorSchemas{
		"400": errorSchema[RestErrorResponse],
		"401": errorSchema[RestErrorResponse],
		"404": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
	}
	req.SetJSONBody(createEntitlementsRequest)
	var out EntitlementListResponse
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Unarchive a product
func (a *Products) Unarchive(ctx context.Context, productID string, opts ...RequestOption) error {
	req := newRequest(http.MethodPost, "/api/v1/products/{product_id}/unarchive", opts)
	req.SetPathParam("product_id", productID)
	req.errors = errorSchemas{
		"401": errorSchema[RestErrorResponse],
		"404": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
	}
	return a.client.execute(ctx, req, nil)
}
