// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// ProductFamilyListResponse is the ProductFamilyListResponse object of the Meteroid API.
type ProductFamilyListResponse struct {
	Data RequiredSlice[ProductFamily] `json:"data"`

	PaginationMeta PaginationResponse `json:"pagination_meta"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *ProductFamilyListResponse) UnmarshalJSON(data []byte) error {
	type plain ProductFamilyListResponse
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "data", "pagination_meta")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v ProductFamilyListResponse) MarshalJSON() ([]byte, error) {
	type plain ProductFamilyListResponse
	return marshalWithExtra(plain(v), v.ExtraFields)
}
