// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// ProductFamilyCreateRequest is the ProductFamilyCreateRequest object of the Meteroid API.
type ProductFamilyCreateRequest struct {
	Name string `json:"name"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *ProductFamilyCreateRequest) UnmarshalJSON(data []byte) error {
	type plain ProductFamilyCreateRequest
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "name")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v ProductFamilyCreateRequest) MarshalJSON() ([]byte, error) {
	type plain ProductFamilyCreateRequest
	return marshalWithExtra(plain(v), v.ExtraFields)
}
