// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// ProductsScope is the ProductsScope object of the Meteroid API.
//
// Only lines for the listed products count. A product is the identity shared by plan
// components, overrides and ad-hoc extras, so a subscription's billed set is matched uniformly.
type ProductsScope struct {
	ProductIDs RequiredSlice[string] `json:"product_ids"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *ProductsScope) UnmarshalJSON(data []byte) error {
	type plain ProductsScope
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "product_ids")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v ProductsScope) MarshalJSON() ([]byte, error) {
	type plain ProductsScope
	return marshalWithExtra(plain(v), v.ExtraFields)
}
