// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// PropertyConfig is the PropertyConfig object of the Meteroid API.
//
// Type-specific configuration. Only the fields relevant to `property_type` are interpreted.
type PropertyConfig struct {
	Max *float64 `json:"max,omitempty"`

	// Maximum length for `TEXT`.
	MaxLength *int32 `json:"max_length,omitempty"`

	// Inclusive numeric bounds for `NUMBER`.
	Min *float64 `json:"min,omitempty"`

	// Allowed choices for `SINGLE_SELECT` / `MULTI_SELECT`.
	Options []SelectOption `json:"options,omitempty"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *PropertyConfig) UnmarshalJSON(data []byte) error {
	type plain PropertyConfig
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "max", "max_length", "min", "options")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v PropertyConfig) MarshalJSON() ([]byte, error) {
	type plain PropertyConfig
	return marshalWithExtra(plain(v), v.ExtraFields)
}
