// Code generated by perseid. DO NOT EDIT.

package meteroid

import (
	"encoding/json"
	"time"
)

// QuoteEvent is the QuoteEvent object of the Meteroid API.
type QuoteEvent struct {
	CustomerID CustomerID `json:"customer_id"`

	QuoteID QuoteID `json:"quote_id"`

	SubscriptionID *SubscriptionID `json:"subscription_id,omitempty"`

	ID EventID `json:"id"`

	// RFC 3339 timestamp.
	Timestamp time.Time `json:"timestamp"`

	Type EventType `json:"type"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *QuoteEvent) UnmarshalJSON(data []byte) error {
	type plain QuoteEvent
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "customer_id", "quote_id", "subscription_id", "id", "timestamp", "type")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v QuoteEvent) MarshalJSON() ([]byte, error) {
	type plain QuoteEvent
	return marshalWithExtra(plain(v), v.ExtraFields)
}
