// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// QuoteEventData is the QuoteEventData object of the Meteroid API.
type QuoteEventData struct {
	CustomerID CustomerID `json:"customer_id"`

	QuoteID QuoteID `json:"quote_id"`

	SubscriptionID *SubscriptionID `json:"subscription_id,omitempty"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *QuoteEventData) UnmarshalJSON(data []byte) error {
	type plain QuoteEventData
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "QuoteEventData", "customer_id", "quote_id")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "customer_id", "quote_id", "subscription_id")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v QuoteEventData) MarshalJSON() ([]byte, error) {
	type plain QuoteEventData
	return marshalWithExtra(plain(v), v.ExtraFields)
}
