// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// RateFee is the RateFee object of the Meteroid API.
type RateFee struct {
	Rate string `json:"rate"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *RateFee) UnmarshalJSON(data []byte) error {
	type plain RateFee
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "rate")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v RateFee) MarshalJSON() ([]byte, error) {
	type plain RateFee
	return marshalWithExtra(plain(v), v.ExtraFields)
}
