// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// RecurringFee is the RecurringFee object of the Meteroid API.
type RecurringFee struct {
	BillingType BillingTypeEnum `json:"billing_type"`

	Quantity int32 `json:"quantity"`

	Rate string `json:"rate"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *RecurringFee) UnmarshalJSON(data []byte) error {
	type plain RecurringFee
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "RecurringFee", "billing_type", "quantity", "rate")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "billing_type", "quantity", "rate")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v RecurringFee) MarshalJSON() ([]byte, error) {
	type plain RecurringFee
	return marshalWithExtra(plain(v), v.ExtraFields)
}
