// Code generated by perseid. DO NOT EDIT.

package meteroid

import (
	"encoding/json"
	"time"
)

// RefundEventData is the RefundEventData object of the Meteroid API.
//
// A refund row, or the payment that failed or was clawed back — the same shape the REST invoice
// exposes as a transaction. `reversal_reason` is deliberately absent: it is free provider text and is
// not carried on the outbox event.
type RefundEventData struct {
	Amount int64 `json:"amount"`

	AmountRefunded int64 `json:"amount_refunded"`

	AmountReversed int64 `json:"amount_reversed"`

	CreditNoteID *CreditNoteID `json:"credit_note_id,omitempty"`

	Currency string `json:"currency"`

	DeclineKind *DeclineKind `json:"decline_kind,omitempty"`

	Error *string `json:"error,omitempty"`

	InvoiceID *InvoiceID `json:"invoice_id,omitempty"`

	ParentTransactionID *PaymentTransactionID `json:"parent_transaction_id,omitempty"`

	PaymentType PaymentTypeEnum `json:"payment_type"`

	// RFC 3339 timestamp.
	ProcessedAt *time.Time `json:"processed_at,omitempty"`

	ProviderTransactionID *string `json:"provider_transaction_id,omitempty"`

	RefundMode *RefundMode `json:"refund_mode,omitempty"`

	ReversalKind *ReversalKind `json:"reversal_kind,omitempty"`

	Status PaymentStatusEnum `json:"status"`

	TransactionID PaymentTransactionID `json:"transaction_id"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *RefundEventData) UnmarshalJSON(data []byte) error {
	type plain RefundEventData
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "RefundEventData", "amount", "amount_refunded", "amount_reversed", "currency", "payment_type", "status", "transaction_id")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "amount", "amount_refunded", "amount_reversed", "credit_note_id", "currency", "decline_kind", "error", "invoice_id", "parent_transaction_id", "payment_type", "processed_at", "provider_transaction_id", "refund_mode", "reversal_kind", "status", "transaction_id")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v RefundEventData) MarshalJSON() ([]byte, error) {
	type plain RefundEventData
	return marshalWithExtra(plain(v), v.ExtraFields)
}
