// Code generated by perseid. DO NOT EDIT.

package meteroid

// RefundMode is one of [AllRefundModeValues], or a value this SDK version
// does not know.
//
// How a voluntary refund was issued: through the provider, or recorded after a wire or cash
// movement made outside Meteroid.
type RefundMode string

// Known values of RefundMode.
//
// The API may add new values over time; unknown values round-trip unchanged.
const (
	RefundModeOnline  RefundMode = "ONLINE"
	RefundModeOffline RefundMode = "OFFLINE"
)

// AllRefundModeValues lists every RefundMode value known to this SDK version.
var AllRefundModeValues = []RefundMode{
	RefundModeOnline,
	RefundModeOffline,
}

// String returns the wire representation of the value.
func (e RefundMode) String() string {
	return string(e)
}

// IsKnown reports whether the value is one this SDK version knows about.
func (e RefundMode) IsKnown() bool {
	for _, known := range AllRefundModeValues {
		if e == known {
			return true
		}
	}
	return false
}
