// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// ReplacePlanRequest is the ReplacePlanRequest object of the Meteroid API.
type ReplacePlanRequest struct {
	AddOns []PlanAddOnInput `json:"add_ons,omitempty"`

	Billing *BillingConfig `json:"billing,omitempty"`

	Components RequiredSlice[PriceComponentInput] `json:"components"`

	Currency string `json:"currency"`

	Description *string `json:"description,omitempty"`

	// Entitlements to attach to this plan's version. Replacing a published plan creates a
	// new version, and entitlements belong to a version, so passing them here keeps them
	// attached to whichever version the call produces.
	Entitlements []EntitlementSpecRequest `json:"entitlements,omitempty"`

	MinimumCommitment *MinimumCommitmentInput `json:"minimum_commitment,omitempty"`

	Name string `json:"name"`

	Status *PlanStatusEnum `json:"status,omitempty"`

	// The plan's amounts are quoted tax-included ("9.99 incl. VAT"): tax is carved out of
	// them at invoice time instead of being added on top, so the customer pays the quoted
	// price whatever rate applies. A customer who bears no tax (reverse charge, exempt,
	// export) still pays it in full. Defaults to `false`.
	TaxInclusive *bool `json:"tax_inclusive,omitempty"`

	Trial *TrialConfig `json:"trial,omitempty"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *ReplacePlanRequest) UnmarshalJSON(data []byte) error {
	type plain ReplacePlanRequest
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "add_ons", "billing", "components", "currency", "description", "entitlements", "minimum_commitment", "name", "status", "tax_inclusive", "trial")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v ReplacePlanRequest) MarshalJSON() ([]byte, error) {
	type plain ReplacePlanRequest
	return marshalWithExtra(plain(v), v.ExtraFields)
}
