// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// ResolvedEntitlementListResponse is the ResolvedEntitlementListResponse object of the Meteroid API.
type ResolvedEntitlementListResponse struct {
	Data RequiredSlice[ResolvedEntitlement] `json:"data"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *ResolvedEntitlementListResponse) UnmarshalJSON(data []byte) error {
	type plain ResolvedEntitlementListResponse
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "ResolvedEntitlementListResponse", "data")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "data")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v ResolvedEntitlementListResponse) MarshalJSON() ([]byte, error) {
	type plain ResolvedEntitlementListResponse
	return marshalWithExtra(plain(v), v.ExtraFields)
}
