// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// ResolvedEntitlement is the ResolvedEntitlement object of the Meteroid API.
//
// Merged entitlement value for a feature across the priority hierarchy, without usage data.
type ResolvedEntitlement struct {
	Feature FeatureRef `json:"feature"`

	Value ResolvedEntitlementValue `json:"value"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *ResolvedEntitlement) UnmarshalJSON(data []byte) error {
	type plain ResolvedEntitlement
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "ResolvedEntitlement", "feature", "value")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "feature", "value")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v ResolvedEntitlement) MarshalJSON() ([]byte, error) {
	type plain ResolvedEntitlement
	return marshalWithExtra(plain(v), v.ExtraFields)
}
