// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// RestErrorResponse is the RestErrorResponse object of the Meteroid API.
type RestErrorResponse struct {
	Code ErrorCode `json:"code"`

	Message string `json:"message"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *RestErrorResponse) UnmarshalJSON(data []byte) error {
	type plain RestErrorResponse
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "RestErrorResponse", "code", "message")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "code", "message")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v RestErrorResponse) MarshalJSON() ([]byte, error) {
	type plain RestErrorResponse
	return marshalWithExtra(plain(v), v.ExtraFields)
}
