// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// RotatedSecret is the RotatedSecret object of the Meteroid API.
//
// Result of rotating a client secret
type RotatedSecret struct {
	ClientSecret string `json:"client_secret"`

	ClientSecretHint string `json:"client_secret_hint"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *RotatedSecret) UnmarshalJSON(data []byte) error {
	type plain RotatedSecret
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "client_secret", "client_secret_hint")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v RotatedSecret) MarshalJSON() ([]byte, error) {
	type plain RotatedSecret
	return marshalWithExtra(plain(v), v.ExtraFields)
}
