// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// SlidingWindowResetPeriod is the SlidingWindowResetPeriod object of the Meteroid API.
//
// Always ends at now — e.g. 30 days means the last 30 days, old usage drops off automatically.
type SlidingWindowResetPeriod struct {
	Interval int32 `json:"interval"`

	Unit CalendarUnit `json:"unit"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *SlidingWindowResetPeriod) UnmarshalJSON(data []byte) error {
	type plain SlidingWindowResetPeriod
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "interval", "unit")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v SlidingWindowResetPeriod) MarshalJSON() ([]byte, error) {
	type plain SlidingWindowResetPeriod
	return marshalWithExtra(plain(v), v.ExtraFields)
}
