// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// SlotFee is the SlotFee object of the Meteroid API.
type SlotFee struct {
	InitialSlots int32 `json:"initial_slots"`

	MaxSlots *int32 `json:"max_slots,omitempty"`

	MinSlots *int32 `json:"min_slots,omitempty"`

	Unit string `json:"unit"`

	UnitRate string `json:"unit_rate"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *SlotFee) UnmarshalJSON(data []byte) error {
	type plain SlotFee
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "initial_slots", "max_slots", "min_slots", "unit", "unit_rate")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v SlotFee) MarshalJSON() ([]byte, error) {
	type plain SlotFee
	return marshalWithExtra(plain(v), v.ExtraFields)
}
