// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// SlotFeeStructure is the SlotFeeStructure object of the Meteroid API.
type SlotFeeStructure struct {
	DowngradePolicy SlotDowngradePolicyEnum `json:"downgrade_policy"`

	SlotUnitName string `json:"slot_unit_name"`

	UpgradePolicy SlotUpgradePolicyEnum `json:"upgrade_policy"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *SlotFeeStructure) UnmarshalJSON(data []byte) error {
	type plain SlotFeeStructure
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "SlotFeeStructure", "downgrade_policy", "slot_unit_name", "upgrade_policy")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "downgrade_policy", "slot_unit_name", "upgrade_policy")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v SlotFeeStructure) MarshalJSON() ([]byte, error) {
	type plain SlotFeeStructure
	return marshalWithExtra(plain(v), v.ExtraFields)
}
