// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// SlotPlanFee is the SlotPlanFee object of the Meteroid API.
//
// Slot-based fee (e.g., per-seat pricing)
type SlotPlanFee struct {
	MinimumCount *int32 `json:"minimum_count,omitempty"`

	Quota *int32 `json:"quota,omitempty"`

	Rates RequiredSlice[TermRate] `json:"rates"`

	SlotUnitName string `json:"slot_unit_name"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *SlotPlanFee) UnmarshalJSON(data []byte) error {
	type plain SlotPlanFee
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "minimum_count", "quota", "rates", "slot_unit_name")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v SlotPlanFee) MarshalJSON() ([]byte, error) {
	type plain SlotPlanFee
	return marshalWithExtra(plain(v), v.ExtraFields)
}
