// Code generated by perseid. DO NOT EDIT.

package meteroid

import (
	"context"
	"encoding/json"
	"net/http"
)

// SubscriptionsListOptions carries the optional query and header parameters of
// [Subscriptions.List]. Leave a field nil to omit it.
type SubscriptionsListOptions struct {
	// Filter by customer ID or alias
	CustomerID *string

	PlanID *PlanID

	Statuses []SubscriptionStatusEnum

	// Sort order. Format: `column.direction`. Allowed columns: `customer_name`, `plan_name`, `mrr_cents`, `billing_start_date`, `end_date`, `status`, `created_at`. Direction: `asc` or `desc`. Default: `created_at.desc`.
	OrderBy *string

	// Page number (0-indexed)
	Page *int32

	// Number of items per page
	PerPage *int32
}

// Subscriptions groups the subscriptions operations of the Meteroid API.
type Subscriptions struct {
	client *Client
}

// fetchList sends GET /api/v1/subscriptions and decodes the response, for [Subscriptions.List].
func (a *Subscriptions) fetchList(ctx context.Context, options *SubscriptionsListOptions, opts ...RequestOption) (*SubscriptionListResponse, error) {
	req := newRequest(http.MethodGet, "/api/v1/subscriptions", opts)
	req.errors = errorSchemas{
		"401": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
		"500": errorSchema[RestErrorResponse],
	}
	if options != nil && options.CustomerID != nil {
		req.SetQueryParam("customer_id", *options.CustomerID)
	}
	if options != nil && options.PlanID != nil {
		req.SetQueryParam("plan_id", formatValue(*options.PlanID))
	}
	if options != nil && len(options.Statuses) > 0 {
		for _, item := range options.Statuses {
			req.AddQueryParam("statuses", formatValue(item))
		}
	}
	if options != nil && options.OrderBy != nil {
		req.SetQueryParam("order_by", *options.OrderBy)
	}
	if options != nil && options.Page != nil {
		req.SetQueryParam("page", formatInt(int64(*options.Page)))
	}
	if options != nil && options.PerPage != nil {
		req.SetQueryParam("per_page", formatInt(int64(*options.PerPage)))
	}
	var out SubscriptionListResponse
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// SubscriptionsListPage is a page of [Subscriptions.List]. It embeds the
// decoded [SubscriptionListResponse], promoting its fields, with the Items of the page; a field
// named like a page member stays reachable through the embedded SubscriptionListResponse.
type SubscriptionsListPage struct {
	SubscriptionListResponse

	// Items holds the items of this page.
	Items []Subscription

	next func(ctx context.Context) (*SubscriptionsListPage, error)
}

// HasNextPage reports whether another page follows this one.
func (p *SubscriptionsListPage) HasNextPage() bool {
	return p != nil && p.next != nil
}

// NextPage fetches the page after this one. It returns nil and no error after
// the last page.
func (p *SubscriptionsListPage) NextPage(ctx context.Context) (*SubscriptionsListPage, error) {
	if !p.HasNextPage() {
		return nil, nil
	}
	return p.next(ctx)
}

// MarshalJSON encodes the SubscriptionListResponse of the page, as received.
func (p SubscriptionsListPage) MarshalJSON() ([]byte, error) {
	return json.Marshal(&p.SubscriptionListResponse)
}

func (p *SubscriptionsListPage) pageItems() []Subscription { return p.Items }

// List subscriptions with optional filtering by customer or plan.
//
// [Subscriptions.ListAutoPaging] iterates over every item instead.
func (a *Subscriptions) List(ctx context.Context, options *SubscriptionsListOptions, opts ...RequestOption) (*SubscriptionsListPage, error) {
	var params SubscriptionsListOptions
	if options != nil {
		params = *options
	}
	resp, err := a.fetchList(ctx, &params, opts...)
	if err != nil {
		return nil, err
	}
	page := &SubscriptionsListPage{SubscriptionListResponse: *resp, Items: resp.Data}
	if len(page.Items) == 0 {
		return page, nil
	}
	current := int32(0)
	if params.Page != nil {
		current = *params.Page
	}
	if reached(current+1, resp.PaginationMeta.TotalPages) {
		return page, nil
	}
	next := current + 1
	params.Page = &next
	page.next = func(ctx context.Context) (*SubscriptionsListPage, error) {
		return a.List(ctx, &params, opts...)
	}
	return page, nil
}

// ListAutoPaging iterates over every item of [Subscriptions.List], fetching
// further pages on demand.
func (a *Subscriptions) ListAutoPaging(ctx context.Context, options *SubscriptionsListOptions, opts ...RequestOption) *AutoPager[Subscription] {
	return newAutoPager[Subscription](ctx, func(ctx context.Context) (*SubscriptionsListPage, error) {
		return a.List(ctx, options, opts...)
	})
}

// Create subscription
//
// Create a new subscription for a customer with a specific plan.
func (a *Subscriptions) Create(ctx context.Context, subscriptionCreateRequest SubscriptionCreateRequest, opts ...RequestOption) (*SubscriptionDetails, error) {
	req := newRequest(http.MethodPost, "/api/v1/subscriptions", opts)
	req.errors = errorSchemas{
		"400": errorSchema[RestErrorResponse],
		"401": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
		"500": errorSchema[RestErrorResponse],
	}
	req.SetJSONBody(subscriptionCreateRequest)
	var out SubscriptionDetails
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Retrieve sends GET /api/v1/subscriptions/{subscription_id}.
//
// # Get subscription details
//
// Retrieve detailed information about a subscription including price components and schedules.
func (a *Subscriptions) Retrieve(ctx context.Context, subscriptionID string, opts ...RequestOption) (*SubscriptionDetails, error) {
	req := newRequest(http.MethodGet, "/api/v1/subscriptions/{subscription_id}", opts)
	req.SetPathParam("subscription_id", subscriptionID)
	req.errors = errorSchemas{
		"401": errorSchema[RestErrorResponse],
		"404": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
		"500": errorSchema[RestErrorResponse],
	}
	var out SubscriptionDetails
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Update subscription settings like payment configuration, billing options, etc.
func (a *Subscriptions) Update(ctx context.Context, subscriptionID string, subscriptionUpdateRequest SubscriptionUpdateRequest, opts ...RequestOption) (*SubscriptionUpdateResponse, error) {
	req := newRequest(http.MethodPatch, "/api/v1/subscriptions/{subscription_id}", opts)
	req.SetPathParam("subscription_id", subscriptionID)
	req.errors = errorSchemas{
		"400": errorSchema[RestErrorResponse],
		"401": errorSchema[RestErrorResponse],
		"404": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
		"500": errorSchema[RestErrorResponse],
	}
	req.SetJSONBody(subscriptionUpdateRequest)
	var out SubscriptionUpdateResponse
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Cancel subscription
//
// Cancel a subscription either immediately or at the end of the billing period.
func (a *Subscriptions) Cancel(ctx context.Context, subscriptionID string, cancelSubscriptionRequest CancelSubscriptionRequest, opts ...RequestOption) (*CancelSubscriptionResponse, error) {
	req := newRequest(http.MethodPost, "/api/v1/subscriptions/{subscription_id}/cancel", opts)
	req.SetPathParam("subscription_id", subscriptionID)
	req.errors = errorSchemas{
		"401": errorSchema[RestErrorResponse],
		"404": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
		"500": errorSchema[RestErrorResponse],
	}
	req.SetJSONBody(cancelSubscriptionRequest)
	var out CancelSubscriptionResponse
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListEntitlements sends GET /api/v1/subscriptions/{subscription_id}/entitlements.
//
// List subscription entitlements
func (a *Subscriptions) ListEntitlements(ctx context.Context, subscriptionID string, opts ...RequestOption) (*EffectiveEntitlementListResponse, error) {
	req := newRequest(http.MethodGet, "/api/v1/subscriptions/{subscription_id}/entitlements", opts)
	req.SetPathParam("subscription_id", subscriptionID)
	req.errors = errorSchemas{
		"401": errorSchema[RestErrorResponse],
		"404": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
	}
	var out EffectiveEntitlementListResponse
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// RetrieveSummary sends GET /api/v1/subscriptions/{subscription_id}/summary.
//
// # Get subscription summary
//
// Retrieve a subscription without its components, add-ons, coupons and entitlements: the same
// shape as list items, for callers that only need status and billing dates.
func (a *Subscriptions) RetrieveSummary(ctx context.Context, subscriptionID string, opts ...RequestOption) (*Subscription, error) {
	req := newRequest(http.MethodGet, "/api/v1/subscriptions/{subscription_id}/summary", opts)
	req.SetPathParam("subscription_id", subscriptionID)
	req.errors = errorSchemas{
		"401": errorSchema[RestErrorResponse],
		"404": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
		"500": errorSchema[RestErrorResponse],
	}
	var out Subscription
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
