// Code generated by perseid. DO NOT EDIT.

package meteroid

import (
	"encoding/json"
	"time"
)

// SubscriptionCoupon is the SubscriptionCoupon object of the Meteroid API.
//
// Coupon as embedded in subscription details — a subset of the `Coupon` resource
// returned by the coupons API.
type SubscriptionCoupon struct {
	Code string `json:"code"`

	Description string `json:"description"`

	Disabled bool `json:"disabled"`

	Discount CouponDiscount `json:"discount"`

	// RFC 3339 timestamp.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`

	ID CouponID `json:"id"`

	RecurringValue *int32 `json:"recurring_value,omitempty"`

	RedemptionLimit *int32 `json:"redemption_limit,omitempty"`

	Reusable bool `json:"reusable"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *SubscriptionCoupon) UnmarshalJSON(data []byte) error {
	type plain SubscriptionCoupon
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "SubscriptionCoupon", "code", "description", "disabled", "discount", "id", "reusable")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "code", "description", "disabled", "discount", "expires_at", "id", "recurring_value", "redemption_limit", "reusable")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v SubscriptionCoupon) MarshalJSON() ([]byte, error) {
	type plain SubscriptionCoupon
	return marshalWithExtra(plain(v), v.ExtraFields)
}
