// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// SubscriptionListResponse is the SubscriptionListResponse object of the Meteroid API.
type SubscriptionListResponse struct {
	Data RequiredSlice[Subscription] `json:"data"`

	PaginationMeta PaginationResponse `json:"pagination_meta"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *SubscriptionListResponse) UnmarshalJSON(data []byte) error {
	type plain SubscriptionListResponse
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "SubscriptionListResponse", "data", "pagination_meta")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "data", "pagination_meta")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v SubscriptionListResponse) MarshalJSON() ([]byte, error) {
	type plain SubscriptionListResponse
	return marshalWithExtra(plain(v), v.ExtraFields)
}
