// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// SubscriptionUpdateRequest is the SubscriptionUpdateRequest object of the Meteroid API.
type SubscriptionUpdateRequest struct {
	// If false, invoices will stay in Draft until manually reviewed and finalized.
	AutoAdvanceInvoices *Nullable[bool] `json:"auto_advance_invoices,omitempty"`

	// Automatically try to charge the customer's configured payment method on finalize.
	ChargeAutomatically *Nullable[bool] `json:"charge_automatically,omitempty"`

	// Partial update of custom property values (merge; send a key with `null` to remove it).
	// Validated against the tenant's `SUBSCRIPTION` property definitions. Omit to leave unchanged.
	CustomProperties json.RawMessage `json:"custom_properties,omitempty"`

	// Default memo for invoices
	InvoiceMemo *Nullable[string] `json:"invoice_memo,omitempty"`

	// Payment terms in days (0 = due on issue)
	NetTerms *Nullable[int32] `json:"net_terms,omitempty"`

	PaymentMethodsConfig *Nullable[PaymentMethodsConfig] `json:"payment_methods_config,omitempty"`

	// Purchase order number
	PurchaseOrder *Nullable[string] `json:"purchase_order,omitempty"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *SubscriptionUpdateRequest) UnmarshalJSON(data []byte) error {
	type plain SubscriptionUpdateRequest
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "SubscriptionUpdateRequest")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "auto_advance_invoices", "charge_automatically", "custom_properties", "invoice_memo", "net_terms", "payment_methods_config", "purchase_order")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v SubscriptionUpdateRequest) MarshalJSON() ([]byte, error) {
	type plain SubscriptionUpdateRequest
	return marshalWithExtra(plain(v), v.ExtraFields)
}
