// Code generated by perseid. DO NOT EDIT.

package meteroid

import (
	"encoding/json"
	"time"
)

// Subscription is the Subscription object of the Meteroid API.
type Subscription struct {
	// When the subscription was activated (first payment or activation condition met)
	// RFC 3339 timestamp.
	ActivatedAt *time.Time `json:"activated_at,omitempty"`

	// If false, invoices will stay in Draft until manually reviewed and finalized. Default to true.
	AutoAdvanceInvoices bool `json:"auto_advance_invoices"`

	BillingDayAnchor int32 `json:"billing_day_anchor"`

	// When billing started (after any trial period)
	BillingStartDate *Date `json:"billing_start_date,omitempty"`

	// Automatically try to charge the customer's configured payment method on finalize.
	ChargeAutomatically bool `json:"charge_automatically"`

	// When the subscription was created
	// RFC 3339 timestamp.
	CreatedAt time.Time `json:"created_at"`

	Currency Currency `json:"currency"`

	// Current billing period end date
	CurrentPeriodEnd *Date `json:"current_period_end,omitempty"`

	// Current billing period start date
	CurrentPeriodStart Date `json:"current_period_start"`

	// User-defined custom property values, keyed by definition `key`.
	CustomProperties json.RawMessage `json:"custom_properties"`

	CustomerAlias *string `json:"customer_alias,omitempty"`

	CustomerID CustomerID `json:"customer_id"`

	CustomerName string `json:"customer_name"`

	// When the subscription ends (if set)
	EndDate *Date `json:"end_date,omitempty"`

	ID SubscriptionID `json:"id"`

	// Default memo for invoices
	InvoiceMemo *string `json:"invoice_memo,omitempty"`

	// Monthly recurring revenue in cents
	MrrCents int64 `json:"mrr_cents"`

	// Payment terms in days (0 = due on issue)
	NetTerms int32 `json:"net_terms"`

	PaymentMethodsConfig *PaymentMethodsConfig `json:"payment_methods_config,omitempty"`

	// Billing period (monthly, annual, etc.)
	Period BillingPeriodEnum `json:"period"`

	PlanDescription *string `json:"plan_description,omitempty"`

	PlanID PlanID `json:"plan_id"`

	PlanName string `json:"plan_name"`

	PlanVersion int32 `json:"plan_version"`

	PlanVersionID PlanVersionID `json:"plan_version_id"`

	PurchaseOrder *string `json:"purchase_order,omitempty"`

	// When the subscription contract starts (benefits apply from this date)
	StartDate Date `json:"start_date"`

	Status SubscriptionStatusEnum `json:"status"`

	// The subscription's prices are quoted tax-included (snapshotted from its plan version).
	TaxInclusive bool `json:"tax_inclusive"`

	// Trial duration in days
	TrialDuration *int32 `json:"trial_duration,omitempty"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *Subscription) UnmarshalJSON(data []byte) error {
	type plain Subscription
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "Subscription", "auto_advance_invoices", "billing_day_anchor", "charge_automatically", "created_at", "currency", "current_period_start", "customer_id", "customer_name", "id", "mrr_cents", "net_terms", "period", "plan_id", "plan_name", "plan_version", "plan_version_id", "start_date", "status", "tax_inclusive")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "activated_at", "auto_advance_invoices", "billing_day_anchor", "billing_start_date", "charge_automatically", "created_at", "currency", "current_period_end", "current_period_start", "custom_properties", "customer_alias", "customer_id", "customer_name", "end_date", "id", "invoice_memo", "mrr_cents", "net_terms", "payment_methods_config", "period", "plan_description", "plan_id", "plan_name", "plan_version", "plan_version_id", "purchase_order", "start_date", "status", "tax_inclusive", "trial_duration")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v Subscription) MarshalJSON() ([]byte, error) {
	type plain Subscription
	return marshalWithExtra(plain(v), v.ExtraFields)
}
