// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// SubscriptionAddOnPriceOverride is the SubscriptionAddOnPriceOverride object of the Meteroid API.
type SubscriptionAddOnPriceOverride struct {
	Name *string `json:"name,omitempty"`

	PriceEntry PriceEntry `json:"price_entry"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *SubscriptionAddOnPriceOverride) UnmarshalJSON(data []byte) error {
	type plain SubscriptionAddOnPriceOverride
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "SubscriptionAddOnPriceOverride", "price_entry")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "name", "price_entry")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v SubscriptionAddOnPriceOverride) MarshalJSON() ([]byte, error) {
	type plain SubscriptionAddOnPriceOverride
	return marshalWithExtra(plain(v), v.ExtraFields)
}
