// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// SubscriptionAddOn is the SubscriptionAddOn object of the Meteroid API.
type SubscriptionAddOn struct {
	AddOnID *AddOnID `json:"add_on_id,omitempty"`

	Fee SubscriptionFee `json:"fee"`

	ID *SubscriptionAddOnID `json:"id,omitempty"`

	Name string `json:"name"`

	Period SubscriptionFeeBillingPeriodEnum `json:"period"`

	Quantity int32 `json:"quantity"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *SubscriptionAddOn) UnmarshalJSON(data []byte) error {
	type plain SubscriptionAddOn
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "SubscriptionAddOn", "fee", "name", "period", "quantity")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "add_on_id", "fee", "id", "name", "period", "quantity")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v SubscriptionAddOn) MarshalJSON() ([]byte, error) {
	type plain SubscriptionAddOn
	return marshalWithExtra(plain(v), v.ExtraFields)
}
