// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// SubscriptionComponent is the SubscriptionComponent object of the Meteroid API.
type SubscriptionComponent struct {
	Fee SubscriptionFee `json:"fee"`

	Name string `json:"name"`

	Period SubscriptionFeeBillingPeriodEnum `json:"period"`

	PriceComponentID *PriceComponentID `json:"price_component_id,omitempty"`

	ProductID *ProductID `json:"product_id,omitempty"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *SubscriptionComponent) UnmarshalJSON(data []byte) error {
	type plain SubscriptionComponent
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "fee", "name", "period", "price_component_id", "product_id")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v SubscriptionComponent) MarshalJSON() ([]byte, error) {
	type plain SubscriptionComponent
	return marshalWithExtra(plain(v), v.ExtraFields)
}
