// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// TieredPlanPricing is the TieredPlanPricing object of the Meteroid API.
type TieredPlanPricing struct {
	BlockSize *int64 `json:"block_size,omitempty"`

	Tiers RequiredSlice[TierRow] `json:"tiers"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *TieredPlanPricing) UnmarshalJSON(data []byte) error {
	type plain TieredPlanPricing
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "block_size", "tiers")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v TieredPlanPricing) MarshalJSON() ([]byte, error) {
	type plain TieredPlanPricing
	return marshalWithExtra(plain(v), v.ExtraFields)
}
