// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// TierRow is the TierRow object of the Meteroid API.
type TierRow struct {
	FirstUnit int64 `json:"first_unit"`

	FlatCap *string `json:"flat_cap,omitempty"`

	FlatFee *string `json:"flat_fee,omitempty"`

	Rate string `json:"rate"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *TierRow) UnmarshalJSON(data []byte) error {
	type plain TierRow
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "TierRow", "first_unit", "rate")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "first_unit", "flat_cap", "flat_fee", "rate")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v TierRow) MarshalJSON() ([]byte, error) {
	type plain TierRow
	return marshalWithExtra(plain(v), v.ExtraFields)
}
