// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// TokenIntrospectionResponse is the TokenIntrospectionResponse object of the Meteroid API.
//
// Token introspection response as per RFC 7662
type TokenIntrospectionResponse struct {
	Active bool `json:"active"`

	ClientID *string `json:"client_id,omitempty"`

	Exp *int64 `json:"exp,omitempty"`

	Iat *int64 `json:"iat,omitempty"`

	Scope *string `json:"scope,omitempty"`

	Sub *string `json:"sub,omitempty"`

	TokenType *string `json:"token_type,omitempty"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *TokenIntrospectionResponse) UnmarshalJSON(data []byte) error {
	type plain TokenIntrospectionResponse
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "active", "client_id", "exp", "iat", "scope", "sub", "token_type")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v TokenIntrospectionResponse) MarshalJSON() ([]byte, error) {
	type plain TokenIntrospectionResponse
	return marshalWithExtra(plain(v), v.ExtraFields)
}
