// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// TokenResponse is the TokenResponse object of the Meteroid API.
//
// Token response as per OAuth 2.0 spec
type TokenResponse struct {
	AccessToken string `json:"access_token"`

	ExpiresIn int64 `json:"expires_in"`

	RefreshToken *string `json:"refresh_token,omitempty"`

	Scope *string `json:"scope,omitempty"`

	TokenType string `json:"token_type"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *TokenResponse) UnmarshalJSON(data []byte) error {
	type plain TokenResponse
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "TokenResponse", "access_token", "expires_in", "token_type")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "access_token", "expires_in", "refresh_token", "scope", "token_type")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v TokenResponse) MarshalJSON() ([]byte, error) {
	type plain TokenResponse
	return marshalWithExtra(plain(v), v.ExtraFields)
}
