// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// TokenRequest is the TokenRequest object of the Meteroid API.
//
// Token request (from POST body, application/x-www-form-urlencoded)
type TokenRequest struct {
	// Client ID (if not using HTTP Basic auth)
	ClientID *string `json:"client_id,omitempty"`

	// Client secret (if not using HTTP Basic auth)
	ClientSecret *string `json:"client_secret,omitempty"`

	// Authorization code (for authorization_code grant)
	Code *string `json:"code,omitempty"`

	// PKCE code verifier (for authorization_code grant with PKCE)
	CodeVerifier *string `json:"code_verifier,omitempty"`

	// Grant type: "authorization_code" or "refresh_token"
	GrantType string `json:"grant_type"`

	// Redirect URI (for authorization_code grant, must match the one used in /authorize)
	RedirectURI *string `json:"redirect_uri,omitempty"`

	// Refresh token (for refresh_token grant)
	RefreshToken *string `json:"refresh_token,omitempty"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *TokenRequest) UnmarshalJSON(data []byte) error {
	type plain TokenRequest
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "client_id", "client_secret", "code", "code_verifier", "grant_type", "redirect_uri", "refresh_token")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v TokenRequest) MarshalJSON() ([]byte, error) {
	type plain TokenRequest
	return marshalWithExtra(plain(v), v.ExtraFields)
}
