// Code generated by perseid. DO NOT EDIT.

package meteroid

import (
	"encoding/json"
	"time"
)

// Transaction is the Transaction object of the Meteroid API.
type Transaction struct {
	Amount int64 `json:"amount"`

	// On a PAYMENT: how much was voluntarily given back (the sum of its settled REFUND
	// children). The invoice stays paid — the Refund credit note is what reduces it.
	AmountRefunded int64 `json:"amount_refunded"`

	// On a PAYMENT: how much was involuntarily clawed back (chargeback, bank recall, lost
	// dispute). This is what the invoice nets out, reopening it.
	AmountReversed int64 `json:"amount_reversed"`

	CreditNoteID *CreditNoteID `json:"credit_note_id,omitempty"`

	Currency string `json:"currency"`

	Error *string `json:"error,omitempty"`

	ID PaymentTransactionID `json:"id"`

	ParentTransactionID *PaymentTransactionID `json:"parent_transaction_id,omitempty"`

	PaymentMethodID *CustomerPaymentMethodID `json:"payment_method_id,omitempty"`

	PaymentMethodInfo *PaymentMethodInfo `json:"payment_method_info,omitempty"`

	PaymentType PaymentTypeEnum `json:"payment_type"`

	// RFC 3339 timestamp.
	ProcessedAt *time.Time `json:"processed_at,omitempty"`

	ProviderTransactionID *string `json:"provider_transaction_id,omitempty"`

	RefundMode *RefundMode `json:"refund_mode,omitempty"`

	ReversalKind *ReversalKind `json:"reversal_kind,omitempty"`

	// The provider's raw cause, or what the operator typed when reversing by hand.
	ReversalReason *string `json:"reversal_reason,omitempty"`

	Status PaymentStatusEnum `json:"status"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *Transaction) UnmarshalJSON(data []byte) error {
	type plain Transaction
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "Transaction", "amount", "amount_refunded", "amount_reversed", "currency", "id", "payment_type", "status")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "amount", "amount_refunded", "amount_reversed", "credit_note_id", "currency", "error", "id", "parent_transaction_id", "payment_method_id", "payment_method_info", "payment_type", "processed_at", "provider_transaction_id", "refund_mode", "reversal_kind", "reversal_reason", "status")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v Transaction) MarshalJSON() ([]byte, error) {
	type plain Transaction
	return marshalWithExtra(plain(v), v.ExtraFields)
}
