// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// UnitConversion is the UnitConversion object of the Meteroid API.
type UnitConversion struct {
	Factor int32 `json:"factor"`

	Rounding UnitConversionRoundingEnum `json:"rounding"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *UnitConversion) UnmarshalJSON(data []byte) error {
	type plain UnitConversion
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "UnitConversion", "factor", "rounding")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "factor", "rounding")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v UnitConversion) MarshalJSON() ([]byte, error) {
	type plain UnitConversion
	return marshalWithExtra(plain(v), v.ExtraFields)
}
