// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// UpdateMetricRequest is the UpdateMetricRequest object of the Meteroid API.
type UpdateMetricRequest struct {
	Description *Nullable[string] `json:"description,omitempty"`

	// Absent = leave filters untouched; present (even empty) = replace them.
	Filters *Nullable[[]MetricFilter] `json:"filters,omitempty"`

	Name *Nullable[string] `json:"name,omitempty"`

	SegmentationMatrix *Nullable[MetricSegmentationMatrix] `json:"segmentation_matrix,omitempty"`

	UnitConversion *Nullable[UnitConversion] `json:"unit_conversion,omitempty"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *UpdateMetricRequest) UnmarshalJSON(data []byte) error {
	type plain UpdateMetricRequest
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "UpdateMetricRequest")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "description", "filters", "name", "segmentation_matrix", "unit_conversion")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v UpdateMetricRequest) MarshalJSON() ([]byte, error) {
	type plain UpdateMetricRequest
	return marshalWithExtra(plain(v), v.ExtraFields)
}
