// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// UpdateAddOnRequest is the UpdateAddOnRequest object of the Meteroid API.
type UpdateAddOnRequest struct {
	Description *Nullable[string] `json:"description,omitempty"`

	MaxInstancesPerSubscription *Nullable[int32] `json:"max_instances_per_subscription,omitempty"`

	Name *Nullable[string] `json:"name,omitempty"`

	PriceID *Nullable[PriceID] `json:"price_id,omitempty"`

	SelfServiceable *Nullable[bool] `json:"self_serviceable,omitempty"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *UpdateAddOnRequest) UnmarshalJSON(data []byte) error {
	type plain UpdateAddOnRequest
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "UpdateAddOnRequest")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "description", "max_instances_per_subscription", "name", "price_id", "self_serviceable")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v UpdateAddOnRequest) MarshalJSON() ([]byte, error) {
	type plain UpdateAddOnRequest
	return marshalWithExtra(plain(v), v.ExtraFields)
}
