// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// UsageResponse is the UsageResponse object of the Meteroid API.
type UsageResponse struct {
	PeriodEnd Date `json:"period_end"`

	PeriodStart Date `json:"period_start"`

	Usage RequiredSlice[MetricUsage] `json:"usage"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *UsageResponse) UnmarshalJSON(data []byte) error {
	type plain UsageResponse
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "UsageResponse", "period_end", "period_start", "usage")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "period_end", "period_start", "usage")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v UsageResponse) MarshalJSON() ([]byte, error) {
	type plain UsageResponse
	return marshalWithExtra(plain(v), v.ExtraFields)
}
