// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// UsageFee is the UsageFee object of the Meteroid API.
type UsageFee struct {
	MetricID BillableMetricID `json:"metric_id"`

	Model UsagePricingModel `json:"model"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *UsageFee) UnmarshalJSON(data []byte) error {
	type plain UsageFee
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "UsageFee", "metric_id", "model")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "metric_id", "model")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v UsageFee) MarshalJSON() ([]byte, error) {
	type plain UsageFee
	return marshalWithExtra(plain(v), v.ExtraFields)
}
