// Code generated by perseid. DO NOT EDIT.

package meteroid_test

import (
	"testing"
)

func TestWebhookEndpoints_ResendWebhookDelivery(t *testing.T) {
	client, requests := mock(200, "application/json", `{"attempt_count":-2147483648,"created_at":"2023-12-31T23:59:59.999-05:30","endpoint_id":"webhook_endpoint_id_44","event_type":"sample","id":"webhook_delivery_id_90","manual":false,"message_id":"event_id_90","status":"IN_FLIGHT"}`)
	call(t, client.WebhookEndpoints().ResendWebhookDelivery, "delivery_id")
	expect(t, requests, "POST /api/v1/webhooks/deliveries/delivery_id/resend")
}
