// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// WebhookEndpointSecret is the WebhookEndpointSecret object of the Meteroid API.
type WebhookEndpointSecret struct {
	Secret string `json:"secret"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *WebhookEndpointSecret) UnmarshalJSON(data []byte) error {
	type plain WebhookEndpointSecret
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "WebhookEndpointSecret", "secret")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "secret")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v WebhookEndpointSecret) MarshalJSON() ([]byte, error) {
	type plain WebhookEndpointSecret
	return marshalWithExtra(plain(v), v.ExtraFields)
}
