// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// WebhookHeaderInput is the WebhookHeaderInput object of the Meteroid API.
//
// A custom header to send with every delivery. A sensitive header is write-only:
// it is never returned, and on update sending it without a value keeps its value.
type WebhookHeaderInput struct {
	Name string `json:"name"`

	Sensitive *bool `json:"sensitive,omitempty"`

	Value *string `json:"value,omitempty"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *WebhookHeaderInput) UnmarshalJSON(data []byte) error {
	type plain WebhookHeaderInput
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	fields, err := objectFields(data, "WebhookHeaderInput", "name")
	if err != nil {
		return err
	}
	v.ExtraFields = extraFields(fields, "name", "sensitive", "value")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v WebhookHeaderInput) MarshalJSON() ([]byte, error) {
	type plain WebhookHeaderInput
	return marshalWithExtra(plain(v), v.ExtraFields)
}
