// Code generated by perseid. DO NOT EDIT.

package meteroid

// WebhookEndpointDisabledReason is one of [AllWebhookEndpointDisabledReasonValues], or a value this SDK version
// does not know.
type WebhookEndpointDisabledReason string

// Known values of WebhookEndpointDisabledReason.
//
// The API may add new values over time; unknown values round-trip unchanged.
const (
	WebhookEndpointDisabledReasonManual       WebhookEndpointDisabledReason = "MANUAL"
	WebhookEndpointDisabledReasonAutoFailures WebhookEndpointDisabledReason = "AUTO_FAILURES"
	WebhookEndpointDisabledReasonGone         WebhookEndpointDisabledReason = "GONE"
)

// AllWebhookEndpointDisabledReasonValues lists every WebhookEndpointDisabledReason value known to this SDK version.
var AllWebhookEndpointDisabledReasonValues = []WebhookEndpointDisabledReason{
	WebhookEndpointDisabledReasonManual,
	WebhookEndpointDisabledReasonAutoFailures,
	WebhookEndpointDisabledReasonGone,
}

// String returns the wire representation of the value.
func (e WebhookEndpointDisabledReason) String() string {
	return string(e)
}

// IsKnown reports whether the value is one this SDK version knows about.
func (e WebhookEndpointDisabledReason) IsKnown() bool {
	for _, known := range AllWebhookEndpointDisabledReasonValues {
		if e == known {
			return true
		}
	}
	return false
}
